### ISSUE TITLE
Translate section title in Japanese

### ISSUE THREAD

**Issue by cstoku** [kubernetes/website#10821]
**This is a...**

* [x]  Feature Request
* [ ]  Bug Report

**Problem:**
Some section titles aren't Japanese.

**Proposed Solution:**
Translate section title in Japanese.
Copy from en contents and update the files listed below.

- [x] content/ja/docs/_index.md (#11422, #11721)
- [x] content/ja/docs/home/_index.md (#11569)
- [x] content/ja/docs/setup/custom-cloud/_index.md (#11572)
- [x] content/ja/docs/setup/independent/_index.md (#11573)
- [x] content/ja/docs/setup/on-premises-vm/_index.md (#11574)
- [x] content/ja/docs/setup/release/_index.md (#11576)
- [x] content/ja/docs/setup/turnkey/_index.md (#11582)
- [x] content/ja/docs/tutorials/kubernetes-basics/create-cluster/_index.md (#11575, #12059)
- [x] content/ja/docs/tutorials/kubernetes-basics/deploy-app/_index.md (#11583)
- [x] content/ja/docs/tutorials/kubernetes-basics/explore/_index.md (#11580)
- [x] content/ja/docs/tutorials/kubernetes-basics/expose/_index.md (#11584)
- [x] content/ja/docs/tutorials/kubernetes-basics/scale/_index.md (#11577)
- [x] content/ja/docs/tutorials/kubernetes-basics/update/_index.md (#11579)

**Page to Update:**
Several pages including TOC.

**Comment by bells17** [comment]
content/ja/docs/home/_index.md
こちらやります

**Comment by bells17** [comment]
content/ja/docs/setup/custom-cloud/_index.md
こちらやります

**Comment by hhiroshell** [comment]
content/ja/docs/tutorials/kubernetes-basics/create-cluster/_index.md
こちらやりまっす。

**Comment by lkougi** [comment]
content/ja/docs/setup/independent/_index.md
これやります！

**Comment by bells17** [comment]
content/ja/docs/setup/on-premises-vm/_index.md
こちらやります

**Comment by bells17** [comment]
content/ja/docs/setup/release/_index.md
こちらやります

**Comment by hmaruyama** [comment]
content/ja/docs/setup/turnkey/_index.md
こちらやります！

**Comment by dzeyelid** [comment]
content/ja/docs/tutorials/kubernetes-basics/deploy-app/_index.md
こちらやります！

**Comment by hhiroshell** [comment]
コレやります。
content/ja/docs/tutorials/kubernetes-basics/explore/_index.md

**Comment by bells17** [comment]
content/ja/docs/tutorials/kubernetes-basics/scale/_index.md
こちらやります

**Comment by lkougi** [comment]
content/ja/docs/tutorials/kubernetes-basics/expose/_index.md
こちらやります
