### ISSUE TITLE
Tracking Indonesian Translation Progress (M1)

### ISSUE THREAD

**Issue by girikuncoro** [kubernetes/website#13929]
## Maintainers
* @girikuncoro
* @irvifa 

## For New Contributors
To translate a page:
1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. Take only one page at a time.
3. Fork this repo, make your translations, and submit a pull request with `language/id` label!

For more detailed instruction, consult with this [JK8s guide](https://github.com/jk8s/sig-docs-id-localization-how-tos#getting-started). Before contributing, read the [glossary](https://github.com/jk8s/sig-docs-id-localization-how-tos#glossary) and the [RSNI Glosarium from Ivan Lanin](https://github.com/jk8s/sig-docs-id-localization-how-tos/blob/master/resources/RSNI-glossarium.pdf) to understand how to translate various technical and Kubernetes-specific terms. (If you're still not sure about something, please don't hesitate to ask in [Slack channel](https://kubernetes.slack.com/messages/CJ1LUCUHM), we won't bite 😄)

Also, we haven't written special style guide for writing Bahasa Indonesia. However, in general we can follow the [English style guide](https://kubernetes.io/docs/contribute/style/style-guide/) with some addition to italicizing imported words.

Please commit with your translations! If you find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For maintainers
When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

- [x] Init Kubernetes ID (@girikuncoro) #13822 

When PRs are merged, make sure to mark that page as completed!

# Work Status
(🏃 Work in Progress; 👀 In Review)

This is our first milestone (M1) that we aim to complete during the lifespan of Kubernetes v1.14. We will mostly focus on `concept`. Since 1.15 release cycle is short, we will do cut, move left overs to next milestone, and perform technical review when that happens in June.

### Architecture (`content/id/docs/concepts/architecture`)
- [ ] 🏃Cloud Controller (@phanama)
- [x] Master Node Communication (@girikuncoro) #13887 
- [x] Nodes (@girikuncoro) #13887 

### Cluster Administration (`content/id/docs/concepts/cluster-administration`)
- [x] Addons (@danninov) #14165
- [ ] Certificates
- [x] Cloud Providers (@danninov) #14015
- [x] Cluster Administration Overview (@danninov) #14156
- [x] Controller Metrics (@danninov) #14229
- [x] Federation (@irvifa) #14148
- [x] Kubelet Garbage Collection (@girikuncoro) #14224
- [ ] Logging
- [ ] Manage Deployment
- [ ] Networking
- [ ] Proxies

### Configuration (`content/id/docs/concepts/configuration`)
- [ ] 🏃Assign Pod Node (@marchellametta)
- [ ] 🏃Manage Compute Resources Container (@digembok)
- [ ] Organize Cluster Access Kubeconfig
- [ ] Overview
- [ ] Pod Priority Preemption
- [ ] Scheduler Perf Tuning
- [ ] 👀 Secret (@irvifa) #14792
- [x] Taint and Toleration (@irvifa) #14405

### Containers (`content/id/docs/concepts/containers`)
- [x] Container Environment Variables (@girikuncoro) #13978
- [x] Container Lifecycle Hooks (@girikuncoro) #14089
- [ ] 🏃 Images (@andriiginting)
- [x] Runtime Class (@girikuncoro) #14222

### Extend Kubernetes (`content/id/docs/concepts/extend-kubernetes`)
- [ ] Extend Cluster
- [ ] Poseidon Firmament Alternate Scheduler
- [ ] Service Catalog
- [ ] API Server Aggregation
- [ ] Custom Resources
- [ ] Device Plugins
- [ ] Network Plugins

### Overview (`content/id/docs/concepts/overview`)
- [x] Components (@irvifa) #13888
- [x] Kubernetes API (@irvifa) #13888
- [x] What is Kubernetes (@irvifa) #13888
- [x] Declarative Config (@qbl) #14030
- [x] Imperative Command (@qbl) #14064 
- [x] Imperative Config (@qbl) #14530
- [ ] 🏃Kustomization (@qbl)
- [ ] Overview
- [x] Annotations (@girikuncoro) #14235
- [ ] Common Labels
- [x] Field Selectors (@girikuncoro) #14236
- [x] Kubernetes Objects (@irvifa) #14125
- [ ] Labels
- [x] Names (@iputra) #14320
- [x] Namespaces (@zufardhiyaulhaq) #14128

### Policy (`content/id/docs/concepts/policy`)
- [ ] Pod Security Policy
- [ ] Resource Quotas

### Services Networking (`content/id/docs/concepts/services-networking`)
- [ ] Add Entries to Pod etcd hosts with host aliases
- [x] Connect Applications Service (@zufardhiyaulhaq) #14079 
- [ ] DNS Pod Service
- [x] Ingress Controllers (@irvifa) #13959
- [x] Ingress (@irvifa) #13958 
- [x] Network Policies (@irvifa) #14287
- [x] Service (@irvifa) #14117

### Storage (`content/id/docs/concepts/storage`)
- [ ]  🏃Dynamic Provisioning (@girikuncoro)
- [x] Persistent Volumes (@evanap) #14532
- [ ] Storage Classes
- [x] Storage Limits (@girikuncoro) #13929
- [ ] Volume Snapshot Classes
- [ ] Volume Snapshots
- [ ] Volumes

### Workloads (`content/id/docs/concepts/workloads`)
- [x] Cron Jobs (@yohanesmario) #14382
- [ ] Daemonset
- [ ] Deployment
- [x]  Garbage Collection (@antoooks ) #14513
- [ ] Jobs Run to Completion
- [ ] 🏃 Replicaset (@yohanesmario)
- [ ] Replication Controller
- [ ] StatefulSet
- [ ] TTL After Finished
- [x] Disruptions (@phanama) #14395
- [ ] 👀 Init Containers (@phanama) #14927
- [ ] 🏃 Pod Lifecycle (@wahyuoi)
- [x] Pod Overview (@zufardhiyaulhaq) #13968
- [ ] Pod
- [x] Pod Preset (@antoooks) #14394

*Note: This contribution template is inspired by Indonesian folks translating [reactjs doc](https://github.com/reactjs/id.reactjs.org/issues/1)*

Related Docs:
1. [RSNI glossary](https://github.com/jk8s/sig-docs-id-localization-how-tos/blob/master/resources/RSNI-glossarium.pdf)
2. [Branching Strategy](https://kubernetes.io/docs/contribute/localization/#branching-strategy)

**Comment by girikuncoro** [comment]
I'm taking Cluster Administration Overview for `Cluster Administration (content/id/docs/concepts/cluster-administration)` next

**Comment by irvifa** [comment]
I'm taking `Services Networking` section for my own milestones and separate it for few PR.

**Comment by girikuncoro** [comment]
I'm taking page `proxies` of Cluster Administration (content/id/docs/concepts/cluster-administration)

**Comment by qbl** [comment]
I'm taking `Declarative Config` of Overview (content/id/docs/concepts/overview)

**Comment by remyleone** [comment]
You can also use this script to know if a given file is touched by which PR: https://github.com/kubernetes/website/blob/master/scripts/find_pr.py By doing so, you can have a single source of truth about whether a file is currently being modified or not.

**Comment by danninov** [comment]
I'm taking `Cloud Providers` of Cluster Administration (content/id/docs/concepts/cluster-administration)

**Comment by girikuncoro** [comment]
> You can also use this script to know if a given file is touched by which PR: https://github.com/kubernetes/website/blob/master/scripts/find_pr.py By doing so, you can have a single source of truth about whether a file is currently being modified or not.

@remyleone cool thanks remy we'll try it out, probably automate this somehow

**Comment by zufardhiyaulhaq** [comment]
I'm taking `Pod Overview` of Workloads (content/id/docs/concepts/workloads)

**Comment by irvifa** [comment]
@remyleone Cool.. thanks for your suggestions..

**Comment by irvifa** [comment]
I'll take `Services Networking` `Service.md`

**Comment by girikuncoro** [comment]
I'm taking Container Environment Variables, Container Lifecycle Hooks, Runtime Class of Containers (content/id/docs/concepts/containers) next

**Comment by zufardhiyaulhaq** [comment]
I'm taking `Connect Applications Service` of `Services Networking (content/id/docs/concepts/services-networking)`

**Comment by qbl** [comment]
I've sent PR for Declarative Config of Overview (content/id/docs/concepts/overview). I'm taking Imperative Command of Overview (content/id/docs/concepts/overview) next.

**Comment by qbl** [comment]
I've sent [PR](https://github.com/kubernetes/website/pull/14064) for Imperative Command of Overview (content/id/docs/concepts/overview). I'm taking Imperative Config (content/id/docs/concepts/overview) next.

**Comment by zufardhiyaulhaq** [comment]
I've sent [PR](https://github.com/kubernetes/website/pull/14079) for Connecting Applications with Services  (content/id/docs/concepts/workloads). I'm taking Namespaces (content/id/docs/concepts/overview) next.

**Comment by irvifa** [comment]
I'm taking Federation.md content/id/docs/concepts/cluster-administration

**Comment by irvifa** [comment]
I'm taking kubernetes-object.md content/id/docs/concepts/overview

**Comment by iputra** [comment]
I am taking `names` of Overview (content/id/docs/concepts/overview)

**Comment by zufardhiyaulhaq** [comment]
I've sent PR #14128 for Namespaces (content/id/docs/concepts/overview). I'm taking Overview (content/id/docs/concepts/configuration) next.

**Comment by danninov** [comment]
I'm taking cluster-administration-overview.md (concepts/cluster-administration/cluster-administration-overview)

**Comment by danninov** [comment]
I'm taking Addons (cluster-administration/addons)

**Comment by irvifa** [comment]
I'm taking `NetworkPolicy` in `content/id/docs/concepts/services-networking`

**Comment by danninov** [comment]
I'm taking `Controller Metrics` in (concepts/cluster-administration)

**Comment by girikuncoro** [comment]
I'm taking `Kubelet Garbage Collection` in (concepts/cluster-administration) next

**Comment by girikuncoro** [comment]
I'm taking `Field Selectors` in (concepts/overview) next

**Comment by girikuncoro** [comment]
I'm taking `Annotations` in (concepts/overview) next

**Comment by andriiginting** [comment]
Hi guys, I'm  taking `images` in `content/id/docs/concepts/containers`

**Comment by yohanesmario** [comment]
Hi guys, I'm taking `Cron Jobs` in `content/id/docs/concepts/workloads`

**Comment by phanama** [comment]
I'm taking `Disruptions` in `concepts/workloads`

**Comment by wahyuoi** [comment]
Hi, I'm taking `Pod Lifecycle` in `content/id/docs/concepts/workloads`

**Comment by evanap** [comment]
Hi, I'm taking `Persistent Volumes` in `content/id/docs/concepts/storage`

**Comment by marchellametta** [comment]
I'm taking `Assign Pod Node` in `content/id/docs/concepts/configuration`

**Comment by irvifa** [comment]
I'm taking Taint and Toleration

**Comment by antoooks** [comment]
Hello, I'm taking `Pod Preset` in `content/id/docs/concepts/workloads`

**Comment by girikuncoro** [comment]
I'm taking Dynamic Provisioning and Storage Limits of `content/id/docs/concepts/storage`

**Comment by irvifa** [comment]
I'm taking secret

**Comment by yohanesmario** [comment]
I've sent PR for CronJob (#14382), and would like to continue to take `ReplicaSet` in `content/id/docs/concepts/workloads`.

**Comment by antoooks** [comment]
I'll be taking `Garbage Collection` in `content/id/docs/concepts/workloads`.

**Comment by phanama** [comment]
I'm taking `Init Containers` in `concepts/workloads`.
.
.
.
You have a typo in the list above: Init Contianers

**Comment by qbl** [comment]
I've sent PR for Imperative Config of Overview (content/id/docs/concepts/overview). I'm taking Kustomization of Overview (content/id/docs/concepts/overview) next.

**Comment by digembok** [comment]
I'm taking `Manage Compute Resources Container` in `content/id/docs/concepts/configuration`

**Comment by phanama** [comment]
I'm taking Cloud Controller in `content/id/docs/concepts/architecture`

**Comment by girikuncoro** [comment]
Hi folks, thank you so much for your contribution to translate Kubernetes docs into Bahasa Indonesia, it means a lot to broader audience/community in Indonesia! 🎉

Since Kubernetes 1.15 has been released, and 1.16 cycle is currently on, we are planning to cut this Milestone 1 on Monday, 24th July 2019. So far we have gathered good statistics for this M1: 35 pages have been translated from 15 contributors!

Will continue the pages that could not get in to Milestone 2 (next 3 months cycle until 1.16 release cut). Will post the M2 issue tracker soon and close this issue.

**Comment by koneko096** [comment]
I'm taking `Manage Deployment` page (`content/id/docs/concepts/cluster-administration/manage-deployment/`)

**Comment by phanama** [comment]
I'm taking Volumes in `content/id/docs/concepts/storage`

**Comment by girikuncoro** [comment]
Thanks for all your contribution in M1! 🎉🎉
We will continue with the rest of pages in M2, tracked here #15341 

Please mention the new issue id when raising PR. Closing this.
