### ISSUE TITLE
Tracking Hindi localisation progress

### ISSUE THREAD

**Issue by avidLearnerInProgress** [kubernetes/website#13957]
## Maintainers

-   [@Rajakavitha1](https://github.com/Rajakavitha1)
-   [@daminisatya](https://github.com/daminisatya)
-   [@mittalyashu](https://github.com/mittalyashu)
-   [@avidLearnerInProgress](https://github.com/avidLearnerInProgress)

## For New Contributors

Refer this spreadsheet for the most common and frequently used words that are required for localization:- [Hindi-language team glossary](https://docs.google.com/spreadsheets/d/1UmL4K0v4yaN34k4WzYDZBobLBp5OZQp4GCTi28AfwQM/edit?usp=sharing)

To translate a page:

1.  Check that no one else has claimed your page in the checklist and comments below.
2.  Comment below with the name of the page you would like to translate. Take only one page at a time.
3.  Fork this repo, make your localisations, and submit a pull request following the name convention `[Add/Update/Fix] [content/hi/file/full/path]`, for example:

-   `Add content/hi/docs/concepts/architecture/nodes.md`
-   `Update content/hi/setup/release/building-from-source.md`

**Points to remember:**
1. You can use this script to know if a given file is touched by which PR: https://github.com/kubernetes/website/blob/master/scripts/find_pr.py By doing so, you can have a single source of truth about whether a file is currently being modified or not.
2. Please use the word **_localisation_** instead of **_translation_** in your PR and comments.
3. Every new contribution should start with a new branch from `master`

For more detailed instruction, check the [website README](https://git.kubernetes.io/website/README-hi.md). Before contributing to docs, read the [Community Documentation Style Guide](https://git.kubernetes.io/community/contributors/guide/style-guide.md) and the [Kubernetes Documentation Style Guide](https://kubernetes.io/docs/contribute/style/style-guide/).

If you're still not sure about something, please don't hesitate to ask in [Slack channel](https://kubernetes.slack.com/messages/CH7GB2E3B).

Please commit with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

-   Init Hindi localisation ([@mittalyashu](https://github.com/mittalyashu)) [#13910](https://github.com/kubernetes/website/pull/13910)

When PRs are merged, make sure to mark that page as completed!

# Work Status

This is our first milestone (M1) that we aim to complete during the lifespan of Kubernetes v1.14. 
If you are interested in working on something is not listed here  
Since 1.15 release cycle is short, we will do cut, move leftovers to next milestone, and perform a technical review when that happens in June.

### Website

- [ ] Landing (@mittalyashu) #15551
- [ ] Partners
- [ ]  Blog 
- [ ] Community 
  - [ ] Contributor cheatsheet (@avidLearnerInProgress) #14001 
- [ ] Update imported docs (@avidLearnerInProgress) #13936, #13919

### Docs

- [ ] Index tree
- [x] Home landing (@mittalyashu ) #13910 
- [ ] Concepts landing 
- [ ] Contribute landing 
- [ ] Setup landing 
- [ ] Tasks landing
- [ ] Partners landing (@saarques) #13916 #13911
- [ ] Reference landing 
- [ ] Concepts landing  (@jidroid404) #13922

### Architecture (`content/en/docs/concepts/architecture`)

- [ ] Nodes (@avidLearnerInProgress) #13960 
- [ ] Cloud Controller (@avidLearnerInProgress) #13960 
- [ ] Master Node Communication (@avidLearnerInProgress) #13960 

### Configuration (`content/en/docs/concepts/configuration`)

- [ ] Assign Pod Node
- [ ] Manage Compute Resources Container
- [ ] Organize Cluster Access Kubeconfig
- [ ] Overview
- [ ] Pod Priority Preemption
- [ ] Scheduler Perf Tuning
- [ ] Secret
- [ ] Taint and Toleration

### Containers (`content/en/docs/concepts/containers`)

- [ ]  Container Environment Variables
- [ ] Container Lifecycle Hooks
- [ ] Images
- [ ] Runtime Class

### Overview (`content/en/docs/concepts/overview`)

- [ ] Components
- [ ] Kubernetes API
- [ ] What is Kubernetes 
- [ ] Declarative Config
- [ ] Imperative Command
- [ ] Imperative Config
- [ ] Kustomization
- [ ] Overview
- [ ] Annotations
- [ ] Common Labels
- [ ] Field Selectors
- [ ] Kubernetes Objects
- [ ] Labels
- [ ] Names
- [ ] Namespaces

### Workloads (`content/en/docs/concepts/workloads`)

- [ ] Cron Jobs
- [ ] Daemonset
- [ ] Deployment
- [ ] Garbage Collection
- [ ] Jobs Run to Completion
- [ ] Replicaset
- [ ] Replication Controller
- [ ] StatefulSet
- [ ] TTL After Finished
- [ ] Disruptions
- [ ] Init Contianers
- [ ] Pod Lifecycle
- [ ] Pod Overview
- [ ] Pod
- [ ] Pod Preset

### Tools (`content/hi/docs/tasks/tools`)

- [ ] Install kubectl
- [ ] Install minikube 

### Debug application cluster (`content/hi/docs/tasks/debug-application-cluster`)

- [ ] Resource metrics pipeline

### Run application (`content/hi/docs/tasks/run-application`)

- [ ]   Configure PDB 
- [ ]  Run Sateless application deployment 

_Note: This contribution template is inspired by reactjs folks translating [reactjs doc](https://github.com/reactjs/id.reactjs.org/issues/1) and the sig-docs-id team._

**Comment by mittalyashu** [comment]
This progress is super useful.

**Comment by mittalyashu** [comment]
This PR https://github.com/kubernetes/website/pull/13910 is ready to get merged.

**Comment by jidroid404** [comment]
* Concepts landing @jidroid404 (#13922)

**Comment by saarques** [comment]
This PR #13916 is ready to get merged.
This PR #13950 is ready to get merged.

**Comment by saarques** [comment]
This PR #13950 is ready to get merged for the issue #13947 .

**Comment by mittalyashu** [comment]
OMG!!! We have added a hindi label.

**Comment by mittalyashu** [comment]
Can you update the description, with the information that every new contribution should start with a new branch from `master`?

**Comment by mittalyashu** [comment]
I am working on the Landing page https://github.com/kubernetes/website/pull/14069

@saarques is working on the partner's page https://github.com/kubernetes/website/pull/13916

**Comment by avidLearnerInProgress** [comment]
> 
> 
> Can you update the description, with the information that every new contribution should start with a new branch from `master`?
Sure, I will!

**Comment by mittalyashu** [comment]
@avidLearnerInProgress To make this issue run for a longer period we need to re-structure it a bit.

**Comment by Aut0R3V** [comment]
Oh damn!
I didn't knew there were translations happening in Hindi aw!!

**Comment by Aut0R3V** [comment]
What can I do here @mittalyashu @saarques @sftim

**Comment by anubha-v-ardhan** [comment]
Lets start!!!
I'm working on translating contents/en/partners

**Comment by anubha-v-ardhan** [comment]
I'm working on https://github.com/kubernetes/website/tree/main/content/en/community next

**Comment by verma-kunal** [comment]
Hey, i'll be starting to work on the Blog section from today
Link: https://github.com/kubernetes/website/tree/main/content/en/blog

**Comment by anubha-v-ardhan** [comment]
@verma-kunal Please go through other language localization to get an idea about Blogs section. Thanks

**Comment by verma-kunal** [comment]
Thanks for pointing it out!! 
asked in the slack channel to be clear on the things 🙂

**Comment by anubha-v-ardhan** [comment]
Folks! we are continuing the effort on new issue #29353

**Comment by sftim** [comment]
/close
in favor of #29353
