### ISSUE TITLE
Tracking German localisation progress

### ISSUE THREAD

**Issue by mkorbi** [kubernetes/website#14137]
# Maintainers

@bene2k1
@rlenferink
@mkorbi

# For New Contributors

To translate a page:
1. Check that no one else has claimed your page in the checklist and comments below.
2. Most wanted pages can be found here: https://github.com/kubernetes/website/issues/17598
3. Comment below with the name of the page you would like to translate. Take only one page at a time.
4. Fork this repo, make your localisations, and submit a pull request following the name convention [Add/Update/Fix] [content/de/file/full/path], for example:

* Add content/de/docs/concepts/architecture/nodes.md
* Update content/de/setup/release/building-from-source.md

**Points to remember:**

* Please use the word localization instead of translation in your PR and comments.
* Every new contribution should start with a new branch from master

For more detailed instructions, check the [website README](https://github.com/kubernetes/website/blob/master/README-de.md). Before contributing to docs, read the [Community Documentation Style Guide](https://github.com/kubernetes/community/blob/master/contributors/guide/style-guide.md) and the [Kubernetes Documentation Style Guide](https://kubernetes.io/docs/contribute/style/style-guide/).

You can also find some useful scripts [here](https://github.com/kubernetes/website/tree/master/scripts) like the [find pr](https://github.com/kubernetes/website/blob/master/scripts/find_pr.py) to find PRs for given files.

If you're still not sure about something, please don't hesitate to ask in Slack channel **kubernetes-docs-de**
--
# Main

## Website
  - [X] Landing
  - [X] Partners
  - [ ] Blog
  - [X] Community
  - [x] Contributor cheatsheet 
  - [X] Case Studies
## Docs
  - [X] Index tree
  - [X] Home landing
  - [X] Concepts landing
  - [X] Contribute landing
  - [X] Setup landing
  - [X] Tasks landing
  - [X] Partners landing
  - [X] Reference landing
  - [X] Concepts landing

# Setup
- [ ] Picking the Right Solution
- [ ] Kubernetes Version and Version Skew Support Policy
- [ ] Building Large Clusters
- [ ] Running in Multiple Zones
- [ ] CRI installation
- [ ] Installing Kubernetes with Digital Rebar Provision (DRP) via KRIB
- [ ] PKI Certificates and Requirements
- [ ] Running Kubernetes Locally via Minikube
- [ ] Validate Node Setup
## Downloading Kubernetes
- [X] Building a release
## Bootstrapping Clusters with kubeadm
- [ ] Install kubeadm
- [ ] Creating a single master cluster with kubeadm
- [ ] Customizing control plane configuration with kubeadm
- [ ] Options for Highly Available Topology
- [ ] Creating Highly Available Clusters with kubeadm
- [ ] Set up a High Availability etcd cluster with kubeadm
- [ ] Configuring each kubelet in your cluster using kubeadm
- [ ] Troubleshooting kubeadm
## Turnkey Cloud Solutions
- [ ] Running Kubernetes on AWS EC2
- [ ] Running Kubernetes on Alibaba Cloud
- [ ] Running Kubernetes on Azure
- [ ] Running Kubernetes on CenturyLink Cloud
- [ ] Running Kubernetes on Google Compute Engine
- [ ] Running Kubernetes on Multiple Cloud with IBM Cloud Private
- [ ] Running Kubernetes on Multiple Clouds with Stackpoint.io
## Custom Cloud Solutions
- [ ] Installing Kubernetes On-premises/Cloud Providers with Kubespray
- [ ] Installing Kubernetes on AWS with kops
## On-Premises VMw
- [ ] Cloudstack
- [ ] Kubernetes on DC/OS
- [ ] oVirt
## Windows in Kubernetes
- [ ] Intro to Windows supporting in Kubernetes
- [ ] Guide for adding Windows Nodes in Kubernetes
- [ ] Guide for scheduling Windows container in Kubernetes

# Concepts
## Overview (content/en/docs/concepts/overview)
  - [X] Components
  - [ ] Kubernetes API
  - [X] What is Kubernetes
  - [ ] Declarative Config
  - [ ] Imperative Command
  - [ ] Imperative Config
  - [ ] Kustomization
  - [ ] Overview
  - [ ] Annotations
  - [ ] Common Labels
  - [ ] Field Selectors
  - [ ] Kubernetes Objects
  - [ ] Labels
  - [ ] Names
  - [ ] Namespaces
## Kubernetes Architecture (content/en/docs/concepts/architecture)
  - [X] Nodes
  - [X] Cloud Controller
  - [X] Master Node Communication
## Containers (content/en/docs/concepts/containers)
  - [ ] Container Environment Variables
  - [ ] Container Lifecycle Hooks
  - [x] Images
  - [ ] Runtime Class
## Workloads (content/en/docs/concepts/workloads)
  - [ ] Cron Jobs
  - [ ] Daemonset
  - [ ] Deployment
  - [ ] Garbage Collection
  - [ ] Jobs Run to Completion
  - [ ] ReplicaSet
  - [ ] ReplicationController
  - [ ] StatefulSet
  - [ ] TTL Controller for Finished Resources
  - [ ] Disruptions
  - [ ] Init Contianers
  - [ ] Pod Lifecycle
  - [ ] Pod Overview
  - [ ] Pods
  - [ ] Pod Preset
## Services, Load Balancing and Networking
- [ ] Services
- [ ] DNS for Services and Pods
- [ ] Ingress
- [ ] Ingress Controllers
- [ ] Network Policies
- [ ] Adding entries to Pod /etc/hosts with Hots Aliases
## Storage
- [ ] Volumes
- [ ] Persistent Volumes
- [ ] Storage Classes
- [ ] Volume Snapshot Classes
- [ ] Dynamic Volume Provisioning
- [ ] Node-specific Volume Limits
## Configuration (content/en/docs/concepts/configuration)
  - [ ] Assign Pod Node
  - [ ] Manage Compute Resources Container
  - [ ] Organize Cluster Access Kubeconfig
  - [ ] Assigning Pods to Nodes
  - [ ] Configuration Best Practices
  - [ ] Pod Priority Preemption
  - [ ] Scheduler Performance Tuning
  - [ ] Secrets
  - [ ] Taint and Toleration
## Policies
- [ ] Resources Quotas
- [ ] Pod Security Policies
## Cluster Administration
- [ ] Cluster Admin Overview
- [ ] Certificates
- [ ] Cloud Providers
- [ ] Managing Resources
- [ ] Cluster Networking
- [ ] Logging Architecture
- [ ] Configuring kubelet Garbage Collection
- [ ] Federation
- [X] Proxies in Kubernetes
- [X] Controller manager metrics
- [ ] Installing Addons
## Extending Kubernetes
- [ ] Extending your Kubernetes Cluster
- [ ] Extending the Kubernetes API with the aggregation layer
- [ ] Custom Resources
- [ ] Network Plugins
- [ ] Device Plugins
- [ ] Service Catalog
- [ ] Poseidon-Firmament - An alternate scheduler

# Tasks
- [ ] Extend kubectl with plugins
- [ ] Manage HugePages
- [ ] Schedule GPUs
## Install Tools
- [X] Install and Set up kubectl
- [X] Install Minikube
## Configure Pods and Containers
- [ ] Assign Memory Resources to Containers and Pods
- [ ] Assign CPU Resources to Containers and Pods
- [ ] Configure GMSA for Windows pods and containers
- [ ] Configure Quality of Service for Pods
- [ ] Assign Extended Resources to a Container
- [ ] Configure a Pod to Use a Volume for Storage
- [ ] Configure a Pod to Use a PersistentVolume for Storage
- [ ] Configure a Pod to Use a Projected Volume for Storage
- [ ] Configure a Security Context for a Pod or Container
- [ ] Configure Service Accounts for Pods
- [ ] Pull an Image from a Private Registry
- [ ] Configure Liveness and Readiness Probes
- [ ] Assign Pods to Nodes
- [ ] Configure Pod Initialization
- [ ] Attach Handlers to Container Lifecycle Events
- [ ] Configure a Pod to Use a ConfigMap
- [ ] Share Process Namespace between Containers in a Pod
- [ ] Translate a Docker Compose File to Kubernetes Resources
## Administer a Cluster
- [ ] Certificate Management with kubeadm
- [ ] Configure Default Memory Requests and Limits for a Namespace
- [ ] Configure Default CPU Requests and Limits for a Namespace
- [ ] Configure Minimum and Maximum Memory Constraints for a Namespace
- [ ] Configure Minimum and Maximum CPU Constraints for a Namespace
- [ ] Configure Memory and CPU Quotas for a Namespace
- [ ] Configure a Pod Quota for a Namespace
- [ ] Use Calico for NetworkPolicy
- [ ] Use Cilium for NetworkPolicy
- [ ] Use Kube-router for NetworkPolicy
- [ ] Romana for NetworkPolicy
- [ ] Weave Net for NetworkPolicy
- [ ] Access Clusters Using the Kubernetes API
- [ ] Access Services Running on Clusters
- [ ] Advertise Extended Resources for a Node
- [ ] Autoscale the DNS Service in a Cluster
- [ ] Change the Reclaim Policy of a PersistentVolume
- [ ] Change the default StorageClass
- [ ] Cluster Management
- [ ] Configure Multiple Schedulers
- [ ] Configure Out Of Resource Handling
- [ ] Configure Quotas for API Objects
- [ ] Control CPU Management Policies on the Node
- [ ] Customizing DNS Service
- [ ] Debugging DNS Resolution
- [ ] Declare Network Policy
- [ ] Developing Cloud Controller Manager
- [ ] Encrypting Secret Data at Rest
- [ ] Guaranteed Scheduling For Critical Add-On Pods
- [ ] IP Masquerade Agent User Guide
- [ ] Kubernetes Cloud Controller Manager
- [ ] Limit Storage Consumption
- [ ] Namespaces Walkthrough
- [ ] Operating etcd clusters for Kubernetes
- [ ] Reconfigure a Node's Kubelet in a Live Cluster
- [ ] Reserve Compute Resources for System Daemons
- [ ] Safely Drain a Node while Respecting Application SLOs
- [ ] Securing a Cluster
- [ ] Set Kubelet parameters via a config file
- [ ] Set up High-Availability Kubernetes Masters
- [ ] Share a Cluster with Namespaces
- [ ] Static Pods
- [ ] Using CoreDNS for Service Discovery
- [ ] Using a KMS provider for data encryption
- [ ] Using sysctls in a Kubernetes Cluster
## Inject Data Into Applications
- [ ] Define a Command and Arguments for a Container
- [ ] Define Environment Variables for a Container
- [ ] Expose Pod Information to Containers Through Environment Variables
- [ ] Expose Pod Information to Containers Through Files
- [ ] Distribute Credentials Securely Using Secrets
- [ ] Inject Information into Pods Using a PodPreset
## Run Applications
- [ ] Run a Stateless Application Using a Deployment
- [ ] Run a Single-Instance Stateful Application
- [ ] Run a Replicated Stateful Application
- [ ] Update API Objects in Place Using kubectl patch
- [ ] Scale a StatefulSet
- [ ] Delete a StatefulSet
- [ ] Force Delete StatefulSet Pods
- [ ] Perform Rolling Update Using a Replication Controller
- [x] Horizontal Pod Autoscaler
- [ ] Horizontal Pod Autoscaler Walkthrough
- [ ] Specifying a Disruption Budget for your Application
## Run Jobs
- [ ] Running Automated Tasks with a CronJob
- [ ] Parallel Processing using Expansions
- [ ] Coarse Parallel Processing Using a Work Queue
- [ ] Fine Parallel Processing Using a Work Queue
## Access Applications in a Cluster
- [ ] Web UI (Dashboard)
- [ ] Accessing Clusters
- [ ] Configure Access to Multiple Clusters
- [ ] Use Port Forwarding to Access Applications in a Cluster
- [ ] Use a Service to Access an Application in a Cluster
- [ ] Connect a Front End to a Back End Using a Service
- [ ] Create an External Load Balancer
- [ ] Configure Your Cloud Provider's Firewalls
- [ ] List All Container Images Running in a Cluster
- [ ] Set up Ingress on Minikube with the NGINX Ingress Controller
- [ ] Communicate Between Containers in the Same Pod Using a Shared Volume
- [ ] Configure DNS for a Cluster
## Monitoring, Logging and Debugging
- [ ] Application Introspection and Debugging
- [ ] Auditing
- [ ] Debug Init Containers
- [ ] Debug Pods and ReplicationControllers
- [ ] Debug Services
- [ ] Debug a StatefulSet
- [ ] Debugging Kubernetes nodes with crictl
- [ ] Determine the Reason for Pod Failure
- [ ] Developing and debugging services locally
- [ ] Events in Stackdriver
- [ ] Get a Shell to a Running Container
- [ ] Logging Using Elasticsearch and Kibana
- [ ] Logging Using Stackdriver
- [ ] Monitor Node Health
- [ ] Resource metrics pipeline
- [ ] Tools for Monitoring Resources
- [ ] Troubleshoot Applications
- [ ] Troubleshoot Clusters
- [ ] Troubleshooting
## Extend Kubernetes
- [ ] Extend the Kubernetes API with CustomResourceDefinitions
- [ ] Versions of CustomResourceDefinitions
- [ ] Configure the Aggregation Layer
- [ ] Setup an Extension API Server
- [ ] Use an HTTP Proxy to Access the Kubernetes API
## TLS
- [ ] Certificate Rotation
- [ ] Manage TLS Certificates in a Cluster
## Federation
- [ ] Set up Cluster Federation with Kubefed
- [ ] Set up CoreDNS as DNS provider for Cluster Federation
Set up placement policies in Federation
Cross-cluster Service Discovery using Federated Services
## Manage Cluster Daemons
- [ ] Perform a Rollback on a DaemonSet
- [ ] Perform a Rolling Update on a Daemonset
## Install Service Catalog
- [ ] Install Service Catalog using Helm
- [ ] Install Service Catalog using SC

# Tutorials
- [X] Hello Minikube
## Learn Kubernetes Basics
- [X] Learn Kubernetes Basics
- [X] Using Minikube to Create a Cluster
- [ ] Interactive Tutorial - Creating a Cluster
- [X] Using kubectl to Create a Deployment
- [ ] Interactive Tutorial - Deploying an App
- [X] Viewing Pods and Nodes
- [ ] Interactive Tutorial - Exploring Your App
- [X] Using a Service to Expose Your App
- [ ] Interactive Tutorial - Exposing Your App
- [X] Running Multiple Instances of Your App
- [ ] Interactive Tutorial - Scaling Your App
- [X] Performing a Rolling Update
- [ ] Interactive Tutorial - Updating Your App
## Online Training Courses
- [ ] Overview of Kubernetes Online Training
## Configuration
- [ ] Configuring Redis using a ConfigMap
## Stateless Applications
- [ ] Exposing an External IP Address to Access an Application in a Cluster
- [ ] Example: Deploying PHP Guestbook application with Redis
- [ ] Example: Add logging and metrics to the PHP / Redis Guestbook example
## Stateful Applications
- [ ] StatefulSet Basics
- [ ] Example: Deploying WordPress and MySQL with Persistent Volumes
- [ ] Example: Deploying Cassandra with Stateful Sets
- [ ] Running ZooKeeper, A Distributed System Coordinator
## Clusters
- [ ] AppArmor
## Services
- [ ] Using Source IP

# Reference
- [X] Standardize Glossary
- [X] Tools
## Kubernetes Issues and Security
- [ ] Kubernetes Issue Tracker
- [ ] Kubernetes Security and Disclosure Information
## Using the Kubernetes API
- [ ] Kubernetes API Overview
- [ ] Kubernetes API Concepts
- [ ] Client Libraries
- [ ] Kubernetes Deprecation Policy
## Accessing the API
- [ ] Controlling Access to the Kubernetes API
- [ ] Authenticating
- [ ] Authenticating with Bootstrap Tokens
- [ ] Using Admission Controllers
- [ ] Dynamic Admission Control
- [ ] Managing Service Accounts
- [ ] Authorization Overview
- [ ] Using RBAC Authorization
- [ ] Using ABAC Authorization
- [ ] Using Node Authorization
- [ ] Webhook Mode
## API Reference
- [ ] Well-Known Labels, Annotations and Taints
## Federation API
- [ ] extensions/v1beta1 Model Definitions
- [ ] extensions/v1beta1 Operations
- [ ] federation/v1beta1 Model Definitions
- [ ] federation/v1beta1 Operations
- [ ] v1 Model Definitions
- [ ] v1 Operations
## Setup tools reference
- [ ] Overview of kubeadm
- [ ] kubeadm init
- [ ] kubeadm join
- [ ] kubeadm upgrade
- [ ] kubeadm config
- [ ] kubeadm reset
- [ ] kubeadm token
- [ ] kubeadm version
- [ ] kubeadm alpha
- [ ] kubeadm init phase
- [ ] kubeadm join phase
- [ ] Implementation details
## Command line tools reference
- [ ] Feature Gates
- [ ] federation-apiserver
- [ ] federation-controller-manager
- [ ] Kubelet authentication/authorization
- [ ] TLS bootstrapping
- [ ] cloud-controller-manager
- [ ] kube-apiserver
- [ ] kube-controller-manager
- [ ] kube-proxy
- [ ] kube-scheduler
- [ ] kubelet
## kubectl
- [ ] Overview of kubectl
- [ ] JSONPath Support
- [ ] kubectl
- [ ] kubectl Cheat Sheet
- [ ] kubectl Commands
- [ ] kubectl Usage Conventions
- [ ] kubectl for Docker Users
# Contribute
- [ ] Start contributing
- [ ] Intermediate contributing
- [ ] Advanced contributing
- [ ] Localizing Kubernetes Documentation
- [ ] Participating in SIG Docs
## Documentation style  overview
- [ ] Documentation style overview
- [ ] Style guide
- [ ] Writing a new topic
- [ ] Using Page Templates
- [ ] Content organization
- [ ] Custom Hugo Shortcodes
## Reference docs overview
- [ ] Reference docs overview
- [ ] Contributing to Upstream Kubernetes Code
- [ ] Generating Reference Documentation for API Kubernetes Federation API
- [ ] Generating Reference Documentation for kubectl Command
- [ ] Generating Reference Documentation for Kubernetes API
- [ ] Generating Reference Pages for Kubernetes Components and Tools

**Comment by mkorbi** [comment]
working on /concepts/services-networking/*

**Comment by sftim** [comment]
This is an umbrella issue
/remove-good-first-issue

It's OK to create good-first-issues that reference this issue as their overarching issue.

**Comment by flo-oss** [comment]
working on content/de/docs/concepts/workloads/pods/_index.md

**Comment by gdenn** [comment]
@mkorbi I'd like to work on "Kubernetes API Overview"

**Comment by iamNoah1** [comment]
@mkorbi @sftim correct me if I am wrong, but this does not look up to date for me. My suggestion is to either close this one or update it as it might be misleading. Especially for new contributors, it might increase the burden to get involved.

**Comment by rul3m4k3r** [comment]
started working on /tasks/tools/install-kubectl-macos.md and all things /tasks/tools/*. There are some depedencies from the original files (en).

**Comment by sftim** [comment]
Not currently triaged as accepted
/remove-help

**Comment by seokho-son** [comment]
Hi @bene2k1 @rlenferink @mkorbi
As a sig-docs localization subproject lead, I would like to check if this issue remains useful and if there's a general willingness to keep it open as is. (sig-docs is endeavoring to manage the quantity of open issues.)

**Comment by seokho-son** [comment]
I am trying to get feedback from #kubernetes-docs-de channel as well.
If there is no feedback, I am going to close this issue. :)

**Comment by iamNoah1** [comment]
@seokho-son back then when I found this issue, it was already outdated and no one ever replied to the question if it is outdated or not. Let's close it :)

**Comment by natalisucks** [comment]
Agree with @seokho-son and @iamNoah1! Closing this issue due to lack of feedback on its progress.

@mkorbi and @kubernetes/sig-docs-de-owners if you want to reopen and continue working on the specific tasks in this issue, please do so!

/close
