### ISSUE TITLE
Umbrella Issue: Remove Duplicate Content

### ISSUE THREAD

**Issue by aimeeu** [kubernetes/website#16091]
**This is a Feature Request**

The new [content guidelines](https://kubernetes.io/docs/contribute/style/content-guide/) address duplicate content. 

The Kubernetes documentation contains duplicate content in several places. This is an umbrella issue to track removal of that content. 

Duplicate content should be removed. Content should be added that points to instructions in external documentation (kubernetes, kubernetes-sigs, CNCF), or a prerequisite added that states what is required (for example, in the case of minikube state that successful installation and configuration of minikube is required).

People working on this issue should be heavy docs contributors or 

- [x] Minikube installation and configuration (Issue #15969) 
- [x] [Instructions for installing Docker, CRI-O, containerd, and other container runtimes on various operating systems](https://kubernetes.io/docs/setup/production-environment/container-runtimes/);  [GitHub](https://github.com/kubernetes/website/edit/master/content/en/docs/setup/production-environment/container-runtimes.md); each of those projects has its own docs
- [x] [ Instructions for installing Kubernetes on production environments using kops](https://kubernetes.io/docs/setup/production-environment/tools/kops/); kops has installation instructions in its [github]((https://github.com/kubernetes/kops) repo so link to those
- [x] [Installing Kubernetes with Kubespray](https://kubernetes.io/docs/setup/production-environment/tools/kubespray/); kubespray has its own [docs](https://kubespray.io) so link to those 
- [ ] [Monitor Node Health](https://kubernetes.io/docs/tasks/debug-application-cluster/monitor-node-health/#enable-disable-in-gce-cluster) - this whole page is about the [node-problem-detector](https://github.com/kubernetes/node-problem-detector). The README in the node-problem-detector repo contains explanation, installation, usage and tutorial sections. Some content is similar between the two pages but other sections contain conflicting content for the same concept, such as installation. Contact the code leads and find out which is correct and update docs content accordingly.

/cc @zacharysarah

**Comment by kbhawkey** [comment]
TODO: Check Falco [Auditing task page](https://kubernetes.io/docs/tasks/debug-application-cluster/falco/). Is this content covered by the Falco docs? Would adding a link to the Falco docs in the [k8s auditing page](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/) be sufficient? For background information, see issue #16140.

**Comment by aimeeu** [comment]
@kbhawkey - Yes! @sftim and I have been discussing this, and I opened  issue #16143 to get clarification on the Content Guide. Some bullet points are open to interpretation. I would like to get group consensus at the SIG Docs meeting on 3 Sept 2019 and then clarify the Content Guide accordingly.

> TODO: Check Falco [Auditing task page](https://kubernetes.io/docs/tasks/debug-application-cluster/falco/). Is this content covered by the Falco docs? Would adding a link to the Falco docs in the [k8s auditing page](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/) be sufficient? For background information, see issue #16140.

**Comment by sftim** [comment]
We should decide if we want to triage this as accepted.

**Comment by sftim** [comment]
> kops has installation instructions in its [github]((https://github.com/kubernetes/kops) repo so link to those

Not sure about this one! I wouldn't rely on GitHub for documentation if we can find a better way.

**Comment by tengqm** [comment]
> > kops has installation instructions in its [github]((https://github.com/kubernetes/kops) repo so link to those
> 
> Not sure about this one! I wouldn't rely on GitHub for documentation if we can find a better way.

How about this one then https://kops.sigs.k8s.io/ ?

**Comment by trottiemcqueen** [comment]
Hello, I would like to contribute and work on this please
