### ISSUE TITLE
Tracking Italian automated translation review

### ISSUE THREAD

**Issue by Fale** [kubernetes/website#18383]
The italian translation has been automatically generated in the past.
For this reason, in June 2019 it has been disabled.
To re-enable it, we should firstly review all currently translated pages, and improve them so that it's easily readable by humans.
The goal of this issue, is to track such progress.

## Pages
* [x] blog/_index.md (#18384)
* [x] case-studies/comcast/index.html (#19785)
* [x] case-studies/_index.md (#19785)
* [x] _common-resources/index.md (#19786)
* [x] community/code-of-conduct.md (#20096)
* [x] community/_index.html (#20096)
* [x] community/static/cncf-code-of-conduct.md (#20101)
* [x] community/static/README.md
* [x] docs/concepts/architecture/cloud-controller.md (#20262)
* [x] docs/concepts/architecture/_index.md (#20243)
* [ ] docs/concepts/architecture/master-node-communication.md
* [ ] docs/concepts/architecture/nodes.md
* [ ] docs/concepts/cluster-administration/addons.md
* [ ] docs/concepts/cluster-administration/certificates.md
* [ ] docs/concepts/cluster-administration/cloud-providers.md
* [ ] docs/concepts/cluster-administration/cluster-administration-overview.md
* [ ] docs/concepts/cluster-administration/controller-metrics.md
* [ ] docs/concepts/cluster-administration/federation.md
* [x] docs/concepts/cluster-administration/_index.md (#20338)
* [ ] docs/concepts/cluster-administration/kubelet-garbage-collection.md
* [ ] docs/concepts/cluster-administration/logging.md
* [ ] docs/concepts/cluster-administration/manage-deployment.md
* [ ] docs/concepts/cluster-administration/networking.md
* [x] docs/concepts/cluster-administration/proxies.md (#20337)
* [x] docs/concepts/example-concept-template.md (#20267)
* [x] docs/concepts/_index.md (#18368)
* [x] docs/concepts/overview/what-is-kubernetes.md (#19783)
* [x] examples/admin/logging/fluentd-sidecar-config.yaml
* [x] examples/admin/logging/two-files-counter-pod-agent-sidecar.yaml
* [x] examples/admin/logging/two-files-counter-pod-streaming-sidecar.yaml
* [x] examples/admin/logging/two-files-counter-pod.yaml
* [x] examples/application/nginx-app.yaml
* [x] examples/debug/counter-pod.yaml
* [x] includes/federation-deprecation-warning-note.md (#20105)
* [x] includes/index.md (#20105)
* [x] _index.html (#19787)
* [x] partners/_index.html (#20104)

**Comment by sftim** [comment]
@Fale I think you can exclude `OWNERS`

Also, all the example manifests look up-to-date. I checked using a tool:
```bash
find content/it/examples -type f | while read manifest; do git diff --no-index "${manifest}" "$( printf "%s" "${manifest}" | sed -e 's,/it/,/en/,' )"; done
```
and also visually scanned for text that would need localizing.

**Comment by sftim** [comment]
`includes/index.md` is fine too.

**Comment by fabriziopandini** [comment]
Excluding OWNERS is ok, but considering that we are at the beginning of this effort and that the well-known issues about the existing translations, I think we should double-check everything no matter if they look up to date.

**Comment by sftim** [comment]
I confirm you that `content/it/examples/*` are checked.

**Comment by fabriziopandini** [comment]
@Fale I'm closing this since we are now on master and we would like to track progress about reviewing/translating pages under concepts using separated issues
/close
