### ISSUE TITLE
Need to clear federation v1 content

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/website#19206]
**This is a Bug Report**

**Problem:**

We've been killed all tasks federation related content in PR #17949 , but there are still many contents write with federation, see the list below:

- [ ] [/content/en/docs/concepts/cluster-administration/federation.md](https://github.com/kubernetes/website/tree/master/content/en/docs/concepts/cluster-administration/federation.md) , reason: referenced some tasks federation links, follow-up PR: #19525 .
- [x] [/content/en/docs/concepts/services-networking/connect-applications-service.md](https://github.com/kubernetes/website/tree/master/content/en/docs/concepts/services-networking/connect-applications-service.md) , reason: what's next section linked federation service discovery page which will be redirected.  follow-up PR: #19572 .
- [ ] [/content/en/docs/reference/tools.md](https://github.com/kubernetes/website/tree/master/content/en/docs/reference/tools.md) , reason: kubefed section follow-up PR: #19583 .
- [ ] [/content/en/docs/tasks/administer-cluster/dns-debugging-resolution.md](https://github.com/kubernetes/website/tree/master/content/en/docs/tasks/administer-cluster/dns-debugging-resolution.md) , reason: Kubernetes Federation section may needs update follow-up PR: #19581 .
- [ ] [/content/en/examples/examples_test.go](https://github.com/kubernetes/website/tree/master/content/en/examples/examples_test.go) and [/content/en/examples/federation/*.yaml](https://github.com/kubernetes/website/tree/master/content/en/examples/federation) , reason: it did some federation tests, do we need to remove these cases? follow-up PR: #19581 .
- [x] [/content/en/includes/federated-task-tutorial-prereqs.md](https://github.com/kubernetes/website/tree/master/content/en/includes/federated-task-tutorial-prereqs.md) , reason: out-dated include page I think.  follow-up PR: #19572 .
- [x] [/data/tasks.yml](https://github.com/kubernetes/website/tree/master/data/tasks.yml) , reason: it referenced some tasks federatoin pages. follow-up PR: #19572 .
- [x] [/data/tools.yml](https://github.com/kubernetes/website/tree/master/data/tools.yml) , reason: it referenced kubefed (federation v1 cli).  follow-up PR: #19572 .
- [ ] [/static/_redirects](https://github.com/kubernetes/website/tree/master/static/_redirects) , reason: some redirects may need update.  follow-up PR: #19572 , #19583 .

**Proposed Solution:**
Confirm the listed items, and correct or delete it.

**Page to Update:**
See the list links.

/language en

**Comment by sftim** [comment]
See #19525

**Comment by kbhawkey** [comment]
@Colstuwjx , Thanks for creating this issue.

**Comment by tengqm** [comment]
/close
done.
