### ISSUE TITLE
Tracking Indonesian Translation Progress (M3)

### ISSUE THREAD

**Issue by girikuncoro** [kubernetes/website#20111]
This is tracking issue of our progress from Q2 2020 onwards. In the beginning of this milestone, as per [our metrics](https://app.circleci.com/pipelines/github/jk8s/sig-docs-id/31/workflows/48a5bce1-b278-4eab-b057-1cd1793c4daf/jobs/44), we have translated 112 pages from 46 contributors, with around 7,000 views per month.

## Maintainers
* @danninov 
* @girikuncoro
* @irvifa 
* @phanama
* @qbl
* @wahyuoi 

## For New Contributors
To translate a page:
1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. Take only one page at a time.
3. Fork this repo, make your translations, and submit a pull request with `language/id` label!
4. After submit, reviewers will give comments in couple of days, please address them. It's recommended to also [squash](https://github.com/wprig/wprig/wiki/How-to-squash-commits) your commits.

### TL;DR Top 5 Mistakes for New Contributors
1. We use "kamu" instead of more formal "Anda" to be more friendly with our readers.
2. Use CamelCase style to write Kubernetes API objects.
    - **Correct:** PersistentVolume. **Incorrect:** persistent volume, `PersistentVolume`, persistentVolume
    - **Correct:** Pod. **Incorrect:** pod, `pod`, "pod"
3. Italicize imported english words if you can't find the indonesian words.
    - **Correct:** _controller_. **Incorrect:** controller, `controller`
    - **Correct:** _default_. **Incorrect:** default, `default`
4. After raising PR, the reviewers will give feedback and comment, please address the comments or give suggestion if you think the comments don't make sense. Many people who are new to contribution thought PR is completion.
5. Proof read your translation before raising PR. Check for typos. Choice of wordings are debatable, but we don't tolerate typos.

For more detailed instruction, consult with this [JK8s guide](https://github.com/jk8s/sig-docs-id-localization-how-tos#getting-started). Before contributing, read the [glossary](https://github.com/jk8s/sig-docs-id-localization-how-tos#glossary) and the [RSNI Glosarium from Ivan Lanin](https://github.com/jk8s/sig-docs-id-localization-how-tos/blob/master/resources/RSNI-glossarium.pdf) to understand how to translate various technical and Kubernetes-specific terms. (If you're still not sure about something, please don't hesitate to ask in [Slack channel](https://kubernetes.slack.com/messages/CJ1LUCUHM), we won't bite 😄)

Also, there is no special style guide for writing Bahasa Indonesia. In general we can follow the [English style guide](https://kubernetes.io/docs/contribute/style/style-guide/) with some addition to italicizing imported words.

Please commit with your translations! When you get comments from reviewers, please address them. We expect claimed pages to be translated within 2 weeks. If you find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For maintainers
When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

- [x] Init Kubernetes ID (@girikuncoro) #13822 

When PRs are merged, make sure to mark that page as completed!

# Work Status
(🏃 Work in Progress; 👀 In Review)

This is our third milestone (M3) that we aim to complete during the Kubernetes v1.19 release cycle. We will mostly continue on translating remaining `concept` pages, and start with `task` pages sorted based on top visited pages.

## Translation of Concepts (15 pages)
- [x] /docs/concepts/architecture/controller/ (@ariscahyadi ) #19799
- [x] /docs/concepts/containers/overview/ (@ariscahyadi) #19799
- [x] /docs/concepts/containers/container-environment/  (@ariscahyadi) #19799
- [x] /docs/concepts/workloads/pods/pod-topology-spread-constraints/ (@wahyuoi) #21565
- [x] /docs/concepts/workloads/pods/ephemeral-containers/ (@ariscahyadi) #19815
- [x] /docs/concepts/services-networking/endpoint-slices/ (@evanap) ##20166
- [x] /docs/concepts/services-networking/service-topology/ (@ariscahyadi) #20229
- [x] /docs/concepts/services-networking/dual-stack/ (@ariscahyadi) #20106
- [x] /docs/concepts/configuration/resource-bin-packing/ (@ariscahyadi) ##20240
- [x] /docs/concepts/policy/limit-range/ (@ariscahyadi ) #21635
- [x] /docs/concepts/scheduling/kube-scheduler/ (@ariscahyadi) #19909
- [x] /docs/concepts/scheduling/scheduling-framework/ (@ariscahyadi) #20195
- [x] /docs/concepts/scheduling/scheduler-perf-tuning/ (@girikuncoro ) #20260
- [x] /docs/concepts/cluster-administration/flow-control/ (@ariscahyadi) #20588
- [x] /docs/concepts/extend-kubernetes/operator/ (@ariscahyadi) #19875

## Translation of Task and Others (25 pages)
- [x] /docs/reference/kubectl/cheatsheet/ (@girikuncoro) #20832
- [x] /docs/tasks/tools/install-kubectl/ (@handywijaya) #20278
- [x] /docs/tasks/tools/install-minikube/ (@dedyks) #20356
- [x] /docs/tasks/access-application-cluster/web-ui-dashboard/ (@mufti1) #20259
- [x] /docs/tasks/configure-pod-container/configure-pod-configmap/ (@evanap) #20438
- [x]  /docs/setup/production-environment/tools/kubeadm/install-kubeadm/ (@evanap) #21878
- [x] /docs/reference/access-authn-authz/rbac/ (part 1) (@imrenagi) #21885
- [x] /docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/ (@evanap) #20945
- [x] /docs/tasks/access-application-cluster/configure-access-multiple-clusters/ (@adityaalifn ) #20739
- [x] /docs/tasks/debug-application-cluster/get-shell-running-container/ (@ariscahyadi ) #20972
- [x] /docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ (@girikuncoro) #21535
- [x] /docs/tasks/ (@ariscahyadi ) #20261
- [x] /docs/tasks/configure-pod-container/pull-image-private-registry/ (@ariscahyadi ) #21712
- [x] /docs/tasks/run-application/horizontal-pod-autoscale/ (@ecojuntak) #20400
- [x] /docs/tasks/inject-data-application/define-environment-variable-container/ (@adityaalifn) #20273
- [x] /docs/tasks/configure-pod-container/configure-persistent-volume-storage/  (@mufti1) #21389
- [x] /docs/tasks/inject-data-application/define-command-argument-container/  (@adityaalifn) #21267
- [x] /docs/tasks/configure-pod-container/configure-service-account/ (@joshuabezaleel ) #21960
- [x] /docs/tasks/access-application-cluster/port-forward-access-application-cluster/ (@adityaalifn) ##20264
- [x] /docs/tasks/job/automated-tasks-with-cron-jobs/ (@mufti1) #20472
- [x] /docs/tasks/access-application-cluster/access-cluster/ (@deryrahman ) #20346
- [x]  /docs/tasks/configure-pod-container/security-context/ (@ariscahyadi) #20913
- [x] /docs/tasks/access-application-cluster/create-external-load-balancer/ (@deryrahman) #21406

## Extras
- [x] /docs/concepts/cluster-administration/monitoring (@ariscahyadi ) #20266
- [x] /docs/setup/best-practices/multiple-zones (@ariscahyadi) #21107

*Note: This contribution template is inspired by Indonesian folks translating [reactjs doc](https://github.com/reactjs/id.reactjs.org/issues/1)*

Related Docs:
1. [RSNI glossary](https://github.com/jk8s/sig-docs-id-localization-how-tos/blob/master/resources/RSNI-glossarium.pdf)
2. [Branching Strategy](https://kubernetes.io/docs/contribute/localization/#branching-strategy)

/language id
/cc @kubernetes/sig-docs-id-reviews

**Comment by ariscahyadi** [comment]
`/docs/concepts/containers/container-environment/` has been pushed together in #19799 
Basically, the content in English documentation is the same but the name is changed from `/docs/concepts/containers/container-environment-variables` into `/docs/concepts/containers/container-environment/`

Thanks,
Aris.

**Comment by girikuncoro** [comment]
I'm taking ` /docs/concepts/scheduling/scheduler-perf-tuning/`

**Comment by evanap** [comment]
Hi! I'd like to take `/docs/concepts/services-networking/endpoint-slices/`

**Comment by handywijaya** [comment]
Hi! I'd to take ` /docs/tasks/tools/install-kubectl/`

**Comment by danninov** [comment]
I'm taking /docs/concepts/policy/limit-range/

**Comment by ariscahyadi** [comment]
I'm taking `/docs/concepts/scheduling/scheduling-framework/`

**Comment by wahyuoi** [comment]
I'm taking `/docs/concepts/containers/overview/`

**Comment by ariscahyadi** [comment]
> I'm taking `/docs/concepts/containers/overview/`

Kayanya sudah di merged lewat PR sebelumnya https://kubernetes.io/id/docs/concepts/containers/overview/ :)

**Comment by wahyuoi** [comment]
Nice, thank you @ariscahyadi for pointing this out :bowing_man: 

I'll take `/docs/concepts/workloads/pods/pod-topology-spread-constraints/`

**Comment by ariscahyadi** [comment]
I will take this `/docs/concepts/services-networking/service-topology/`

**Comment by dedyyyy** [comment]
I would like to take
docs/tasks/tools/install-minikube

**Comment by dedyyyy** [comment]
i would like to translate this

` /docs/tasks/tools/install-minikube/
`

**Comment by mufti1** [comment]
I will take this ` /docs/tasks/access-application-cluster/web-ui-dashboard/`

**Comment by adityaalifn** [comment]
I woul like to take this ` /docs/tasks/access-application-cluster/port-forward-access-application-cluster/`

**Comment by ariscahyadi** [comment]
Let's continue... I will take this `/docs/concepts/configuration/resource-bin-packing/`

**Comment by deryrahman** [comment]
Hi, I would like to take this `/docs/tasks/access-application-cluster/access-cluster/`

**Comment by ariscahyadi** [comment]
Next... I take this `/docs/tasks/`

**Comment by girikuncoro** [comment]
I'm taking `/docs/reference/kubectl/cheatsheet/` next

**Comment by adityaalifn** [comment]
Next, I'm taking this `/docs/tasks/inject-data-application/define-environment-variable-container/`

**Comment by mufti1** [comment]
Next, I will take this `/docs/tasks/job/automated-tasks-with-cron-jobs/`

**Comment by deryrahman** [comment]
Next, let me take this `/docs/tasks/access-application-cluster/create-external-load-balancer/`

**Comment by evanap** [comment]
I'd like to translate the page `/docs/tasks/configure-pod-container/configure-pod-configmap/`

**Comment by VaraKatare** [comment]
I'd like to translate the page `/docs/setup/production-environment/tools/kubeadm/install-kubeadm/`

**Comment by ecojuntak** [comment]
I'm taking `/docs/tasks/run-application/horizontal-pod-autoscale/`

**Comment by ariscahyadi** [comment]
I want to take a challenge to complete the last page in the concept `/docs/concepts/cluster-administration/flow-control/`
This page is long so I know why it becomes the last page remaining :)

**Comment by adityaalifn** [comment]
I'd like to take `/docs/tasks/access-application-cluster/configure-access-multiple-clusters/`

**Comment by novalagung** [comment]
let me take `/docs/tasks/configure-pod-container/pull-image-private-registry/` :)

**Comment by imrenagi** [comment]
I will take this 
`/docs/reference/access-authn-authz/rbac/`

**Comment by evanap** [comment]
Hi, I'll be translating this page `/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/`

**Comment by girikuncoro** [comment]
I'm taking `/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/` next

**Comment by ariscahyadi** [comment]
I will continue with this `/docs/tasks/configure-pod-container/security-context/`

**Comment by mufti1** [comment]
I will take this ` /docs/tasks/configure-pod-container/configure-persistent-volume-storage/`

**Comment by ariscahyadi** [comment]
I will continue with this `/docs/tasks/debug-application-cluster/get-shell-running-container/`

**Comment by adityaalifn** [comment]
I'd like to take this `/docs/tasks/inject-data-application/define-command-argument-container/`

**Comment by ariscahyadi** [comment]
Because nothing left... I propose to translate this `docs/setup/best-practices/multiple-zones/`

**Comment by girikuncoro** [comment]
Folks, because we only have 4 weeks left to close this milestone, can you let us know if you are still working on your claimed pages? Please raise the pull request by Sunday, 7 June 2020. If we don't hear from you by then, we will clear the pages to let other contributors work on them.

Here's the list of claimed pages

/docs/concepts/workloads/pods/pod-topology-spread-constraints/ (@wahyuoi)
/docs/concepts/policy/limit-range/ (@danninov)
/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ (@VaraKatare)
/docs/reference/access-authn-authz/rbac/ (@imrenagi)
/docs/tasks/configure-pod-container/pull-image-private-registry/ (@novalagung)
/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ (@girikuncoro)
/docs/tasks/run-application/horizontal-pod-autoscale/ (@ecojuntak)

Thanks for your contribution so far!

**Comment by imrenagi** [comment]
yep. im still working on it @girikuncoro  :p

**Comment by joshuabezaleel** [comment]
I'll take ` /docs/tasks/configure-pod-container/configure-service-account/`

**Comment by girikuncoro** [comment]
I've cleared these up to allow other contributors working on these

/docs/concepts/policy/limit-range/ (@danninov)
/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ (@VaraKatare)
/docs/tasks/configure-pod-container/pull-image-private-registry/ (@novalagung)

**Comment by ariscahyadi** [comment]
> I've cleared these up to allow other contributors working on these
> 
> /docs/concepts/policy/limit-range/ (@danninov)
> /docs/setup/production-environment/tools/kubeadm/install-kubeadm/ (@VaraKatare)
> /docs/tasks/configure-pod-container/pull-image-private-registry/ (@novalagung)

I am working on this `/docs/concepts/policy/limit-range/`

**Comment by ariscahyadi** [comment]
> I've cleared these up to allow other contributors working on these
> 
> /docs/concepts/policy/limit-range/ (@danninov)
> /docs/setup/production-environment/tools/kubeadm/install-kubeadm/ (@VaraKatare)
> /docs/tasks/configure-pod-container/pull-image-private-registry/ (@novalagung)

I am working on this `/docs/tasks/configure-pod-container/pull-image-private-registry/`

**Comment by evanap** [comment]
Does this page `/docs/setup/production-environment/tools/kubeadm/install-kubeadm/` still need translation? I'll work on it if needed.

**Comment by girikuncoro** [comment]
> Does this page `/docs/setup/production-environment/tools/kubeadm/install-kubeadm/` still need translation? I'll work on it if needed.

@evanap I think it's free, feel free to take it, thanks for stepping up! next week is our last week of current milestone

**Comment by evanap** [comment]
@girikuncoro Alright! Working on it as fast as possible to catch the train 🚀

**Comment by irvifa** [comment]
Do we intended to open a new milestone @girikuncoro ?

**Comment by girikuncoro** [comment]
> Do we intended to open a new milestone @girikuncoro ?

@irvifa yes, this should be the last week of this current milestone, I hope we can close all pages, you want to propose the list of pages for new milestone?

**Comment by ariscahyadi** [comment]
> > Do we intended to open a new milestone @girikuncoro?
> 
> @irvifa yes, this should be the last week of this current milestone, I hope we can close all pages, you want to propose the list of pages for new milestone?

@irvifa and @girikuncoro let me know if you need help to review... to ensure that we can close all the open pages on time :)

**Comment by girikuncoro** [comment]
Thank you so much for everyone's contribution, we have successfully closed this Milestone 3! I hope you all learned new Kubernetes knowledge from this contribution. Please DM or mention me on twitter [@girikuncoro](https://twitter.com/girikuncoro) if you want to receive special gifts (a cute kubernetes mask) from your contributions.

Our next milestone is going to be maintained in https://github.com/kubernetes/website/issues/22296
Looking forward to your next contributions! 🎉
