### ISSUE TITLE
Umbrella issue: Remove unused files and scripts

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#22024]
Now that the Docsy theme is merged and running, we have a number of unused or duplicate JavaScript, CSS, image and font files in the kubernetes/website repository. We should remove these, as it will make the repository easier to maintain going forward.

Some of these removals are more straightforward than others, but as a general rule, anyone executing this work should do the following:

1) Do a keyword search of the directory to ensure that the file, directory or image isn't referenced by any content pages or layout pages.
2) Delete the file
3) Try to build the site and inspect pages thoroughly

### Javascript 

I would only take these on if you have experience with Javascript or are very familiar with the website. Almost all of these will include removing an href from one or more layout files, and some of them will require removing functions in a semi-mysterious `/scripts/js/script.js` file.

- [x] https://github.com/kubernetes/website/issues/22040 **Good first issue!** Remove `/scripts/js/anchor-4.1.1-min.js`
- [x] https://github.com/kubernetes/website/issues/22044 **Good first issue!** Remove `/scripts/js/custom-jekyll/tags.js` and containing directory
- [x] https://github.com/kubernetes/website/issues/22041 Investigate removing `/scripts/js/bootstrap-4.3.1.min.js` (note: seems to be called by `/reference/generated/kubernetes-api/v1.18/index.html` only?)
- [x] [#tbd] Investigate removing `/functions-src/deploy-succeded.js`
- [x] https://github.com/kubernetes/website/issues/22049 Remove `/scripts/js/sweetalert.js`, unused `copyCode()` function
- [x] https://github.com/kubernetes/website/issues/22059 Investigate removing JQuery UI (lots of moving parts!)
- [x] https://github.com/kubernetes/website/issues/22045 Investigate removing /static/js/search.js (complicated, tread carefully)
~- [ ] [#tbd] Investigate whether any functions in `/scripts/js/script.js` can be removed (complicated, tread carefully)~ Opting not to do this fow now. 

### Images

Many of these are good first issues! 👯 

- [x] https://github.com/kubernetes/website/issues/22086 Clean up case study images 
- [x] https://github.com/kubernetes/website/issues/22090 Investigate: can we remove `/static/images/square-logos`? (I don't think they're used on the training/partners pages, but double-check)
- [x] https://github.com/kubernetes/website/issues/22091 **Good First issue!!** Remove `/static/images/metadocs/`
- [x] https://github.com/kubernetes/website/issues/22092 **Good First issue!!** Remove `/static/images/logos`
- [x] https://github.com/kubernetes/website/issues/22093 **Good First Issue!!** Remove `/static/images/journeys`
- [x] https://github.com/kubernetes/website/issues/22094 **Good First Issue!!** Remove `/static/images/community_logos`

### Fonts

- [x] https://github.com/kubernetes/website/issues/22095 Investigate removing Roboto
- [x] https://github.com/kubernetes/website/issues/22096 Investigate removing MaterialIcons

### CSS

~- [ ] [#tbd] Double-check that all files contained in `/scripts/src/css` are actually used~ Opting to not do this... all of the files are used but there's an opportunity to optimize/move lots of this code directly into _styles.scss that should be evaluated in more depth.

**Comment by celestehorgan** [comment]
WOHOOO!
