### ISSUE TITLE
Tracking Indonesian translation for glossary

### ISSUE THREAD

**Issue by habibrosyad** [kubernetes/website#24382]
This is a tracking issue for Indonesian translation of https://k8s.io/docs/reference/glossary. Below is the list of what has been and need to be translated:

Overal Page:
- [x] Menu, heading and intro of glossary #24180

Terms (by glossary id):
- [ ] addons
- [ ] admission-controller
- [ ] aggregation-layer
- [x] annotation #24377 
- [x] api-group #24377
- [ ] app-container
- [ ] application-architect
- [ ] application-developer
- [x] applications #24378
- [ ] approver
- [ ] certificate
- [x] cgroup #24378
- [ ] cidr
- [ ] cla
- [ ] cloud-controller-manager
- [ ] cloud-provider
- [ ] cluster-architect
- [ ] cluster-infrastructure
- [ ] cluster-operations
- [x] cluster-operator #24379
- [x] cluster #24379
- [ ] cncf
- [ ] cni
- [ ] code-contributor
- [x] configmap #24391
- [x] container-env-variables #24391
- [ ] container-lifecycle-hooks
- [x] container-runtime #24391
- [x] container #24391
- [ ] containerd
- [x] contributor
- [x] control-plane #24391
- [x] controller #24392
- [ ] cri-o
- [x] cri #24392
- [ ] cronjob
- [ ] csi
- [x] customresourcedefinition #24392
- [x] daemonset #24392
- [x] data-plane #24392
- [x] deployment #24427
- [ ] developer
- [x] device-plugin #24427
- [x] disruption #24427
- [x] docker #24427
- [ ] downstream
- [ ] dynamic-volume-provisioning
- [ ] endpoint-slice
- [ ] endpoint
- [x] ephemeral-container #24427
- [x] etcd
- [x] extensions #24428
- [ ] flexvolume
- [ ] helm-chart
- [ ] horizontal-pod-autoscaler
- [ ] host-aliases
- [x] image #24428
- [x] ingress
- [x] init-container #24428
- [ ] istio
- [x] job #24428
- [ ] kops
- [x] kube-apiserver #24428
- [x] kube-controller-manager #26090
- [x] kube-proxy #26090
- [x] kube-scheduler #26090
- [ ] kubeadm
- [x] kubectl #26090
- [x] kubelet #26090
- [ ] kubernetes-api #24347 **[revise]**
- [ ] label #24347 **[revise]**
- [ ] limitrange #24347 **[revise]**
- [ ] logging #24347 **[revise]**
- [x] managed-service
- [ ] manifest #24347 **[revise]**
- [ ] master #24347 **[revise]**
- [ ] member
- [ ] minikube #24347 **[revise]**
- [ ] mirror-pod #24347 **[revise]**
- [x] name #24347 **[revise]**
- [x] namespace #24111 
- [ ] network-policy
- [ ] node #24347 **[revise]**
- [ ] operator-pattern
- [x] persistent-volume-claim #24094 #24347 **[revise]**
- [x] persistent-volume #24088 #24347 **[revise]**
- [x] platform-developer
- [ ] pod-disruption-budget
- [ ] pod-lifecycle #24347 **[revise]**
- [ ] pod-priority
- [ ] pod-security-policy #24347 **[revise]**
- [x] pod #24347 **[revise]**
- [ ] podpreset
- [ ] preemption
- [ ] proxy
- [ ] qos-class #24347 **[revise]**
- [x] quantity #26090
- [x] rbac #24211 #24347 **[revise]**
- [ ] replica-set #24347 **[revise]**
- [ ] replication-controller
- [ ] resource-quota #24347 **[revise]**
- [ ] reviewer
- [ ] rkt
- [ ] secret
- [ ] security-context
- [ ] selector #24347 **[revise]**
- [ ] service-account #24347 **[revise]**
- [x] service-broker
- [x] service-catalog
- [x] service #24347 **[revise]**
- [ ] shuffle-sharding #24347 **[revise]**
- [ ] sig
- [x] statefulset #24347 **[revise]**
- [ ] static-pod #24347 **[revise]**
- [ ] storage-class
- [ ] sysctl
- [ ] taint #24347 **[revise]**
- [ ] toleration #24347 **[revise]**
- [x] uid #24347 **[revise]**
- [ ] upstream
- [ ] volume-plugin
- [x] volume #24347 **[revise]**
- [ ] wg
- [ ] workload #24347 **[revise]**

Note:
**[review]** - PR exists, under review
**[revise]** - Exclusive label PR #24347 which is closed due to the huge size, and need to be split into smaller PRs
- [x] - Translation exists
- [ ] - No translation (or PR exists but not merged yet)

/assign 
/language id
/cc @kubernetes/sig-docs-id-reviews

**Comment by habibrosyad** [comment]
fyi @irvifa @ariscahyadi @girikuncoro

**Comment by girikuncoro** [comment]
This is great, thanks for this initiative @habibrosyad !

**Comment by irvifa** [comment]
@habibrosyad do we still track this issue here? Any expected timeline?

**Comment by habibrosyad** [comment]
@irvifa Yep, just for the glossary. I still could not find a time to continue working on this issue. So I'm just keeping it alive just in case. What do you think?

**Comment by habibrosyad** [comment]
Let me close this issue for the time being, reducing the open issue on the website, and reopen it later when we have the bandwidth to tackle it.

/close
