### ISSUE TITLE
Tracking Indonesian Translation Progress (M5)

### ISSUE THREAD

**Issue by girikuncoro** [kubernetes/website#25025]
This is tracking issue of our progress from Q4 2020 onwards. In the beginning of this milestone, as per our [metrics](https://app.circleci.com/pipelines/github/jk8s/sig-docs-id/33/workflows/e59d9d32-55b7-49f7-86ad-c818ea562c5f/jobs/61), we have translated 220 pages from 84 contributors (the script from main repo shows 260+ pages), with around 8,000 views per month. In this milestone, we take step back to revisit our central glossary, contributing strategy and guidance. We also focus on updating the obsolete pages. We are not officially listing down target pages to translate, but feel free if you have spare time to translate some.

## Maintainers
- @ariscahyadi
- @danninov
- @girikuncoro
- @irvifa
- @phanama
- @qbl
- @wahyuoi

## For New Contributors
To translate a page:
- Check that no one else has claimed your page in the checklist and comments below.
- Comment below with the name of the page you would like to translate. Take only one page at a time.
- Fork this repo, make your translations, and submit a pull request with language/id label!
- After submit, reviewers will give comments in couple of days, please address them. It's recommended to also squash your commits with good commit message.

P.S. We are revamping new guide that is more easily accessible in this milestone, stay tuned!

### Establish Central Glossary (PIC: @ariscahyadi @wahyuoi )
As contributor, I should be able to open and refer the central glossary when doing translating work, and update them when needed. Every change to central glossary will need to go through Pull Requests on k/website.

Task list:
- [ ] There should be page accessible on kubernetes.io that shows glossary and contributing guidance. Ref: [Japanese link](https://kubernetes.io/ja/docs/contribute/localization/#%E9%A0%BB%E5%87%BA%E5%8D%98%E8%AA%9E) [Korean link](https://kubernetes.io/ko/docs/contribute/localization_ko)
- [ ] The page should contain common words according to our learning for the past year

### Updating Current Indonesia pages with the latest English page (PIC: @danninov @girikuncoro )
Task list:
- [x] Collect the pages that are no longer exist and renamed pages
- [x] Collect obsolete pages under Concept and Task section

General guidelines:
- **removed** means page has been deleted or moved somewhere else, look carefully for pages with different name but same/similar content
- **modified** means page have been updated, in order to help see what's the diff, run:
    ```sh
    ./scripts/upstream_changes.py <page-name>`
    ```
    Example:
    ```sh
    # colordiff will help in seeing the changes clearer
    ./scripts/upstream_changes.py content/id/_index.html | colordiff
    ```

List of outdated pages (40 out of 162 pages for this milestone):
- [ ] **removed**	content/en//docs/search.md
- [ ] **removed**	content/en//docs/tasks/tools/install-minikube.md
- [ ] **removed**	content/en//docs/tasks/tools/kubeadm/_index.md
- [ ] **removed**	content/en//docs/tasks/example-task-template.md
- [ ] **removed**	content/en//docs/tasks/administer-cluster/cluster-management.md
- [ ] **removed**	content/en//docs/setup/learning-environment/minikube.md
- [ ] **removed**	content/en//docs/concepts/configuration/assign-pod-node.md
- [ ] **removed**	content/en//docs/concepts/configuration/pod-overhead.md
- [ ] **removed**	content/en//docs/concepts/configuration/manage-compute-resources-container.md
- [ ] **removed**	content/en//docs/concepts/configuration/resource-bin-packing.md
- [ ] **removed**	content/en//docs/concepts/configuration/taint-and-toleration.md
- [ ] **removed**	content/en//docs/concepts/scheduling/scheduling-framework.md
- [ ] **removed**	content/en//docs/concepts/scheduling/scheduler-perf-tuning.md
- [ ] **removed**	content/en//docs/concepts/scheduling/kube-scheduler.md
- [ ] **removed**	content/en//docs/concepts/scheduling/_index.md
- [ ] **removed**	content/en//docs/concepts/workloads/pods/pod-overview.md
- [ ] **removed**	content/en//docs/concepts/workloads/pods/pod.md
- [ ] **removed**	content/en//docs/concepts/workloads/controllers/jobs-run-to-completion.md
- [ ] **removed**	content/en//docs/concepts/extend-kubernetes/poseidon-firmament-alternate-scheduler.md
- [ ] **removed**	content/en//docs/concepts/containers/overview.md
- [ ] **removed**	content/en//docs/concepts/cluster-administration/cluster-administration-overview.md
- [ ] **removed**	content/en//docs/concepts/cluster-administration/federation.md
- [ ] **removed**	content/en//docs/concepts/cluster-administration/cloud-providers.md
- [ ] **removed**	content/en//docs/concepts/cluster-administration/controller-metrics.md
- [ ] **removed**	content/en//docs/concepts/cluster-administration/monitoring.md
- [ ] **removed**	content/en//docs/templates/index.md
- [ ] **removed**	content/en//docs/reference/glossary/kuantitas.md
- [ ] **removed**	content/en//docs/sitemap.md
- [ ] **modified**  content/en/includes/task-tutorial-prereqs.md
- [ ] **modified**  content/en/docs/home/supported-doc-versions.md
- [ ] **modified**  content/en/docs/home/_index.md
- [ ] **modified**  content/en/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
- [ ] **modified**  content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
- [ ] **modified**  content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
- [ ] **modified**  content/en/docs/tasks/run-application/run-stateless-application-deployment.md
- [ ] **modified**  content/en/docs/tasks/run-application/force-delete-stateful-set-pod.md
- [ ] **modified**  content/en/docs/tasks/tools/install-kubectl.md
- [ ] **modified**  content/en/docs/tasks/tools/_index.md
- [ ] **modified**  content/en/docs/tasks/configure-pod-container/configure-service-account.md
- [ ] **modified**  content/en/docs/tasks/configure-pod-container/configure-persistent-volume-storage.md

## Extras
_Take note translated pages in case any contributions_
- [ ] content/id/docs/tasks/configure-pod-container/quality-service-pod.md (@frbimo #25082)

Related Docs:
* [M5 Discussion](https://docs.google.com/document/d/1f-Fw_-oNiObsfgDx6t3RqXH7IAb1xRbXsyfMb4g5CrU)
* [RSNI glossary](https://github.com/jk8s/sig-docs-id-localization-how-tos/blob/master/resources/RSNI-glossarium.pdf)

/language id
/cc @kubernetes/sig-docs-id-reviews

**Comment by frbimo** [comment]
> We are not officially listing down target pages to translate, but feel free if you have spare time to translate some.

[quality-service-pod](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/) has no id translation. is it available for pickup?

**Comment by girikuncoro** [comment]
> > We are not officially listing down target pages to translate, but feel free if you have spare time to translate some.
> 
> [quality-service-pod](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/) has no id translation. is it available for pickup?

@frbimo yes feel free to pick it up! When you raise PR, mention this issue, I'll list the pages on description, thanks for your contribution!

**Comment by ariscahyadi** [comment]
Hi All,

We tried to sort the list of common words (around 100) as mentioned here https://docs.google.com/spreadsheets/d/1uK1TGfKyT5ZmWWQx4c4KYm7YmOmuOHyQW-bh8rGTMP4/edit#gid=0
and please find below top 30 words which are used over 1000 times in Kubernetes English documentation

- cluster     6757
- container     5727
- node     5326
- file     4536
- service     4482
- set     4294
- resource     3884
- default     3128
- deploy     3007
- image     2784
- request     2630
- object     2270
- command     2141
- view     2092
- support     2059
- release     1975
- tool     1921
- deployment     1854
- client     1759
- reference     1460
- update     1441
- state     1316
- task     1280
- certificate     1233
- install     1136
- scale     1119
- process     1098
- replica     1085
- flag     1031
- event     1006

@girikuncoro @wahyuoi @danninov let me know if you have any comments!

**Comment by girikuncoro** [comment]
I have collected the pages using [our script](https://github.com/jk8s/sig-docs-id/blob/master/scripts/diff_en_id.py) that we have but no longer found in the english folders, these are caused by either removal or pages have been moved to new path:
- [ ] website/content/id/docs/templates/index.md
- [ ] website/content/id/docs/concepts/workloads/pods/pod.md
- [ ] website/content/id/docs/concepts/extend-kubernetes/poseidon-firmament-alternate-scheduler.md
- [ ] website/content/id/docs/concepts/workloads/pods/pod-overview.md
- [ ] website/content/id/docs/concepts/workloads/controllers/jobs-run-to-completion.md
- [ ] website/content/id/docs/search.md
- [ ] website/content/id/docs/concepts/cluster-administration/monitoring.md
- [ ] website/content/id/docs/concepts/configuration/pod-overhead.md
- [ ] website/content/id/docs/concepts/cluster-administration/controller-metrics.md
- [ ] website/content/id/docs/reference/glossary/kuantitas.md
- [ ] website/content/id/docs/tasks/tools/kubeadm/_index.md
- [ ] website/content/id/docs/setup/learning-environment/minikube.md
- [ ] website/content/id/docs/concepts/scheduling/scheduler-perf-tuning.md
- [ ] website/content/id/docs/concepts/configuration/taint-and-toleration.md
- [ ] website/content/id/docs/concepts/cluster-administration/cluster-administration-overview.md
- [ ] website/content/id/docs/concepts/containers/overview.md
- [ ] website/content/id/docs/sitemap.md
- [ ] website/content/id/docs/concepts/configuration/resource-bin-packing.md
- [ ] website/content/id/docs/tasks/tools/install-minikube.md
- [ ] website/content/id/docs/concepts/cluster-administration/cloud-providers.md
- [ ] website/content/id/docs/concepts/cluster-administration/federation.md
- [ ] website/content/id/docs/tasks/administer-cluster/cluster-management.md
- [ ] website/content/id/docs/concepts/scheduling/kube-scheduler.md
- [ ] website/content/id/docs/concepts/scheduling/scheduling-framework.md
- [ ] website/content/id/docs/tasks/example-task-template.md
- [ ] website/content/id/docs/concepts/configuration/manage-compute-resources-container.md
- [ ] website/content/id/docs/concepts/scheduling/_index.md
- [ ] website/content/id/docs/concepts/configuration/assign-pod-node.md

Let me know what you think!

**Comment by girikuncoro** [comment]
I ran the [upstream script](https://github.com/kubernetes/website/blob/master/scripts/upstream_changes.py), traced all pages that are different with commit hash, and dump the diff into collection of files stored in our [jk8s repo](https://github.com/jk8s/sig-docs-id/tree/master/upstream_change_snapshot_20201127). There are 96 obsolete files, let me know if this make sense.

**Comment by habibrosyad** [comment]
content/en//docs/reference/glossary/kuantitas.md will be handled via https://github.com/kubernetes/website/issues/24382 (has a PR already in https://github.com/kubernetes/website/pull/24347 which is still in progress to be divided into smaller chunk and need to be revisited again according to the new central glossary).

**Comment by ariscahyadi** [comment]
Hi @girikuncoro,

I have already opened new tracking issue M6 #26955, so you may close this issue.

Thanks,
Aris.

/cc @kubernetes/sig-docs-id-reviews

**Comment by girikuncoro** [comment]
Thanks @ariscahyadi 

/close
