### ISSUE TITLE
[zh] Umbrella issue: pages out of sync in tasks section

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#26178]
The following pages are out of sync as of Jan 21, 2021. When signing up and working on a particular task, please leave a comment to this issue and ensure you have fetched the latest master.

Audit (XXL): @tengqm #26249

- [x] content/zh/docs/tasks/debug-application-cluster/audit.md

Kubeadm Upgrade (XXL): @tengqm #26271

- [x] content/zh/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md

Install Kubectl (XXL): @tengqm #26287

- [x] content/zh/docs/tasks/tools/install-kubectl.md

Stateful App (XL): @tengqm #26291

- [x] content/zh/docs/tasks/run-application/run-replicated-stateful-application.md

Connecting Frontend Backend (XL): @tengqm #26298

- [x] content/zh/docs/tasks/access-application-cluster/connecting-frontend-backend.md

HPA (XL): @tengqm #26299

- [x] content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md

Probes (XL): @tengqm #26314

- [x] content/zh/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md

CRICTL (L): @chenxuc #26316

- [x] content/zh/docs/tasks/debug-application-cluster/crictl.md

Service Account (L): @chenxuc #26257

- [x] content/zh/docs/tasks/configure-pod-container/configure-service-account.md

Topology Manageer (L): @chenxuc #26363

- [x] content/zh/docs/tasks/administer-cluster/topology-manager.md

Portforward (L): @chenxuc  #26283

- [x] content/zh/docs/tasks/access-application-cluster/port-forward-access-application-cluster.md

HA (L): @chenxuc #26332

- [x] content/zh/docs/tasks/administer-cluster/highly-available-master.md

Misc Batch 1 (M):  CaoDonghui123 #26237

- [x] content/zh/docs/tasks/extend-kubernetes/setup-konnectivity.md
- [x] content/zh/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

Misc Batch 2 (S): @chenxuc   #26250, #26252  @ydFu #26213

- [x] content/zh/docs/tasks/debug-application-cluster/debug-pod-replication-controller.md
- [x] content/zh/docs/tasks/tools/_index.md
- [x] content/zh/docs/tasks/manage-kubernetes-objects/kustomization.md
- [x] content/zh/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md
- [x] content/zh/docs/tasks/administer-cluster/namespaces.md
- [x] content/zh/docs/tasks/administer-cluster/nodelocaldns.md
- [x] content/zh/docs/tasks/administer-cluster/out-of-resource.md
- [x] content/zh/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md

**Tip**

To understand what are the contents to be synced, run this for example:

```
./scripts/lsync.sh content/zh/docs/tasks/administer-cluster/out-of-resource.md
```

**Comment by chenxuc** [comment]
I will try to work on some of items. I will mark which item I'm currently working on in the comment later.
/assign

**Comment by CaoDonghui123** [comment]
I will try to sync Misc Batch 1 (M).
/assign

**Comment by chenxuc** [comment]
I will work on the remaining items in Misc Batch 2 (S)

- [ ]  content/zh/docs/tasks/debug-application-cluster/debug-pod-replication-controller.md
- [ ]  content/zh/docs/tasks/tools/_index.md
- [ ]  content/zh/docs/tasks/manage-kubernetes-objects/kustomization.md
- [ ]  content/zh/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md
- [ ]  content/zh/docs/tasks/administer-cluster/nodelocaldns.md
- [ ]  content/zh/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md

**Comment by chenxuc** [comment]
I'm working on following items:

| Issue Name  | PR |
| ------------- | ------------- |
| Misc Batch 2  | #26250 (merged) <br> #26252 (open)  |
| Service Account   | WIP  |

**Comment by chenxuc** [comment]
I'm working on following items:

| Issue Name  | PR |
| ------------- | ------------- |
| Misc Batch 2  | #26250 (merged) <br> #26252 (merged)  |
| Service Account (L)   | #26257 (merged)  |
| Portforward (L) | #26283 (merged) |
| HA (L) | WIP |
| CRICTL (L) | WIP |

**Comment by chenxuc** [comment]
I'm working on following items:

| Issue Name  | PR |
| ------------- | ------------- |
| Misc Batch 2  | #26250 (merged) <br> #26252 (merged)  |
| Service Account (L)   | #26257 (merged)  |
| Portforward (L) | #26283 (merged) |
| CRICTL (L) | #26316 (open) |
| HA (L) | #26332 (open) |

**Comment by chenxuc** [comment]
@tengqm 
The PR for "Service Account (L)" is merged. You might want to update the issue list with the PR #26257 .
The only item left seems to be "Topology Manageer (L)".

**Comment by chenxuc** [comment]
I will finish the last item "Topology Manageer (L)" in next couple days.

| Issue Name  | PR |
| ------------- | ------------- |
| Misc Batch 2  | #26250 (merged) <br> #26252 (merged)  |
| Service Account (L)   | #26257 (merged)  |
| Portforward (L) | #26283 (merged) |
| HA (L) | #26332 (merged) |
| CRICTL (L) | #26316 (open) |
| Topology Manageer (L) | WIP |

**Comment by chenxuc** [comment]
All items are completed!

| Issue Name  | PR |
| ------------- | ------------- |
| Misc Batch 2  | #26250 (merged) <br> #26252 (merged)  |
| Service Account (L)   | #26257 (merged)  |
| Portforward (L) | #26283 (merged) |
| HA (L) | #26332 (merged) |
| CRICTL (L) | #26316 (merged) |
| Topology Manageer (L) | #26363 (merged) |

**Comment by tengqm** [comment]
🎉   We made it!

/close
