### ISSUE TITLE
[zh] Umbrella issue: pages out of sync in concepts section

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#26177]
The following pages needs sync as of Jan 21, 2021.

Garbage Collection: @chenxuc #26236

- [x] content/zh/docs/concepts/workloads/controllers/garbage-collection.md

PSP

- [x] content/zh/docs/concepts/policy/pod-security-policy.md

System Logs: @ydFu  #26248

- [x] content/zh/docs/concepts/cluster-administration/system-logs.md

Misc Batch 1: @ydFu

- [x] content/zh/docs/concepts/configuration/overview.md
- [x] content/zh/docs/concepts/scheduling-eviction/assign-pod-node.md
- [x] content/zh/docs/concepts/scheduling-eviction/pod-overhead.md
- [x] content/zh/docs/concepts/storage/volume-snapshot-classes.md
- [x] content/zh/docs/concepts/storage/volumes.md

Misc Batch 2:  @ydFu #26239

- [x] content/zh/docs/concepts/services-networking/network-policies.md
- [x] content/zh/docs/concepts/services-networking/service.md
- [x] content/zh/docs/concepts/services-networking/dns-pod-service.md

Misc Batch 3

- [x] content/zh/docs/concepts/workloads/pods/disruptions.md
- [x] content/zh/docs/concepts/workloads/pods/init-containers.md
- [x] content/zh/docs/concepts/workloads/pods/ephemeral-containers.md
- [x] content/zh/docs/concepts/workloads/controllers/replicaset.md
- [x] content/zh/docs/concepts/workloads/controllers/replicationcontroller.md

Misc Batch 4: @ydFu

- [x] content/zh/docs/concepts/architecture/controller.md
- [x] content/zh/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
- [x] content/zh/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
- [x] content/zh/docs/concepts/extend-kubernetes/operator.md

Misc Batch 5

- [x] content/zh/docs/concepts/policy/resource-quotas.md
- [x] content/zh/docs/concepts/cluster-administration/system-metrics.md
- [x] content/zh/docs/concepts/cluster-administration/flow-control.md

**Tip**

To understand what are the contents to be synced, run this for example:

```
./scripts/lsync.sh content/zh/docs/concepts/policy/resource-quotas.md
```

**Comment by chenxuc** [comment]
I will try to work on some of items. I will mark which item I'm currently working on in the comment.
/assign

**Comment by chenxuc** [comment]
Working on following items:
Garbage Collection

 content/zh/docs/concepts/workloads/controllers/garbage-collection.md
PSP

 content/zh/docs/concepts/policy/pod-security-policy.md
System Logs

 content/zh/docs/concepts/cluster-administration/system-logs.md

**Comment by ydFu** [comment]
I will done 'Misc Batch 1' in PR #26220 .

**Comment by ydFu** [comment]
I will do 'Misc Batch 5' in PR #26232
|  **Issue Name**  | **PR  number**  | **State**  |
|  ----  | ----  | ----  |
| Misc Batch 1  |  #26220  |  Merged  |
| Misc Batch 4  |  #26219  |  Merged  |
| Misc Batch 5  |  #26232  |  Open  |

/assign

**Comment by ydFu** [comment]
I will do 'Misc Batch 2' in PR #26239

|  **Issue Name**  | **PR  number**  | **State**  |
|  ----  | ----  | ----  |
| Misc Batch 1  |  #26220  |  Merged  |
| Misc Batch 2  |  #26239  |  Open  |
| Misc Batch 4  |  #26219  |  Merged  |
| Misc Batch 5  |  #26232  |  Merged  |

**Comment by ydFu** [comment]
I compiled the information that is PR Related this issue.
|  **Issue Name**  | **PR  number**  | **State**  |
|  ----  | ----  | ----  |
| System Logs  |  #26248  |  Open  |
| PSP  | #26232 | Merged  |
| Misc Batch 1  |  #26220  |  Merged  |
| Misc Batch 2  |  #26239  |  Merged  |
| Misc Batch 3  |  #26195,#26211,#26210,#26208  |  Merged  |
| Misc Batch 4  |  #26219  |  Merged  |
| Misc Batch 5  |  #26232  |  Merged  |

**Comment by tengqm** [comment]
All work items completed!!!
@ydFu @chenxuc Thank you for your hard work!
