### ISSUE TITLE
Tracking stale content within the website repo

### ISSUE THREAD

**Issue by a-mccarthy** [kubernetes/website#26717]
**This is a Feature Request**

SIG Docs should have a way to identify if content within the website repo is potentially stale and have a way to communicate potentially stale content to SIG groups that own the content. 

The goal of this issue is to outline a MVP to track and update stale content in the kubernetes/website repo. The project has the potential to make of changes to the website repo and processes so our first goal is to determine its viability and the best way to implement it within the community. There has been ongoing work to identify how SIG Docs can implement this and the pieces needed to make this work across the repo and community, see more information on the project outline in this [doc](https://docs.google.com/document/d/1H5I5kVovfXWd3jpXm-mmy7L2D9uIweo77kZs4-NazQs/edit#).

There is still a lot of room for improvement and this project depends on getting support and feedback from SIGs and the community :) 

**What would you like to be added**

**MVP:** The ability perform a single pass over a portion of the website repo, identify stale content, and work with a SIG to review content for accuracy and make and updates as necessary. 

- [ ] Define what constitutes stale content in the kubernetes/website repo. 
- [ ] Develop a simple, automated way to identify stale content in the repo.
- [ ] Work with at least one SIG to help review and update stale content that relates to their specific subject area

**Scope**
- Only review English language content in `content/docs/en`, excluding _index.md and glossary files.
- Limit content review down to one single topic area, for example working with only tasks, tutorials, or concepts and only content that would be owned by one SIG. TBD - picking an area 

*Define what constitutes stale content in the kubernetes/website repo.*

Working definition - needs improvement
* Content that has not be updated in > 1 year based on git last commit date

*Develop a simple, automated way to identify stale content in the repo*

Depends on having a clear definition of stale content. POC script started in https://github.com/kubernetes/website/pull/26442

*Work with at least one SIG to help review and update stale content that relates to their specific subject area*

This project requires a lot of input and cooperation from SIG groups. To start, use a single SIG to get feedback and iterate on processes before expanding the project scope.

To Do:
- Identify a SIG willing to help with this MVP
- Work on a communication place to talk about this project broadly. 

**Why is this needed**

SIG Docs needs better visibility into content state on the kubernetes.io website. There is currently no easy way to tell if content has been kept up to date, especially in cases when maintainers turnover or there are long gaps between when a feature is promoted between stages (alpha, beta, GA). By building a way to make sure content on the site is being updated regularly, users can have greater confidence in docs on kubernetes.io. 

This will ultimately benefit all SIGs because having reliability up-to-date docs can help to reduce the overall support burden of SIGs as users face less frustration, ask less questions, and file less issues when information is current. 

**Comments**

See more information about the project in the [overview doc](https://docs.google.com/document/d/1H5I5kVovfXWd3jpXm-mmy7L2D9uIweo77kZs4-NazQs/edit#)

**Comment by kbhawkey** [comment]
Good start @a-mccarthy .
/triage accepted

**Comment by a-mccarthy** [comment]
> Only review English language content in content/docs/en, excluding _index.md and glossary files.

We talked about excluding _index.md files bc they are built from a template and blank, however that is not the case for every _index.md file, for example: https://kubernetes.io/docs/tasks/tools/. 

I still feel like the number _index.md files with non-template generated content is relatively low, so we can probably still exclude them from this search, but I wanted to make a note about them existing.
