### ISSUE TITLE
Tracking Indonesian Translation Progress (M6)

### ISSUE THREAD

**Issue by ariscahyadi** [kubernetes/website#26955]
This is tracking issue of our progress from Q1 2021 onwards. In the beginning of this milestone, as per our [metrics](https://app.circleci.com/pipelines/github/jk8s/sig-docs-id/33/workflows/e59d9d32-55b7-49f7-86ad-c818ea562c5f/jobs/61), we have translated 220 pages from 84 contributors (the script from main repo shows 260+ pages), with around 8,000 views per month. In this milestone, we still continuing on updating the obsolete pages. We are not officially listing down target pages to translate, but feel free if you have spare time to translate some.

## Maintainers
- @ariscahyadi
- @danninov
- @girikuncoro
- @irvifa
- @phanama
- @qbl
- @wahyuoi
- @habibrosyad 

## For New Contributors

Please check this documentation about [Dokumentasi Khusus Untuk Translasi Bahasa Indonesia](https://kubernetes.io/id/docs/contribute/localization_id/) which gives step-by-step on how to start to contribute and translate using official guidelines.

## Work Status

There is a list of outdated pages (40 out of 162 pages for this milestone) and please feel free if you want to take part on this work.

### PIC: @ariscahyadi 
- [X] **removed** content/en//docs/search.md #27153
- [X] **removed** content/en//docs/tasks/tools/install-minikube.md #27154
- [X]  **removed** content/en//docs/tasks/tools/kubeadm/_index.md #27266
- [X] **removed** content/en//docs/tasks/example-task-template.md #27388
- [X] **removed** content/en//docs/tasks/administer-cluster/cluster-management.md #27389
- [X] **removed** content/en//docs/setup/learning-environment/minikube.md #24533
- [X] **removed** content/en//docs/concepts/configuration/assign-pod-node.md #27434
- [X] **removed** content/en//docs/concepts/configuration/pod-overhead.md #27403

### PIC: @danninov 
- [ ] **removed** content/en//docs/concepts/configuration/manage-compute-resources-container.md
- [X] **moved** content/en//docs/concepts/configuration/resource-bin-packing.md #27533
- [X] **moved** content/en//docs/concepts/configuration/taint-and-toleration.md #27434
- [X] **renamed** content/en//docs/concepts/scheduling/scheduling-framework.md #27535
- [X] **renamed** content/en//docs/concepts/scheduling/scheduler-perf-tuning.md #27535
- [X] **renamed** content/en//docs/concepts/scheduling/kube-scheduler.md #27535
- [X] **renamed** content/en//docs/concepts/scheduling/_index.md #27535
- [ ] **removed** content/en//docs/concepts/workloads/pods/pod-overview.md
 
### PIC: TBD
- [ ] **removed** content/en//docs/concepts/workloads/pods/pod.md
- [ ] **removed** content/en//docs/concepts/workloads/controllers/jobs-run-to-completion.md
- [ ] **removed** content/en//docs/concepts/extend-kubernetes/poseidon-firmament-alternate-scheduler.md
- [ ] **removed** content/en//docs/concepts/containers/overview.md
- [ ] **removed** content/en//docs/concepts/cluster-administration/cluster-administration-overview.md
- [ ] **removed** content/en//docs/concepts/cluster-administration/federation.md
- [ ] **removed** content/en//docs/concepts/cluster-administration/cloud-providers.md
- [ ] **removed** content/en//docs/concepts/cluster-administration/controller-metrics.md

### PIC: @habibrosyad 
- [X] **removed** content/en//docs/concepts/cluster-administration/monitoring.md #27208
- [X] **removed**  content/en//docs/templates/index.md #27137
- [X] **removed** content/en//docs/reference/glossary/kuantitas.md #26090
- [X] **removed** content/en//docs/sitemap.md #27138
- [X] **modified** content/en/includes/task-tutorial-prereqs.md #27211
- [X] **modified** content/en/docs/home/supported-doc-versions.md #27213
- [ ] **modified** content/en/docs/home/_index.md
- [ ] **modified** content/en/docs/tasks/debug-application-cluster/resource-usage-monitoring.md

### PIC: TBD
- [ ] **modified** content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
- [ ] **modified** content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
- [ ] **modified** content/en/docs/tasks/run-application/run-stateless-application-deployment.md
- [ ] **modified** content/en/docs/tasks/run-application/force-delete-stateful-set-pod.md
- [ ] **modified** content/en/docs/tasks/tools/install-kubectl.md
- [ ] **modified** content/en/docs/tasks/tools/_index.md
- [ ] **modified** content/en/docs/tasks/configure-pod-container/configure-service-account.md
- [ ] **modified** content/en/docs/tasks/configure-pod-container/configure-persistent-volume-storage.md

/language id
/cc @kubernetes/sig-docs-id-reviews

**Comment by habibrosyad** [comment]
@ariscahyadi I'm taking the 4th part, as I've done the `content/en/docs/reference/glossary/kuantitas.md` in https://github.com/kubernetes/website/pull/26090

**Comment by ariscahyadi** [comment]
> @ariscahyadi I'm taking the 4th part, as I've done the `content/en/docs/reference/glossary/kuantitas.md` in #26090

Thanks @habibrosyad .. it is updated.

**Comment by ariscahyadi** [comment]
`content/en/docs/search.md` is moved to `content/en/search.md` as mentioned here #23083

**Comment by ariscahyadi** [comment]
`content/en/docs/tasks/tools/install-minikube.md`is removed and redirect to official minikube webpage https://minikube.sigs.k8s.io/docs/start/ , as mentioned here #23354

**Comment by ariscahyadi** [comment]
The whole `content/en/docs/tasks/tools/kubeadm/` pages are move into `content/endocs/reference/setup-tools/kubeadm/` including `_index.md` as mentioned here #23048

**Comment by habibrosyad** [comment]
The whole `content/en/docs/templates/` are removed in https://github.com/kubernetes/website/pull/20893, I'm going to remove the directory as well as it's unused now.

**Comment by habibrosyad** [comment]
`content/en/docs/concepts/cluster-administration/monitoring.md` is moved to `content/en/docs/concepts/cluster-administration/system-metrics.md` via https://github.com/kubernetes/website/pull/21202

**Comment by habibrosyad** [comment]
`content/en/docs/sitemap.md` is removed via https://github.com/kubernetes/website/pull/24270

**Comment by habibrosyad** [comment]
Just sharing a useful trick for finding related PR which delete/modified a file:

### 1. Get a commit hash related with the changes
```bash
git log --diff-filter=D -- [file path]
```

e.g.

```bash
git log --diff-filter=D -- content/en/docs/sitemap.md 
```

The output will be similar with this:
```bash
commit b1fb333fad2301d4d6c30548fb001687f42e24c1
Author: ROSHEEN NAEEM <rosheennaeem4@gmail.com>
Date:   Wed Sep 30 20:30:50 2020 +0500

    Delete sitemap.md
```

Please note the commit has in the output (`b1fb333fad2301d4d6c30548fb001687f42e24c1`, in the case of the example above).

You can use the same command to find which commit modified a file by changing the filter from `D` to `M` (refer to [here](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203) for more filters)

### 2. Check the commit in github

Go to, e.g., `https://github.com/kubernetes/website/commit/b1fb333fad2301d4d6c30548fb001687f42e24c1` (replace `b1fb333fad2301d4d6c30548fb001687f42e24c1` with your commit hash in step 1).

Find the related PR with the commit, e.g. via web UI:
![image](https://user-images.githubusercontent.com/4804060/111772042-fd605c00-88de-11eb-9a12-1b7300b71cb0.png)

In bottom left hand corner near the branch name, in this case `master`, you can see the PR id `(#24270)`. Click on the link and you will be redirected to the respective PR page, then you can analyse what changes has been made and what actions needed to incorporate it to our localization.

**Comment by ariscahyadi** [comment]
`content/en//docs/tasks/example-task-template.md` is removed here #22301 together with others.

**Comment by ariscahyadi** [comment]
`content/en//docs/tasks/administer-cluster/cluster-management.md` is removed here #24415

**Comment by ariscahyadi** [comment]
Hi @kubernetes/sig-docs-id-reviews ... it seems this issue is automatically closed.
Do you have any idea how to re-opened it?

**Comment by ariscahyadi** [comment]
Thanks @irvifa :)

**Comment by ariscahyadi** [comment]
Hi @kubernetes/sig-docs-id-reviews .... I think we need to close this issue, because it has already behind the schedule.
Do we need to complete all within 1-2 weeks? or we need to carry forward to next quarter?

**Comment by ariscahyadi** [comment]
Hi All,

I have opened Q2 2021 tracking issue #28772
