### ISSUE TITLE
Tracking Indonesian Translation Progress (M7)

### ISSUE THREAD

**Issue by ariscahyadi** [kubernetes/website#28772]
This is tracking issue of our progress from Q2 2021 onwards. In the beginning of this milestone, as per our [metrics](https://app.circleci.com/pipelines/github/jk8s/sig-docs-id/33/workflows/e59d9d32-55b7-49f7-86ad-c818ea562c5f/jobs/61), we have translated 220 pages from 84 contributors (the script from main repo shows 260+ pages), with around 8,000 views per month. In this milestone, we still continuing on updating the obsolete pages. We are not officially listing down target pages to translate, but feel free if you have spare time to translate some.

## Maintainers
- @ariscahyadi
- @danninov
- @girikuncoro
- @irvifa
- @phanama
- @qbl
- @wahyuoi
- @habibrosyad 

## For New Contributors

Please check this documentation about [Dokumentasi Khusus Untuk Translasi Bahasa Indonesia](https://kubernetes.io/id/docs/contribute/localization_id/) which gives step-by-step on how to start to contribute and translate using official guidelines.

## Work Status

There is a list of 28 pages and please feel free if you want to take part on this work.

### Follow-up pages from M6 Milestone

- [ ] **add** content/en/docs/contribute/style/write-new-topic.md
- [ ] **add** content/en/docs/tasks/administer-cluster/cluster-upgrade.md
- [ ] **add** content/en/docs/tasks/administer-cluster/enable-disable-api.md
- [ ] **add** content/en/docs/tasks/administer-cluster/safely-drain-node.md
- [ ] **modify** content/en/docs/setup/_index.md
- [ ] **modify** content/en/docs/concepts/architecture/nodes.md
- [ ] **modify** content/en/docs/concepts/cluster-administration/_index.md
- [ ] **modify** content/en/docs/concepts/configuration/pod-priority-preemption.md

### Remove pages
- [ ] **removed** content/en//docs/concepts/configuration/manage-compute-resources-container.md
- [ ] **removed** content/en//docs/concepts/workloads/pods/pod-overview.md
- [ ] **removed** content/en//docs/concepts/workloads/pods/pod.md
- [ ] **removed** content/en//docs/concepts/workloads/controllers/jobs-run-to-completion.md #29173
- [ ] **removed** content/en//docs/concepts/extend-kubernetes/poseidon-firmament-alternate-scheduler.md
- [ ] **removed** content/en//docs/concepts/containers/overview.md
- [ ] **removed** content/en//docs/concepts/cluster-administration/cluster-administration-overview.md
- [ ] **removed** content/en//docs/concepts/cluster-administration/federation.md
- [ ] **removed** content/en//docs/concepts/cluster-administration/cloud-providers.md
- [ ] **removed** content/en//docs/concepts/cluster-administration/controller-metrics.md

### Modified Pages
- [ ] **modified** content/en/docs/home/_index.md
- [ ] **modified** content/en/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
- [ ] **modified** content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
- [ ] **modified** content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
- [ ] **modified** content/en/docs/tasks/run-application/run-stateless-application-deployment.md
- [ ] **modified** content/en/docs/tasks/run-application/force-delete-stateful-set-pod.md
- [ ] **modified** content/en/docs/tasks/tools/install-kubectl.md
- [ ] **modified** content/en/docs/tasks/tools/_index.md
- [ ] **modified** content/en/docs/tasks/configure-pod-container/configure-service-account.md
- [ ] **modified** content/en/docs/tasks/configure-pod-container/configure-persistent-volume-storage.md

———————————————————————————————————-———————————————————

Trick to find related PR which delete/modified a file as shared by @habibrosyad

**1. Get a commit hash related with the changes**

`git log --diff-filter=D -- [file path]`
e.g.
`git log --diff-filter=D -- content/en/docs/sitemap.md`
The output will be similar with this:
```commit b1fb333fad2301d4d6c30548fb001687f42e24c1
Author: ROSHEEN NAEEM <rosheennaeem4@gmail.com>
Date:   Wed Sep 30 20:30:50 2020 +0500

Delete sitemap.md
```
Please note the commit hash in the output (`b1fb333fad2301d4d6c30548fb001687f42e24c1`, in the case of the example above).
You can use the same command to find which commit modified a file by changing the filter from D to M (refer to [here](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203) for more filters). In case of modified file, you might get multiple commit hashes, pick the latest one (contains the recent changes), or just pick ones that suit your needs.

**2. Check the commit in Github**

Go to, e.g., https://github.com/kubernetes/website/commit/b1fb333fad2301d4d6c30548fb001687f42e24c1 (replace b1fb333fad2301d4d6c30548fb001687f42e24c1 with your commit hash in step 1).
Find the related PR with the commit, e.g. via web UI:

![](https://user-images.githubusercontent.com/4804060/111772042-fd605c00-88de-11eb-9a12-1b7300b71cb0.png)

In bottom left hand corner near the branch name, in this case master, you can see the PR id (#24270). Click on the link and you will be redirected to the respective PR page, then you can analyse what changes has been made and what actions needed to incorporate it to our localization.

/language id
/cc @kubernetes/sig-docs-id-reviews

**Comment by seokho-son** [comment]
Hi folks!

As a sig-docs localization subproject lead, I would like to check if this issue remains useful and if there's a general willingness to keep it open as is. (sig-docs is endeavoring to manage the quantity of open issues.)

PTAL
@ariscahyadi
@danninov
@girikuncoro
@irvifa
@phanama
@qbl
@wahyuoi
@habibrosyad

**Comment by girikuncoro** [comment]
@seokho-son thanks for commenting, this issue is more than 2 years old, and few of them are no longer relevant, currently @kubernetes/sig-docs-id-owners still looking for lead who wants to drive the ID localization further, we can close this issue and revisit after we revamp the project initiative
