### ISSUE TITLE
[zh] Concept files to sync for 1.22

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#29325]
Numbers in the following list may be not up to date. Please run `./scripts/lsync.sh` again before working on each of them.

- [x] (1) Secret Rewriting  @howieyuen   #29823

```
32	26	content/zh/docs/concepts/configuration/secret.md
```

- [x] (2) Pod Security Standards Revision   @mayocream  #29996

```
376	184	content/zh/docs/concepts/security/pod-security-standards.md
```

- [x] (3) Persistent Volume   @mayocream  #30002

```
125	40	content/zh/docs/concepts/storage/persistent-volumes.md
```

- [x] (4) Flow Control  @howieyuen   #29866

```
83	53	content/zh/docs/concepts/cluster-administration/flow-control.md
```

- [x] (5) Workload Controllers  @mayocream   #30014

```
4	3	content/zh/docs/concepts/workloads/controllers/cron-jobs.md
35	22	content/zh/docs/concepts/workloads/controllers/daemonset.md
29	15	content/zh/docs/concepts/workloads/controllers/statefulset.md
2	2	content/zh/docs/concepts/workloads/controllers/replicaset.md
55	22	content/zh/docs/concepts/workloads/controllers/job.md
```

- [x] (6) Policies  @mayocream    #30015

```
20	14	content/zh/docs/concepts/policy/resource-quotas.md
13	6	content/zh/docs/concepts/policy/pid-limiting.md
50	10	content/zh/docs/concepts/policy/pod-security-policy.md
```

- [x] (7) Pods  @mayocream    #30032

```
13	3	content/zh/docs/concepts/workloads/pods/pod-lifecycle.md
2	2	content/zh/docs/concepts/workloads/pods/disruptions.md
7	4	content/zh/docs/concepts/workloads/pods/init-containers.md
4	116	content/zh/docs/concepts/workloads/pods/ephemeral-containers.md
14	2	content/zh/docs/concepts/workloads/pods/_index.md
```

- [x] (8) Service @EricWvi  #29369 

```
14	5	content/zh/docs/concepts/services-networking/network-policies.md
0	1	content/zh/docs/concepts/services-networking/endpoint-slices.md
44	10	content/zh/docs/concepts/services-networking/service.md
6	1	content/zh/docs/concepts/services-networking/ingress.md
16	3	content/zh/docs/concepts/services-networking/dns-pod-service.md
```

- [x] (9) Scheduling @mengjiao-liu   #29423

```
**removed**	content/zh/docs/concepts//scheduling-eviction/eviction-policy.md
1	1	content/zh/docs/concepts/scheduling-eviction/scheduling-framework.md
9	9	content/zh/docs/concepts/scheduling-eviction/pod-priority-preemption.md
2	2	content/zh/docs/concepts/scheduling-eviction/scheduler-perf-tuning.md
27	26	content/zh/docs/concepts/scheduling-eviction/resource-bin-packing.md
19	6	content/zh/docs/concepts/scheduling-eviction/taint-and-toleration.md
2	2	content/zh/docs/concepts/scheduling-eviction/kube-scheduler.md
2	2	content/zh/docs/concepts/scheduling-eviction/assign-pod-node.md
```

- [x] (10) Storage  @howieyuen   #29965

```
33	4	content/zh/docs/concepts/storage/storage-classes.md
25	48	content/zh/docs/concepts/storage/volumes.md
```

- [x] (11) Basic Objects  @mayocream   #30037 

```
17	2	content/zh/docs/concepts/containers/images.md
4	4	content/zh/docs/concepts/containers/runtime-class.md
13	2	content/zh/docs/concepts/overview/working-with-objects/names.md
1	1	content/zh/docs/concepts/overview/working-with-objects/field-selectors.md
4	5	content/zh/docs/concepts/overview/working-with-objects/kubernetes-objects.md
5	0	content/zh/docs/concepts/overview/working-with-objects/annotations.md
2	2	content/zh/docs/concepts/overview/working-with-objects/labels.md
```

- [x] (12) Cluster Admin   @superleo   #30211

```
5	1	content/zh/docs/concepts/configuration/organize-cluster-access-kubeconfig.md
3	1	content/zh/docs/concepts/security/overview.md
1	1	content/zh/docs/concepts/architecture/cloud-controller.md
60	2	content/zh/docs/concepts/architecture/nodes.md
1	1	content/zh/docs/concepts/cluster-administration/manage-deployment.md
**removed**	content/zh/docs/concepts//cluster-administration/kubelet-garbage-collection.md
5	2	content/zh/docs/concepts/cluster-administration/logging.md
**removed**	content/zh/docs/concepts//workloads/controllers/garbage-collection.md
```

- [x] (13) k8s Extension  @superleo  #29984

```
11	2	content/zh/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
2	2	content/zh/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md
3	3	content/zh/docs/concepts/extend-kubernetes/operator.md
```

**Comment by tengqm** [comment]
@mengjiao-liu @zhangguanzhang @kerthcet @rudeigerc @hide-in-code @able8 @jaronnie @keashem @loufenghua @chenxuc @howieyuen @dcoliversun @liuxu623 @eatjeff @liutaot @gaoguangze111 @buptliuwei @HongjiangHuang @zhiguo-lu @timyinshi

**Comment by mengjiao-liu** [comment]
I want to try this aspect of synchronous scheduling.
```
(9) Scheduling

**removed**	content/zh/docs/concepts//scheduling-eviction/eviction-policy.md
1	1	content/zh/docs/concepts/scheduling-eviction/scheduling-framework.md
9	9	content/zh/docs/concepts/scheduling-eviction/pod-priority-preemption.md
2	2	content/zh/docs/concepts/scheduling-eviction/scheduler-perf-tuning.md
27	26	content/zh/docs/concepts/scheduling-eviction/resource-bin-packing.md
19	6	content/zh/docs/concepts/scheduling-eviction/taint-and-toleration.md
2	2	content/zh/docs/concepts/scheduling-eviction/kube-scheduler.md
2	2	content/zh/docs/concepts/scheduling-eviction/assign-pod-node.md

```

**Comment by howieyuen** [comment]
part 1：https://github.com/kubernetes/website/pull/29823

**Comment by mayocream** [comment]
(3) Persistent Volume https://github.com/kubernetes/website/pull/30002

**Comment by mayocream** [comment]
(4) is already updated to latest version. 
see https://github.com/kubernetes/website/pull/29866

**Comment by mayocream** [comment]
I might need help getting these PR merged. (reviewed by @tengqm, need another LGTM) 
(2) #29996
(3) #30002

And these ones need to be reviewed:
(5) #30014
(6) #30015
(7) #30032
(11) #30037

**Comment by tengqm** [comment]
We have completed this umbrella issue!!! A big thank you to y'all!
/close
