### ISSUE TITLE
[zh] Tasks files to sync for 1.22

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#29329]
Numbers in the following list may be not up to date. Please run `./scripts/lsync.sh` again before working on each of them.

- [x] (1) run-app  @steven-my  #29451
```
5	6	content/zh/docs/tasks/debug-application-cluster/debug-running-pod.md
1	1	content/zh/docs/tasks/debug-application-cluster/debug-cluster.md
**removed**	content/zh/docs/tasks//debug-application-cluster/logging-stackdriver.md
1	1	content/zh/docs/tasks/debug-application-cluster/determine-reason-pod-failure.md
3	3	content/zh/docs/tasks/run-application/delete-stateful-set.md
1	1	content/zh/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
11	8	content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
```

- [x] (2) Kubectl install  @steven-my  #29509

```
45	7	content/zh/docs/tasks/tools/install-kubectl-windows.md
81	2	content/zh/docs/tasks/tools/install-kubectl-macos.md
57	6	content/zh/docs/tasks/tools/install-kubectl-linux.md
**removed**	content/zh/docs/tasks//tools/included/install-kubectl-gcloud.md
```

- [x] (3) objects & network  @steven-my    #29772

```
3	3	content/zh/docs/tasks/manage-kubernetes-objects/kustomization.md
4	4	content/zh/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md
1	1	content/zh/docs/tasks/network/validate-dual-stack.md
130	0	content/zh/docs/tasks/network/customize-hosts-file-for-pods.md
```

- [x] (4) pod container @superleo  #29821 

```
6	4	content/zh/docs/tasks/configure-pod-container/quality-service-pod.md
8	5	content/zh/docs/tasks/configure-pod-container/configure-service-account.md
1	1	content/zh/docs/tasks/configure-pod-container/pull-image-private-registry.md
21	6	content/zh/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
20	1	content/zh/docs/tasks/configure-pod-container/security-context.md
2	2	content/zh/docs/tasks/configure-pod-container/configure-runasusername.md
0	6	content/zh/docs/tasks/manage-hugepages/scheduling-hugepages.md
```

- [x] (5) windows  @superleo  #29798

```
71	18	content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
```

- [x] (6) admin 1   @steven-my   #29797

```
22	23	content/zh/docs/tasks/administer-cluster/enabling-service-topology.md
1	0	content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
2	2	content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-deprecation-affects-you.md
26	2	content/zh/docs/tasks/administer-cluster/safely-drain-node.md
17	26	content/zh/docs/tasks/administer-cluster/kubelet-config-file.md
```

- [x] (7) admin 2   @steven-my  #29814

```
1	1	content/zh/docs/tasks/administer-cluster/namespaces-walkthrough.md
1	0	content/zh/docs/tasks/administer-cluster/declare-network-policy.md
1	1	content/zh/docs/tasks/administer-cluster/extended-resource-node.md
29	37	content/zh/docs/tasks/administer-cluster/reserve-compute-resources.md
1	1	content/zh/docs/tasks/administer-cluster/network-policy-provider/calico-network-policy.md
39	25	content/zh/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md
```

- [x] (8) admin 3  @steven-my #29815

```
3	23	content/zh/docs/tasks/administer-cluster/coredns.md
1	1	content/zh/docs/tasks/administer-cluster/encrypt-data.md
32	23	content/zh/docs/tasks/administer-cluster/reconfigure-kubelet.md
4	3	content/zh/docs/tasks/administer-cluster/namespaces.md
1	1	content/zh/docs/tasks/administer-cluster/nodelocaldns.md
**removed**	content/zh/docs/tasks/administer-cluster/out-of-resource.md
**removed**	content/zh/docs/tasks/administer-cluster/highly-available-master.md
```

- [x] (9) admin 4  @Steven-my

```
2	12	content/zh/docs/tasks/administer-cluster/dns-custom-nameservers.md
3	3	content/zh/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
3	5	content/zh/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md
14	4	content/zh/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
7	0	content/zh/docs/tasks/administer-cluster/dns-debugging-resolution.md
```

- [x] (10) admin 5  @chenxuc  #29742

```
2	2	content/zh/docs/tasks/administer-cluster/access-cluster-services.md
3	0	content/zh/docs/tasks/administer-cluster/certificates.md
2	9	content/zh/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods.md
5	5	content/zh/docs/tasks/administer-cluster/topology-manager.md
7	3	content/zh/docs/tasks/administer-cluster/sysctl-cluster.md
15	13	content/zh/docs/tasks/administer-cluster/securing-a-cluster.md
```

- [x] (11) admin 6  @chenxuc   #29584

```
1	1	content/zh/docs/tasks/administer-cluster/limit-storage-consumption.md
1	1	content/zh/docs/tasks/administer-cluster/change-pv-reclaim-policy.md
17	9	content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
14	1	content/zh/docs/tasks/administer-cluster/cpu-management-policies.md
1	1	content/zh/docs/tasks/administer-cluster/access-cluster-api.md
```

- [x] (12) access  @chenxuc  #29545 

```
2	9	content/zh/docs/tasks/access-application-cluster/port-forward-access-application-cluster.md
4	4	content/zh/docs/tasks/access-application-cluster/list-all-running-container-images.md
26	20	content/zh/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
```

- [x] (13) misc  @chenxuc  #29501

```
6	5	content/zh/docs/tasks/tls/certificate-rotation.md
3	3	content/zh/docs/tasks/configmap-secret/managing-secret-using-kustomize.md
3	3	content/zh/docs/tasks/configmap-secret/managing-secret-using-config-file.md
15	17	content/zh/docs/tasks/manage-daemon/update-daemon-set.md
1	1	content/zh/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning.md
8	4	content/zh/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
1	1	content/zh/docs/tasks/extend-kubernetes/configure-aggregation-layer.md
```

- [x] (14) Indexed parallel processing  @howieyuen   #29816 

```
NEW   content/zh/docs/tasks/job/indexed-parallel-processing-static.md
```

**Comment by tengqm** [comment]
@mengjiao-liu @zhangguanzhang @kerthcet @rudeigerc @hide-in-code @able8 @jaronnie @keashem @loufenghua @chenxuc @howieyuen @dcoliversun @liuxu623 @eatjeff @liutaot @gaoguangze111 @buptliuwei @HongjiangHuang @zhiguo-lu @timyinshi

**Comment by chenxuc** [comment]
I can work on this issue.
/assign

**Comment by steven-my** [comment]
I will work on the sections (1) run-app (2) Kubectl install
/assign

**Comment by chenxuc** [comment]
I have some family issue that might slow down my progress. steven-my has discussed with me and we will work together for this issue. Thanks.

**Comment by chenxuc** [comment]
I'm working on `(13) misc`

**Comment by chenxuc** [comment]
I'm working on `(11) admin` : PR #29584

**Comment by chenxuc** [comment]
I'm working on `(10) admin 5` : PR #29742

**Comment by steven-my** [comment]
I will work on (3) objects & network

**Comment by superleo** [comment]
I'm working on (5) windows

**Comment by superleo** [comment]
> I'm working on (5) windows

https://github.com/kubernetes/website/pull/29788

**Comment by superleo** [comment]
I will work on (4) pod container

**Comment by steven-my** [comment]
I will work on (6) admin 1 and (7) admin 2

**Comment by steven-my** [comment]
I will work on (8) admin 3

**Comment by howieyuen** [comment]
I am working on (14) and PR link https://github.com/kubernetes/website/pull/29816

**Comment by tengqm** [comment]
Superb!!!
/close
