### ISSUE TITLE
[zh] Umbrella topic for files missing translation.

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#31905]
The following files are missing in content/zh.

- [x]  153 content/en/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd.md   #31907
- [x]  483 content/en/docs/tasks/administer-cluster/memory-manager.md #31172
- [x]   79 content/en/docs/setup/best-practices/enforcing-pod-security-standards.md   #31926
- [x]  779 content/en/docs/contribute/style/diagram-guide.md   #31912
- [x]  170 content/en/docs/concepts/security/pod-security-admission.md   #31926
- [x]  123 content/en/docs/concepts/storage/projected-volumes.md   #31945
- [x]  183 content/en/docs/concepts/architecture/garbage-collection.md   #31180
- [x]   51 content/en/docs/concepts/architecture/cri.md    #31859
- [x]  478 content/en/docs/tutorials/security/apparmor.md   #31884
- [x]  526 content/en/docs/tutorials/security/seccomp.md    #31867
- [x]   75 content/en/docs/reference/tools/map-crictl-dockercli.md   #31943
- [x] 1517 content/en/docs/reference/config-api/kube-scheduler-config.v1beta3.md  #31018
- [x] 1517 content/en/docs/reference/config-api/kube-scheduler-config.v1beta2.md   #31021
- [x] 1449 content/en/docs/reference/config-api/kubeadm-config.v1beta2.md     #31030
- [x]  279 content/en/docs/reference/config-api/apiserver-encryption.v1.md   #31948
- [x]  281 content/en/docs/reference/config-api/kubelet-config.v1alpha1.md   #31951
- [x]  375 content/en/docs/reference/config-api/apiserver-config.v1alpha1.md    #31942
- [x]   91 content/en/docs/reference/config-api/apiserver-config.v1.md    #31941
- [x]  107 content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_kubeconfig_user.md  #31911
- [x]   61 content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_kubeconfig.md  #31911
- [x]   23 content/en/docs/reference/setup-tools/kubeadm/kubeadm-kubeconfig.md  #31911
- [x]   22 content/en/docs/reference/glossary/container-runtime-interface.md  #31977
- [x]   16 content/en/docs/reference/glossary/cadvisor.md   #31978
- [x]   28 content/en/docs/reference/glossary/userns.md   #31979
- [x]   25 content/en/docs/reference/glossary/event.md   #31980
- [x]  272 content/en/docs/reference/access-authn-authz/psp-to-pod-security-standards.md  #31940

**Comment by jihoon-seo** [comment]
Then it seems that nearly all of the English files are translated to Chinese (except those files, which count not that much)! Wow 😊

**Comment by FOWind** [comment]
Is there a plan to translate content under `content/zh/docs/reference/kubernetes-api` ?

**Comment by tengqm** [comment]
> Is there a plan to translate content under `content/zh/docs/reference/kubernetes-api` ?

I'm not aware of any plan so far.

**Comment by howieyuen** [comment]
all works have been done, looks like we can close this one.
Thanks to all contribution
