### ISSUE TITLE
[zh][Umbrella] Tasks pages to sync for 1.24

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#33477]
This is an umbrella issue for tasks docs that are out of sync for `zh`
localization. The difference is captured on 2022-05-05, so the list may become
outdated soon. Please do run the `scripts/lsync.sh` again before working on
any issue.

/help

- [x] tasks-1   @Abirdcfly 
```
114	64	content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
1	1	content/en/docs/tasks/run-application/run-replicated-stateful-application.md
1	1	content/en/docs/tasks/run-application/force-delete-stateful-set-pod.md
1	1	content/en/docs/tasks/network/validate-dual-stack.md
```

- [x] tasks-2     @TinySong   #33603
```
28	60	content/en/docs/tasks/configure-pod-container/configure-gmsa.md
1	1	content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
1	1	content/en/docs/tasks/configure-pod-container/configure-pod-initialization.md
22	23	content/en/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
```

- [x] tasks-3     @TinySong  #33661
```
49	3	content/en/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use.md
**removed**	content/en/docs//tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-deprecation-affects-you.md
27	2	content/en/docs/tasks/administer-cluster/migrating-from-dockershim/_index.md
```

- [x] tasks-4     @TinySong   #33723
```
46	37	content/en/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace.md
54	32	content/en/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace.md
```

- [x] tasks-5     @TinySong   #33779
```
34	21	content/en/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace.md
19	10	content/en/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace.md
38	29	content/en/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace.md
```

- [x] tasks-6     @TinySong  #33831
```
50	26	content/en/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
19	364	content/en/docs/tasks/administer-cluster/reconfigure-kubelet.md
```

- [x] tasks-7  @fenggw-fnst   #33525
```
108	81	content/en/docs/tasks/administer-cluster/encrypt-data.md
```

- [x] tasks-8   @fenggw-fnst  #33632
```
40	33	content/en/docs/tasks/administer-cluster/ip-masq-agent.md
81	38	content/en/docs/tasks/administer-cluster/nodelocaldns.md
```

- [x] tasks-9    @TinySong   #33598
```
44	31	content/en/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
1	3	content/en/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md
57	6	content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
```

- [x] tasks-10   @fenggw-fnst   #33647
```
2	2	content/en/docs/tasks/administer-cluster/securing-a-cluster.md
42	43	content/en/docs/tasks/administer-cluster/change-pv-reclaim-policy.md
49	14	content/en/docs/tasks/administer-cluster/controller-manager-leader-migration.md
```

- [x] tasks-11  @fenggw-fnst #33766  #33823
```
61	2	content/en/docs/tasks/administer-cluster/cpu-management-policies.md
87	87	content/en/docs/tasks/access-application-cluster/create-external-load-balancer.md
```

- [x] tasks-12  @Abirdcfly   #33695
```
479	3	content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
```

- [x] tasks-13  @fenggw-fnst #33914
```
1	1	content/en/docs/tasks/tls/manual-rotation-of-ca-certificates.md
1	1	content/en/docs/tasks/job/indexed-parallel-processing-static.md
31	16	content/en/docs/tasks/kubelet-credential-provider/kubelet-credential-provider.md
1	1	content/en/docs/tasks/inject-data-application/define-command-argument-container.md
50	46	content/en/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
```

- [ ] task-14 @ihuibin  #33956
```
**new** content/en/docs/tasks/administer-cluster/verify-signed-images.md
```

**Comment by fenggw-fnst** [comment]
Hi!
I want to pick up part 7 since I am just working on it.
```
108	81	content/en/docs/tasks/administer-cluster/encrypt-data.md
```
/assign

**Comment by fenggw-fnst** [comment]
Sent PR #33525 for task-7.

**Comment by TinySong** [comment]
I want to pick up part 2-6
/assign

**Comment by fenggw-fnst** [comment]
Hi, I want to pick up tasks-8 and tasks-10.

**Comment by fenggw-fnst** [comment]
Next, I would like to work on tasks-11 and tasks-13.

**Comment by Abirdcfly** [comment]
I want to work on task-1 and tasks-12
/assign

**Comment by Abirdcfly** [comment]
tasks-1  
content/zh/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md  has been fixed by https://github.com/kubernetes/website/pull/33030
content/zh/docs/tasks/run-application/run-replicated-stateful-application.md has been fixed by https://github.com/kubernetes/website/pull/33528
content/zh/docs/tasks/run-application/force-delete-stateful-set-pod.md has been fixed by https://github.com/kubernetes/website/pull/33526
content/zh/docs/tasks/network/validate-dual-stack.md has been fixed by https://github.com/kubernetes/website/pull/33527

So task1 has been completed.

**Comment by fenggw-fnst** [comment]
For tasks-13, I've sent #33914 to update kubelet-credential-provider.md and downward-api-volume-expose-pod-information.md, the rest are still in sync, so as soon as #33914 is merged, we can mark it as done.

**Comment by howieyuen** [comment]
task-14
```
content/en/docs/tasks/administer-cluster/verify-signed-images.md
```

**Comment by tengqm** [comment]
@howieyuen Task-14 has been added, but it has been taken by @ihuibin, please help review.

**Comment by howieyuen** [comment]
> @howieyuen Task-14 has been added, but it has been taken by @ihuibin, please help review.

copy that

**Comment by tengqm** [comment]
@howieyuen I have closed https://github.com/kubernetes/website/pull/33899 because it is dirty (invalid commit message plus 22 commits). Please consider take it over if time permits.

**Comment by Abirdcfly** [comment]
task 14 shuold be updated by https://github.com/kubernetes/website/pull/34400
so, this issue can be close now.
/close
