### ISSUE TITLE
[zh][Umbrella] Change language code for Chinese (simplified) to 'zh-cn'.

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#33955]
This one is an umbrella issue for the change of Chinese language code (See: #33002).
There are many warnings when building the doc site caused by the Docsy change. We need to take a series of actions to deal with this change, captured below:

- [x] Wait for #33476 to close where concepts-3 is still open.
- [x] Wait for #34033 to close so we don't have large chunk of changes to sync.
- [x] Pin the head ID on main for Chinese localization progress, with the latest list of pages to sync.
- [x] Switch the site metadata/configuration from 'zh' to 'zh-cn'. This includes changes to the config.toml and language ID related files.  #34215
- [x] Take down the head ID on main, update list of pages to sync.  #34221
- [x] Update existing pages for links with '/zh/' prefix, using new prefix '/zh-cn/'.  #34501
- [x] Update list of pages to sync.
- [x] Cleanup any other occurrences of '/zh/'.

**Note**

1. We'll not wait for #33475 to be closed because the last working item in that list depends on a huge refactoring to Windows docs.
2. We will record the list of pages to sync under this issue.

**Comment by Sea-n** [comment]
Maybe we need to add 301 redirect to [/static/_redirects](https://github.com/kubernetes/website/blob/main/static/_redirects) for existing links from external sites.

There are ~1300 files (about 900 Markdown files) in `/content/zh`, and need to consider some `aliases` and `slug`.
Currently the `_redirects` file only have ~500 lines.

**Comment by howieyuen** [comment]
first task is done, we can proceed a step forward now
