### ISSUE TITLE
[zh-cn][Umbrella] API reference pages to sync.

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#34733]
We have already translated some of the API references into Chinese. The following are pages that still need to be translated.

- [x] DaemonSet-v1   @sarazqy  #34985

```
855 content/en/docs/reference/kubernetes-api/workload-resources/daemon-set-v1.md
```     

- [x] Job-v1  @sarazqy   #34746

```
896 content/en/docs/reference/kubernetes-api/workload-resources/job-v1.md
```
     
- [x] ReplicaSet-v1   @windsonsea   #34889

```
805 content/en/docs/reference/kubernetes-api/workload-resources/replica-set-v1.md
```

- [x] CronJob-v1  @sarazqy   #34748

```
802 content/en/docs/reference/kubernetes-api/workload-resources/cron-job-v1.md
```

- [x] HPA-v1  @twilight0620    #34747

```
791 content/en/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v1.md
```

- [x] StatefulSet-v1  @yaolixin-creater  #34859

```
888 content/en/docs/reference/kubernetes-api/workload-resources/stateful-set-v1.md
```

- [x] HPA-v2  @zhangxyjlu   #35125

```
1357 content/en/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2.md
```

- [x] HPA-v2beta2   @zhangxyjlu   #35183

```
1343 content/en/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2beta2.md
```

- [x] PodTemplate-v1   @qlijin   #35395

```
583 content/en/docs/reference/kubernetes-api/workload-resources/pod-template-v1.md
```

- [x] Pod-v1  @ydFu  #35196

```
3340 content/en/docs/reference/kubernetes-api/workload-resources/pod-v1.md
```

- [x] ReplicationController-v1  @windsonsea   #34891

```     
805 content/en/docs/reference/kubernetes-api/workload-resources/replication-controller-v1.md
```

- [x] Deployment-v1   @windsonsea #34892

```
868 content/en/docs/reference/kubernetes-api/workload-resources/deployment-v1.md
```

- [x] CRD-v1   @zhangxyjlu   #34926

```
1161 content/en/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1.md
```

- [x] ValidatingWebhookConfiguration-v1   @yaolixin-creater  #34870

```
618 content/en/docs/reference/kubernetes-api/extend-resources/validating-webhook-configuration-v1.md
```

- [x] MutatingWebhookConfiguration-v1  @donghui21  #34991

```
628 content/en/docs/reference/kubernetes-api/extend-resources/mutating-webhook-configuration-v1.md
```

- [x] TokenRequest-v1  @windsonsea   #34741

```
185 content/en/docs/reference/kubernetes-api/authentication-resources/token-request-v1.md
```

- [x] FlowSchema-v1beta2  @windsonsea  #34806

```
800 content/en/docs/reference/kubernetes-api/cluster-resources/flow-schema-v1beta2.md
```

- [x] RuntimeClass-v1   @windsonsea   #34749

```
518 content/en/docs/reference/kubernetes-api/cluster-resources/runtime-class-v1.md
```

- [x] Node-v1  @yaolixin-creater   #34979

```
983 content/en/docs/reference/kubernetes-api/cluster-resources/node-v1.md
```

- [x] PriorityLevelConfiguration-v1beta2  @windsonsea  #34827

```
702 content/en/docs/reference/kubernetes-api/cluster-resources/priority-level-configuration-v1beta2.md
```

- [x] Event-v1  @syxunion   #34482

```
651 content/en/docs/reference/kubernetes-api/cluster-resources/event-v1.md
```

- [x] ComponentStatus-v1  @windsonsea   #34744

```
203 content/en/docs/reference/kubernetes-api/cluster-resources/component-status-v1.md
```

- [x] LimitRange-v1   @windsonsea   #34779

```
606 content/en/docs/reference/kubernetes-api/policy-resources/limit-range-v1.md
```

- [x] NetworkPolicy-v1   @gangchen03   #35105

```
909 content/en/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
```

- [x] PDB-v1   @yaolixin-creater  #34937 

```
828 content/en/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1.md
```

- [x] ResourceQuota-v1  @donghui12  #34933

```
783 content/en/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
```

- [x] PSP-v1beta1   @windsonsea   #34789

```
739 content/en/docs/reference/kubernetes-api/policy-resources/pod-security-policy-v1beta1.md
```

- [x] EndpointSlice-v1   @Michelle951   #34928 

```
666 content/en/docs/reference/kubernetes-api/service-resources/endpoint-slice-v1.md
```

- [x] Endpoints-v1  @shixiuguo  @windsonsea   #35601

```
657 content/en/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
```

- [x] IngressClass-v1 @qlijin     #34723

```
503 content/en/docs/reference/kubernetes-api/service-resources/ingress-class-v1.md
```

- [x] Service-v1   @donghui12   #34849

```
963 content/en/docs/reference/kubernetes-api/service-resources/service-v1.md
```

- [x] Ingress-v1   @shixiuguo @windsonsea  #35634

```
911 content/en/docs/reference/kubernetes-api/service-resources/ingress-v1.md
```

**Comment by windsonsea** [comment]
I would like to take `TokenRequest-v1` at a start :)

**Comment by ydFu** [comment]
I would like to take pod-v1.md.
/assign

**Comment by zhangxyjlu** [comment]
I would like to handle:
custom-resource-definition-v1

**Comment by Michelle951** [comment]
I would like to handle:

EndpointSlice-v1

/assign

**Comment by donghui12** [comment]
I would like to handle:
service-v1
/assign

**Comment by tengqm** [comment]
> I would like to handle: service-v1 /assign

@donghui12 Thanks for stepping out. Please be sure to check existing API reference translations before working on the new ones. There are quite some tricky issues to handle when translating API reference. Looking forward to your contribution.

**Comment by yaolixin-creater** [comment]
I would like to handle:
StatefulSet-v1
/assign

**Comment by donghui12** [comment]
I would like to handle:
ResourceQuota-v1
/assign

**Comment by sarazqy** [comment]
I would like to handle:
DaemonSet-v1
/assign

**Comment by yaolixin-creater** [comment]
I would like to handle:
ValidatingWebhookConfiguration-v1
/assign

**Comment by donghui12** [comment]
Please reciew @Michelle951 @ydFu

**Comment by gangchen03** [comment]
I would like to take:
NetworkPolicy-v1
/assign

**Comment by donghui12** [comment]
I would like to handle:
MutatingWebhookConfiguration-v1
/assign

**Comment by yaolixin-creater** [comment]
I would like to handle:
Node-v1
/assign

**Comment by zhangxyjlu** [comment]
I would like to handle:
 HPA-v2 ：horizontal-pod-autoscaler-v2.md
 HPA-v2beta2 ：horizontal-pod-autoscaler-v2beta2.md

**Comment by ydFu** [comment]
/reopen 

This issue is still in progress.

**Comment by tengqm** [comment]
/reopen
#34985 should not close this yet.

**Comment by mengjiao-liu** [comment]
We have completed all tasks!  🎉🎉🎉

**Comment by windsonsea** [comment]
🎉🎉🎉

**Comment by tengqm** [comment]
All tasks completed. Wonderful job, team!
