### ISSUE TITLE
Umbrella issue: Localizing the Kubernetes website into Russian

### ISSUE THREAD

**Issue by kirkonru** [kubernetes/website#37044]
# Kubernetes documentation - the Russian localization project

### Maintainers:

* [shurup](https://github.com/shurup)
* [kirkonru](https://github.com/kirkonru)

This Issue tracks the progress of the localization of the Kubernetes documentation in Russian.

## General workflow

* Choose the article you want to translate from the list below and comment in this issue that you are ready to work on it.
* Wait for a response from the localization team. Maintainers will assign the chosen file to you.
* [Fork](https://github.com/kubernetes/website/fork) the main branch of the kubernetes/website repo. 
* Translate the chosen English article.
* In your fork, create a corresponding Russian file (in `/content/ru/docs/…`) for the article you have translated. Make sure its name is the same as the original.
* Fill it with the translated text; keep the layout and code samples intact. Use single backticks (**`**) to call out code or a command within a sentence. 
* Create a PR named `[ru] Translation of /your/article.md`, add the `language/ru` label to it.
* Select `dev-1.25-ru.1` as the target branch.

## Points to remember
* Please use the word **localization** instead of **translation**.
* Make sure no one is translating the file.
* If you feel that the localization team takes too long to respond, feel free to @mention/ping the maintainers mentioned above.

## Useful links
* For more information on how to contribute, check out these [guidelines](https://kubernetes.io/docs/contribute/).
* Feel free to join the relevant Slack channels:
   - [Kubernetes](https://slack.k8s.io/);
   - [kubernetes-docs-ru](https://kubernetes.slack.com/messages/kubernetes-docs-ru); 
   - [sig-docs-localizations](https://kubernetes.slack.com/messages/sig-docs-localizations).
* Kubernetes Website Repository: [https://github.com/kubernetes/website](https://github.com/kubernetes/website)

# Files
🟢 - localization is complete; 
🟡 - localization is in progress; 
🟣 - file has been merged.

- [ ]  concepts/architecture/cgroups.md
- [ ]  concepts/architecture/cri.md
- [x]  🟢    concepts/cluster-administration/certificates.md
- [x]  🟢    concepts/cluster-administration/flow-control.md
- [x]  🟢    concepts/cluster-administration/logging.md
- [x]  🟢    concepts/cluster-administration/manage-deployment.md
- [x]  🟢    concepts/cluster-administration/networking.md
- [x]  🟢    concepts/cluster-administration/proxies.md
- [x]  🟢    concepts/cluster-administration/system-metrics.md
- [x]  🟢    concepts/cluster-administration/system-traces.md
- [x]  🟢    concepts/configuration/_index.md
- [x]  🟢    concepts/configuration/configmap.md
- [x]  🟢    concepts/configuration/manage-resources-containers.md
- [x]  🟢    concepts/configuration/organize-cluster-access-kubeconfig.md
- [x]  🟢    concepts/configuration/overview.md
- [x]  🟢    concepts/configuration/secret.md
- [x]  🟢    concepts/configuration/windows-resource-management.md
- [x]  🟢    concepts/containers/_index.md
- [x]  🟢    concepts/containers/container-environment.md
- [x]  🟢    concepts/containers/container-lifecycle-hooks.md
- [x]  🟢    concepts/containers/images.md
- [x]  🟢    concepts/containers/runtime-class.md
- [x]  🟡 **WIP**    concepts/extend-kubernetes/_index.md
- [x]  🟡 **WIP**    concepts/extend-kubernetes/operator.md
- [x]  🟡 **WIP**    concepts/extend-kubernetes/api-extension/_index.md
- [x]  🟡 **WIP**    concepts/extend-kubernetes/api-extension/apiserver-aggregation.md
- [x]  🟡 **WIP**    concepts/extend-kubernetes/api-extension/custom-resources.md
- [ ]  concepts/extend-kubernetes/compute-storage-net/_index.md
- [ ]  concepts/extend-kubernetes/compute-storage-net/device-plugins.md
- [ ]  concepts/extend-kubernetes/compute-storage-net/network-plugins.md
- [ ]  concepts/overview/working-with-objects/finalizers.md
- [ ]  concepts/overview/working-with-objects/owners-dependents.md
- [ ]  concepts/policy/_index.md
- [ ]  concepts/policy/limit-range.md
- [ ]  concepts/policy/node-resource-managers.md
- [ ]  concepts/policy/pid-limiting.md
- [ ]  concepts/policy/resource-quotas.md
- [ ]  concepts/scheduling-eviction/_index.md
- [ ]  concepts/scheduling-eviction/api-eviction.md
- [ ]  concepts/scheduling-eviction/assign-pod-node.md
- [ ]  concepts/scheduling-eviction/kube-scheduler.md
- [ ]  concepts/scheduling-eviction/node-pressure-eviction.md
- [ ]  concepts/scheduling-eviction/pod-overhead.md
- [ ]  concepts/scheduling-eviction/pod-priority-preemption.md
- [ ]  concepts/scheduling-eviction/resource-bin-packing.md
- [ ]  concepts/scheduling-eviction/scheduler-perf-tuning.md
- [ ]  concepts/scheduling-eviction/scheduling-framework.md
- [ ]  concepts/scheduling-eviction/taint-and-toleration.md
- [ ]  concepts/scheduling-eviction/topology-spread-constraints.md
- [ ]  concepts/security/_index.md
- [ ]  concepts/security/api-server-bypass-risks.md
- [ ]  concepts/security/controlling-access.md
- [ ]  concepts/security/multi-tenancy.md
- [ ]  concepts/security/overview.md
- [ ]  concepts/security/pod-security-admission.md
- [ ]  concepts/security/pod-security-policy.md
- [ ]  concepts/security/pod-security-standards.md
- [ ]  concepts/security/rbac-good-practices.md
- [ ]  concepts/security/security-checklist.md
- [ ]  concepts/security/windows-security.md
- [ ]  concepts/services-networking/_index.md
- [ ]  concepts/services-networking/connect-applications-service.md
- [ ]  concepts/services-networking/dns-pod-service.md
- [ ]  concepts/services-networking/dual-stack.md
- [ ]  concepts/services-networking/endpoint-slices.md
- [ ]  concepts/services-networking/ingress-controllers.md
- [ ]  concepts/services-networking/ingress.md
- [ ]  concepts/services-networking/network-policies.md
- [ ]  concepts/services-networking/service-topology.md
- [ ]  concepts/services-networking/service-traffic-policy.md
- [ ]  concepts/services-networking/service.md
- [ ]  concepts/services-networking/topology-aware-hints.md
- [ ]  concepts/services-networking/windows-networking.md
- [ ]  concepts/storage/_index.md
- [ ]  concepts/storage/dynamic-provisioning.md
- [ ]  concepts/storage/ephemeral-volumes.md
- [ ]  concepts/storage/persistent-volumes.md
- [ ]  concepts/storage/projected-volumes.md
- [ ]  concepts/storage/storage-capacity.md
- [ ]  concepts/storage/storage-classes.md
- [ ]  concepts/storage/storage-limits.md
- [ ]  concepts/storage/volume-health-monitoring.md
- [ ]  concepts/storage/volume-pvc-datasource.md
- [ ]  concepts/storage/volume-snapshot-classes.md
- [ ]  concepts/storage/volume-snapshots.md
- [ ]  concepts/storage/volumes.md
- [ ]  concepts/storage/windows-storage.md
- [ ]  concepts/windows/_index.md
- [ ]  concepts/windows/intro.md
- [ ]  concepts/windows/user-guide.md
- [ ]  concepts/workloads/_index.md
- [ ]  concepts/workloads/controllers/_index.md
- [ ]  concepts/workloads/controllers/cron-jobs.md
- [ ]  concepts/workloads/controllers/daemonset.md
- [ ]  concepts/workloads/controllers/deployment.md
- [ ]  concepts/workloads/controllers/job.md
- [ ]  concepts/workloads/controllers/replicaset.md
- [ ]  concepts/workloads/controllers/replicationcontroller.md
- [ ]  concepts/workloads/controllers/statefulset.md
- [ ]  concepts/workloads/controllers/ttlafterfinished.md
- [ ]  concepts/workloads/pods/_index.md
- [ ]  concepts/workloads/pods/disruptions.md
- [ ]  concepts/workloads/pods/downward-api.md
- [ ]  concepts/workloads/pods/ephemeral-containers.md
- [ ]  concepts/workloads/pods/init-containers.md
- [ ]  concepts/workloads/pods/pod-lifecycle.md
- [ ]  concepts/workloads/pods/user-namespaces.md

**Comment by shurup** [comment]
@kirkonru thank you for summing it all up! Let's also add PRs to the documents that are translated already but not merged yet, please. E.g.:

> * [x]   concepts/cluster-administration/networking.md — #36467
> * [x]   concepts/cluster-administration/proxies.md — #36783
> …

**Comment by shurup** [comment]
We've started with translating the missing pages; however, there are some problems with existing (already translated) pages as well.
* #37745 revealed that `concepts/_index.md` (and the first pages it leads to) is significantly outdated. Since it's a starting point for many users, I'd say these pages are more important than other files we have in our current todo list;
* looking at #35187 made me realise this article has room for improvement as well (hopefully, @Zhurik will handle that — we can mark him as WIP for now).

@kirkonru, reflect these thoughts in the **Files**, please.

**Comment by shurup** [comment]
This issue is an ongoing effort; thus, we don't want to make it stale.

/remove-lifecycle stale

**Comment by yungserge** [comment]
Hi gents! @shurup @kirkonru 
I could contribute to this issue, if help is still needed. 
I could start with concepts/workloads/_index.md unless you think the docs should be localized in the order provided above. Let me know. Thanks! :)

**Comment by shurup** [comment]
Hi @yungserge! Sure, there's still a lot to be done, and your help will be much appreciated!
@kirkonru, please confirm you haven't started working on `concepts/workloads/_index.md` yet so Sergey can proceed with this page.

**Comment by kirkonru** [comment]
Hi @yungserge! No work has begun on `concepts/workloads/_index.md`, so feel free to localize it. Please let me know when you are ready to proceed - I'll label the page as a WIP. The [Documentation Style Guide](https://kubernetes.io/docs/contribute/style/style-guide/) might come in handy (Russian version is also available, but I'm not sure how up to date it is).

**Comment by yungserge** [comment]
@kirkonru I've already started, you can label it as WIP. Thanks, the [Documentation Style Guide](https://kubernetes.io/docs/contribute/style/style-guide/) is helpful

**Comment by yungserge** [comment]
Hey guys! @shurup @kirkonru  I am ready to submit the PR but it says to "Select dev-1.25-ru.1 as the target branch." and I do not see this one in the repo. Should I just select the main branch?

**Comment by shurup** [comment]
@yungserge right, mentioning the v1.25 branch there is outdated. You can use main instead.

**Comment by yungserge** [comment]
@kirkonru  I can start with the next one: concepts/workloads/controllers/_index.md

**Comment by kirkonru** [comment]
@yungserge Great! Got it assigned to you.

**Comment by yungserge** [comment]
I can start working on concepts/workloads/controllers/cron-jobs.md while waiting for feedback on #44009.

**Comment by shurup** [comment]
Hi @yungserge, that's awesome! Please feel free to keep going with the whole `concepts/workloads` part, as we are unaware of anyone else handling it ATM.

**Comment by yungserge** [comment]
Hi @shurup, could you take a look at #44009? I am ready to submit the next document, and I wanted to get feedback on the current PR before I do so :)

**Comment by shurup** [comment]
Hi @yungserge! I will surely do that. Sorry for the delay on my side due to a vacation and Christmas holidays. Hopefully, I'll get back to reviewing it next week.

**Comment by yungserge** [comment]
@shurup No problem, just when you get a chance. Thank you!

**Comment by catinbag** [comment]
Hi @shurup, @kirkonru 👋 
I can help with translating the Pods page

**Comment by aprasolova** [comment]
Hi localization team! 

I'd like to contribute. 

I might localize the page `concepts/extend-kubernetes/operator.md`, or any other which you propose.

**Comment by shurup** [comment]
Hi @aprasolova, you are most welcome! Actually, we have so many pages still lacking translation that you're free to choose any of them, and it will surely be beneficial. The `operator.md` page might be a good start since it is not too big. Feel free to reach me whenever you have any questions about moving forward 🙏

**Comment by banlor** [comment]
hi @shurup @kirkonru - opened a PR for concepts/security/linux-security.md: kubernetes/website#55710. flag if you'd prefer the assign-first workflow next time.
