### ISSUE TITLE
Umbrella issue: Improvements to draft-translate.py script

### ISSUE THREAD

**Issue by a-mccarthy** [kubernetes/website#37954]
**This is a Feature Request**

Continuing the excellent work done for https://github.com/kubernetes/website/issues/36879 by @bart2001, we should consider the making improvements for the draft translation script being added by https://github.com/kubernetes/website/pull/37254. (The PR for adding the script is still being reviewed and waiting to be merged.)

The current version of this script is not considered GA. The purpose of this issue is to keep track of improvements we'd like to see for this script before it can be considered GA or ready for large scale use by localization teams. It's available for use by any localization team, but before using it teams should understand the potential drawbacks.  Namely that the script is not the final step for translation work. It can provide a basic translation of a file's content, but the content still need to be reviewed and edited by a human to make sure the meaning, context, and word choice is correct in the translated content. 

**Where this script is useful:** 

It's recommended that the current form of the script is used for the first pass translation of a page from the original EN to the target language. It may prove less useful for translating parts of a file that has changed in EN if it's already been translated into the target language, b/c the script in its current form translates the whole file. You currently aren't able to only translate sections of files. 

This script is also useful for preserving the formatting of the EN file to the target language file. This will keep line numbers and line breaks the same so it is easier to do future translation work. If the EN file changes and the basic formatting is the same in the translated versions, it will be easier to find the place where to update the translated content.  

**What would you like to be added**

Improvements needed for GA

- [ ] Use an official supported library. The current script uses https://github.com/ssut/py-googletrans to do the translation work. This is not an official library and does not have any guarantees of long term support/availability. See https://github.com/ssut/py-googletrans#note-on-library-usage for more info. 
- [ ] Add bulk file translation. Right now the script only supports translated a single file at a time.
- [ ] Make it possible for the script to skip words that a localization team has decided not to localize. Some words are not translated for every language. There should be a configureable way for teams to skip words that should not be translated. For example, https://github.com/kubernetes/website/pull/37254#issuecomment-1305821773

Nice to have improvements 
- [ ] Translate only parts of a file. The script in its current form translates the whole file. We should see if its possible to only translate parts of a file. 

**Comments**

**Comment by a-mccarthy** [comment]
@bart2001 I've created this umbrella issue based on your great demo and the discussion on using the script for the last localization meeting. Please review it and let me know if i've captured everything correctly or if you have any other improvement that you are thinking about adding. (i didn't see another issue covering this topic, but if there is one already please feel free to close this :) 

I was thinking that we could use this issue as a place to track the work needed for improving the script and we can create issues for each item as needed to do work or have further discussion.

**Comment by seokho-son** [comment]
Hi @a-mccarthy 

https://github.com/kubernetes/website/pull/37254 that implements a draft-translation tool closed.
I hope to check and discuss how to continue this issue. :)
