### ISSUE TITLE
Umbrella issue for Netlify access amendments

### ISSUE THREAD

**Issue by divya-mohan0209** [kubernetes/website#38839]
### Discussed in [k/website discussion](https://github.com/kubernetes/website/discussions/38019) and [RT 1.26 retro](https://docs.google.com/document/d/11Oa-L76z8Y1wYufdm1wEV87NUJm1nzQ4b12k6UQY3t8/edit#heading=h.ukbaidczvy3r)

- One member from CNCF's Dev Advocate/Tech writer team to have access to K8s Netlify
- Netlify access cleanup for emeritus co-chairs/tech leads
- Netlify access cleanup for other non-Docs accounts
- RT Docs lead Netlify access

Proposal: 

- [x] Since no sub-teams within Netlify give elevated privileges, the CNCF Dev Advocate/Tech Writer will be added individually as a collaborator. 

- [x] #41199

- [x]  Separate onboarding and offboarding documentation for co-chairs & leads to be created toward including this access.

~~- [ ] For non-docs accounts, for example, RT Docs, Emeritus Steering, etc., access is to be removed after consultation with SIG Contribex.~~

- [x] Per [Netlify documentation](https://docs.netlify.com/accounts-and-billing/team-management/team-member-roles/), a collaborator role allows the actions required for the Release team Docs lead to perform the necessary actions on a release without causing any damage. If in agreement, document explicitly in the [role handbook](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#update-the-site-configuration-files-for-previous-releases) to seek Netlify collaborator access from the Docs leads.

- [x] Document in k/community whoever has owner access to Netlify.

Edit: Raised an issue with SIG Contribex for non-docs accounts under [this issue](https://github.com/kubernetes/community/issues/7311). We will be following up further on the issue and in Slack.

**Comment by palnabarun** [comment]
+1 on the overall cleanup.

---

(With the hat of a GitHub Admin)

Would our access be removed? Asking since we get requests to enable subproject sites (*.sigs.k8s.io) on kubernetes/org and we handle those requests.

**Comment by palnabarun** [comment]
On that note, can a list be maintained in k/community on who has Owner access to Netlify? This can keep the membership transparent to everyone.

**Comment by divya-mohan0209** [comment]
> +1 on the overall cleanup.
> 
> (With the hat of a GitHub Admin)
> 
> Would our access be removed? Asking since we get requests to enable subproject sites (*.sigs.k8s.io) on kubernetes/org and we handle those requests.

Nope. For the current cleanup, we'll be manually cross-checking and figuring out the retention. But the aim is to have an updated Netlify members list by end of Q1 (hopefully) & a way to, potentially, automate it.

**Comment by divya-mohan0209** [comment]
> On that note, can a list be maintained in k/community on who has Owner access to Netlify? This can keep the membership transparent to everyone.

Agreed!

**Comment by a-mccarthy** [comment]
+1 to moving forward with this. @chalin and @nate-double-u have both raised Netlify access as issues/blockers for ongoing CNCF projects, like out Google analytics 4 migration (issue: https://github.com/kubernetes/website/issues/35299).

**Comment by divya-mohan0209** [comment]
Amending the description format to a checklist of items that will be completed after the consensus date i.e. February 8th.

**Comment by nate-double-u** [comment]
> One member from CNCF's Dev Advocate/Tech writer team to have access to K8s Netlify

Is it too late to ask for 2 members from CNCF's Dev Advocate/Tech writer team to have access? Would be good for vacation coverage and whatnot.

**Comment by divya-mohan0209** [comment]
Closing this issue off as the audit work + associated documentation for SIG Docs has been completed. For non-docs accounts on Netlify, we have raised it with SIG Contribex and will be following it up there.

/close
