### ISSUE TITLE
[zh-cn][Umbrella] Remove or mark all references to k8s.gcr.io

### ISSUE THREAD

**Issue by mengjiao-liu** [kubernetes/website#39417]
This issue is under the umbrella of https://github.com/kubernetes/website/issues/39353

> for each downstream localization, find any mentions of k8s.gcr.io update to be level with the English version of pages

You can use the following command to find the file that still has content `k8s.gcr.io` and resync:
```bash
$ grep -r "k8s.gcr.io" ./content/zh-cn/*
$ ./scripts/lsync.sh <file>
```

- [x] ./content/zh-cn/blog/_posts/2022-05-13-grpc-probes-in-beta.md https://github.com/kubernetes/website/pull/39420
- [x] ./content/zh-cn/blog/_posts/2022-05-27-maxunavailable-for-statefulset.md https://github.com/kubernetes/website/pull/39421
- [x] ./content/zh-cn/docs/tasks/debug/debug-application/debug-running-pod.md #39419
- [x] ./content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_scheduler.md #39560
- [x] ./content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon_all.md #39592
- [x] ./content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md #39646
- [x] ./content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_controller-manager.md #39646

**Comment by mengjiao-liu** [comment]
If anyone else wants to work here, please let me know so I can track it.

**Comment by devarsh10** [comment]
Hey @mengjiao-liu, I found some file which are still following `k8s.gcr.io` registry.
Can you guide me what should be my further steps?

Regards.

**Comment by mengjiao-liu** [comment]
This is about the synchronization of Chinese content. Although there is no translation of Chinese content this time, I hope you didn't misread the synchronized language. @devarsh10 

You may find the scripts/lsync.sh tool useful. For example, run the following command on the main branch:
```
./scripts/lsync.sh ./content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_scheduler.md
```
It will show you the changes to the upstream English source since the last time that page was sync'ed (or translated).Basically, those changes are the lines we need to resync to Chinese.

**Comment by devarsh10** [comment]
Okay. I may misread as I'm less aware of Chinese.
Thank you for the reply.
Regards

**Comment by mengjiao-liu** [comment]
All tasks were done.
/close
