### ISSUE TITLE
[zh-cn][Umbrella]Concept files to sync for 1.26 

### ISSUE THREAD

**Issue by howieyuen** [kubernetes/website#39985]
Numbers in the following list may be not up to date. Please run ./scripts/lsync.sh again before working on each of them.

- [x] task-1 @asa3311  
- https://github.com/kubernetes/website/pull/39997 
- https://github.com/kubernetes/website/pull/40007
```
1	1	content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
4	3	content/en/docs/concepts/scheduling-eviction/pod-priority-preemption.md
```

- [ ] task-2 @howieyuen https://github.com/kubernetes/website/pull/40083
```
158	159	content/en/docs/concepts/storage/storage-classes.md
```

- [x] task-3 @asa3311 https://github.com/kubernetes/website/pull/40016
```
3	3	content/en/docs/concepts/storage/persistent-volumes.md
2	2	content/en/docs/concepts/services-networking/endpoint-slices.md
1	1	content/en/docs/concepts/services-networking/topology-aware-hints.md
```

- [x] task-4 @howieyuen https://github.com/kubernetes/website/pull/40046
```
1	1	content/en/docs/concepts/workloads/pods/user-namespaces.md
2	2	content/en/docs/concepts/workloads/pods/_index.md
1	1	content/en/docs/concepts/workloads/controllers/cron-jobs.md
1	1	content/en/docs/concepts/workloads/controllers/job.md
1	1	content/en/docs/concepts/workloads/_index.md
```

- [x] task-5 @howieyuen https://github.com/kubernetes/website/pull/40045
```
2	0	content/en/docs/concepts/architecture/cgroups.md
2	2	content/en/docs/concepts/windows/intro.md
1	1	content/en/docs/concepts/cluster-administration/addons.md
```

**Comment by asa3311** [comment]
I want to try

/assign

**Comment by howieyuen** [comment]
I am taking task-4 and task-5

**Comment by ydFu** [comment]
@asa3311 @howieyuen 
All tasks have been completed and merged. Thanks for your contribution, and we have successfully resolved this issue together.

/close
