### ISSUE TITLE
[zh-cn][Umbrella]Reference files to sync for 1.26 

### ISSUE THREAD

**Issue by howieyuen** [kubernetes/website#39987]
Numbers in the following list may be not up to date. Please run `./scripts/lsync.sh` again before working on each of them.

- [x] task-1 @asa3311 https://github.com/kubernetes/website/pull/40077
```
1	1	content/en/docs/reference/kubernetes-api/authorization-resources/cluster-role-binding-v1.md
1	1	content/en/docs/reference/kubernetes-api/authorization-resources/role-binding-v1.md
1	1	content/en/docs/reference/kubernetes-api/authorization-resources/role-v1.md
1	1	content/en/docs/reference/kubernetes-api/authorization-resources/cluster-role-v1.md
1	1	content/en/docs/reference/kubernetes-api/workload-resources/replica-set-v1.md
1	1	content/en/docs/reference/kubernetes-api/workload-resources/replication-controller-v1.md
1	1	content/en/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
```

- [x] task-2 @asa3311 https://github.com/kubernetes/website/pull/40141
```
8	0	content/en/docs/reference/kubernetes-api/extend-resources/validating-webhook-configuration-v1.md
1	1	content/en/docs/reference/kubernetes-api/authentication-resources/token-request-v1.md
**removed**	content/en/docs/reference/kubernetes-api/cluster-resources/flow-schema-v1beta2.md
**removed**	content/en/docs/reference/kubernetes-api/cluster-resources/priority-level-configuration-v1beta2.md
1	1	content/en/docs/reference/kubernetes-api/_index.md
```

- [x] task-3 @asa3311 https://github.com/kubernetes/website/pull/40157
```
6	6	content/en/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
2	2	content/en/docs/reference/kubernetes-api/service-resources/endpoint-slice-v1.md
3	3	content/en/docs/reference/kubernetes-api/service-resources/service-v1.md
1	1	content/en/docs/reference/kubernetes-api/common-parameters/common-parameters.md

```

- [x] task-4 @my-git9 https://github.com/kubernetes/website/pull/40111
```
100	4	content/en/docs/reference/kubernetes-api/workload-resources/pod-v1.md
```

- [x] task-5 @windsonsea https://github.com/kubernetes/website/pull/40035
```
127	6	content/en/docs/reference/labels-annotations-taints/_index.md
```

- [x] task-6 @fenggw-fnst 
https://github.com/kubernetes/website/pull/40153
https://github.com/kubernetes/website/pull/40151
```
1	1	content/en/docs/reference/labels-annotations-taints/audit-annotations.md
1	0	content/en/docs/reference/tools/map-crictl-dockercli.md
1	1	content/en/docs/reference/tools/_index.md
1	0	content/en/docs/reference/scheduling/policies.md
1	1	content/en/docs/reference/scheduling/_index.md
19	10	content/en/docs/reference/networking/virtual-ips.md
0	5	content/en/docs/reference/networking/service-protocols.md
```

- [x] task-7  @fenggw-fnst   #40284
```
143	144	content/en/docs/reference/config-api/kubeadm-config.v1beta3.md
```

- [x] task-8 @asa3311 https://github.com/kubernetes/website/pull/40172
```
1	1	content/en/docs/reference/config-api/apiserver-webhookadmission.v1.md
1	1	content/en/docs/reference/config-api/kubelet-credentialprovider.v1alpha1.md
1	1	content/en/docs/reference/config-api/kubelet-credentialprovider.v1beta1.md
1	1	content/en/docs/reference/config-api/apiserver-config.v1alpha1.md
1	1	content/en/docs/reference/config-api/apiserver-config.v1.md
1	2	content/en/docs/reference/config-api/_index.md
4	10	content/en/docs/reference/instrumentation/node-metrics.md
```

- [x] task-9 @asa3311 https://github.com/kubernetes/website/pull/40205
```
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_list.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_etcd.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_kubelet-start.md
11	3	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_etcd.md
```

- [x] task-10  @fenggw-fnst  #40240
```
11	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-config_kubeadm.md
11	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-config_all.md
7	0	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-config_kubelet.md
14	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_certs.md
```

- [x] task-11 @yulng https://github.com/kubernetes/website/pull/40182
```
4	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_version.md
2	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_create.md
4	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_token.md
11	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_preflight.md
```

- [x] task-12  @yulng #40218 
```
4	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join.md
4	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_delete.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs.md
4	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare.md
```

- [x] task-13  @asa3311 https://github.com/kubernetes/website/pull/40219
```
13	3	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_all.md
4	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_diff.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade.md
7	0	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubelet-start.md
```

- [x] task-14  @asa3311 #40236
```
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
4	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_etcd-peer.md
4	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_etcd-healthcheck-client.md
4	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase.md
5	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node.md
```

- [x] task-15 @asa3311 #40238 
```
4	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_etcd-server.md
4	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md
4	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_sa.md
4	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_apiserver.md
```

- [x] task-16  @yulng https://github.com/kubernetes/website/pull/40244
```
7	0	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubelet-finalize_all.md
4	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_join-defaults.md
4	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon.md
11	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset.md
11	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-ca.md
```

- [x] task-17  @asa3311 #40239
```
13	3	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_all.md
11	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_all.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_admin.conf.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-healthcheck-client.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_check-expiration.md
```

- [x] task-18  @asa3311 https://github.com/kubernetes/website/pull/40248
```
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew.md
2	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_kubeconfig_user.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-config.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_ca.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
```

- [x] task-19  @yulng #40268
```
4	0	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-kubelet-client.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_controller-manager.conf.md
2	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_control-plane.md
7	0	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubelet-finalize_experimental-cert-rotation.md
```

- [x] task-20 @asa3311  https://github.com/kubernetes/website/pull/40251
```
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_generate.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_bootstrap-token.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-peer.md
```

- [x] task-21 @asa3311 https://github.com/kubernetes/website/pull/40253
```
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_plan.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_apiserver-etcd-client.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_scheduler.conf.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_kubeconfig.md
```

- [x] task-22 @asa3311 https://github.com/kubernetes/website/pull/40258
```
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_all.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_scheduler.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_preflight.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_all.md
9	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_mark-control-plane.md
```

- [x] task-23 @asa3311 https://github.com/kubernetes/website/pull/40262
```
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_admin.md
10	3	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_control-plane.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon_coredns.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_front-proxy-ca.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver.md
```

- [x] task-24 @fenggw-fnst https://github.com/kubernetes/website/pull/40260
```
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_apply.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_mark-control-plane.md
9	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_download-certs.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_apiserver-kubelet-client.md
```

- [x] task-25 @fenggw-fnst https://github.com/kubernetes/website/pull/40257
```
7	0	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_etcd_local.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_completion.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_migrate.md
```

- [x] task-26 @fenggw-fnst https://github.com/kubernetes/website/pull/40255
```
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase.md
2	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_update-status.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-etcd-client.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_front-proxy-client.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_front-proxy-client.md
```

- [x] task-27 @fenggw-fnst  https://github.com/kubernetes/website/pull/40254
```
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_certificate-key.md
7	0	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon_kube-proxy.md
9	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_preflight.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_controller-manager.md
```

- [x] task-28 @fenggw-fnst  https://github.com/kubernetes/website/pull/40252
```
9	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_kubeconfig.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_kubelet.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_init-defaults.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md
8	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-server.md
1	1	content/en/docs/reference/setup-tools/_index.md
```

- [x] task-29 @windsonsea 
https://github.com/kubernetes/website/pull/40139
https://github.com/kubernetes/website/pull/40171
https://github.com/kubernetes/website/pull/40173
https://github.com/kubernetes/website/pull/40186
```
19	26	content/en/docs/reference/command-line-tools-reference/kube-apiserver.md
10	10	content/en/docs/reference/command-line-tools-reference/kube-controller-manager.md
18	18	content/en/docs/reference/command-line-tools-reference/kube-proxy.md
1	0	content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
```

- [x] task-30 @my-git9 https://github.com/kubernetes/website/pull/40108
```
86	149	content/en/docs/reference/command-line-tools-reference/kubelet.md
```

- [x] task-31  @fenggw-fnst #40246 https://github.com/kubernetes/website/pull/40247
```
5	5	content/en/docs/reference/command-line-tools-reference/kube-scheduler.md
1	1	content/en/docs/reference/command-line-tools-reference/_index.md
1	1	content/en/docs/reference/glossary/kubectl.md
1	1	content/en/docs/reference/glossary/qos-class.md
1	1	content/en/docs/reference/glossary/kubeadm.md
```

- [x] task-32  @fenggw-fnst #40242
```
1	0	content/en/docs/reference/node/topics-on-dockershim-and-cri-compatible-runtimes.md
1	1	content/en/docs/reference/node/_index.md
1	1	content/en/docs/reference/issues-security/_index.md
1	0	content/en/docs/reference/kubectl/conventions.md
1	0	content/en/docs/reference/kubectl/jsonpath.md
1	0	content/en/docs/reference/_index.md
1	1	content/en/docs/reference/access-authn-authz/admission-controllers.md
```

**Comment by windsonsea** [comment]
I would like to handle `task-5`:
```
127	6	content/en/docs/reference/labels-annotations-taints/_index.md
```

**Comment by asa3311** [comment]
> I would like to handle `task-7`:
content/en/docs/reference/config-api/kubeadm-config.v1beta3.md

**Comment by asa3311** [comment]
I would like to handle task-2:

**Comment by howieyuen** [comment]
> I would like to handle task-2:

I have say, wow! you are on fire!!!

**Comment by my-git9** [comment]
I would like to handle task-30
```
86	149	content/en/docs/reference/command-line-tools-reference/kubelet.md
```

**Comment by my-git9** [comment]
I would like to handle task-4
```
100	4	content/en/docs/reference/kubernetes-api/workload-resources/pod-v1.md
```

**Comment by my-git9** [comment]
I would like to handle task-4
```
100	4	content/en/docs/reference/kubernetes-api/workload-resources/pod-v1.md
```

**Comment by windsonsea** [comment]
I would like to handle `task-29`

/assign

**Comment by asa3311** [comment]
I would like to handle task-3;

**Comment by fenggw-fnst** [comment]
I would like to take task-6.

**Comment by asa3311** [comment]
I would like to take task-8.

**Comment by asa3311** [comment]
I would like to take task-9.

**Comment by fenggw-fnst** [comment]
Then I would like to take task-10.

**Comment by yulng** [comment]
I would like to take task-10.

**Comment by yulng** [comment]
I would like to take task-12.

**Comment by asa3311** [comment]
I would like to take task-13.

**Comment by yulng** [comment]
I would like to take task-16.

**Comment by asa3311** [comment]
I would like to take task-14.

**Comment by asa3311** [comment]
I would like to take task-15.

**Comment by asa3311** [comment]
I would like to take task-17.

**Comment by asa3311** [comment]
I would like to take task-18.

**Comment by fenggw-fnst** [comment]
I would like to take task-32.

**Comment by fenggw-fnst** [comment]
I would like to take task-31.

**Comment by yulng** [comment]
I would like to take task-19.

**Comment by fenggw-fnst** [comment]
I would like to take task-28.

**Comment by asa3311** [comment]
I would like to take task-20.

**Comment by asa3311** [comment]
I would like to take task-21.

**Comment by fenggw-fnst** [comment]
I would like to take task-27.

**Comment by fenggw-fnst** [comment]
I would like to take task-26.

**Comment by fenggw-fnst** [comment]
I would like to take task-25.

**Comment by asa3311** [comment]
I would like to take task-23.

**Comment by fenggw-fnst** [comment]
I would like to take task-7, the last one.

**Comment by howieyuen** [comment]
Congratulations! We have finished all tasks! Thanks to everybody!!!
