### ISSUE TITLE
[zh-cn][Umbrella] Files to sync for 1.26

### ISSUE THREAD

**Issue by howieyuen** [kubernetes/website#39988]
```[tasklist]
### Tasks
- [x] task files: https://github.com/kubernetes/website/issues/39983
- [x] contribute files: https://github.com/kubernetes/website/issues/39984
- [x] concept files: https://github.com/kubernetes/website/issues/39985
- [x] tutorial files: https://github.com/kubernetes/website/issues/39986
- [ ] reference files: https://github.com/kubernetes/website/issues/39987
```

**Comment by howieyuen** [comment]
cc @chenrui333 @chenxuc @my-git9 @kinzhi @mengjiao-liu @SataQiu @Sea-n @tanjunchen @tengqm @windsonsea @xichengliudui

**Comment by howieyuen** [comment]
Congratulations! We have finished all tasks, thanks to everybody!
