### ISSUE TITLE
Add version metadata to feature gates

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#44357]
**This is a Feature Request**

**What would you like to be added**
The [feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) page is generated from lots of small Markdown files. We have a [demo](https://github.com/kubernetes/website/pull/43491) of how we can add metadata to the [front matter](https://gohugo.io/content-management/front-matter/) of each page.

This issue is about two things:
- setting version metadata in the front matter of those Markdown files
- adding some [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) validation to fail a website build if the version metadata is present but invalid

**Why is this needed**
We want to automate the process of updating feature gate information. It's very common to move features from alpha to beta and we want to make it easy for contributors to do that. However, it's a big change to make all in one go.

So, this issue is an incremental improvement. We get to set version metadata and make sure it's not obviously wrong, and we end up closer to the point where we can build on this. The demo in PR https://github.com/kubernetes/website/pull/43491 shows only one possibility.

People have had other ideas; for example, we could change our `feature-state` shortcode so that it loads the feature state based on the metadata we have for a feature gate.
If you want to implement your own idea, and especially if you can do that change without updating every feature gate we list, then you would be welcome to.

**Comments**
/area web-development

If you pick this up, you can choose one of two approaches:
1. add the validation code and set the version metadata for _some_ feature gates
   - for example, you could add it just to the feature gates that have already been removed
   - for example, you could add it just to the feature gates that begin with the letter `A`
   - that leaves work for other contributors to do in a future PR, and helps keep your change small
1. add the validation code and set the version metadata for _all_ feature gates

Anyone is welcome to work on this. It is not particularly beginner friendly, so if you want to help here and haven't already worked on a web development issue in this repository, you might like to pick up a simpler web development issue first and then return to this one.

---

## Subtasks

If you want to work on just a portion of this, open a draft PR that covers one of these subtasks, and mention #44357 in the PR description. The PR title should match:
> Set version metadata for feature gates that start with ?

(change ? to the letter of the alphabet that you are working on)

```[tasklist]
### Tasks (check off only when done and merged)
- [ ] `feature-gates/a*.md`
- [ ] `feature-gates/b*.md`
- [ ] `feature-gates/c*.md`
- [ ] `feature-gates/d*.md`
- [ ] `feature-gates/e*.md`
- [ ] `feature-gates/g*.md`
- [ ] `feature-gates/h*.md`
- [ ] `feature-gates/i*.md`
- [ ] `feature-gates/j*.md`
- [ ] `feature-gates/k*.md`
- [ ] `feature-gates/l*.md`
- [ ] `feature-gates/m*.md`
- [ ] `feature-gates/n*.md`
- [ ] `feature-gates/o*.md`
- [ ] `feature-gates/p*.md`
- [ ] `feature-gates/q*.md`
- [ ] `feature-gates/r*.md`
- [ ] `feature-gates/s*.md`
- [ ] `feature-gates/t*.md`
- [ ] `feature-gates/u*.md`
- [ ] `feature-gates/v*.md`
- [ ] `feature-gates/w*.md`
```

**Comment by sftim** [comment]
/priority backlog
/triage accepted

We'd like to do this, but it's not our top priority.

**Comment by sftim** [comment]
We could split this up into subtasks that people could claim.

**Comment by sftim** [comment]
This is done
/close

**Comment by sftim** [comment]
I wonder if we can do something around automatically comparing against https://github.com/kubernetes/kubernetes/blob/master/test/featuregates_linter/test_data/unversioned_feature_list.yaml
