### ISSUE TITLE
[bn] We need to localize some content and make necessary adjustments before launching in Bengali.

### ISSUE THREAD

**Issue by asem-hamid** [kubernetes/website#44993]
<h1> What is this issue for?</h1> 

### Here, we are Localizing the Kubernetes website to make it available in Bengali.

<h1>How can I contribute?</h1>

All the information you need is covered  in this [video.](https://youtu.be/zlHNWVQwAj0)
For more information join us on [slack](https://kubernetes.slack.com/messages/kubernetes-docs-bn)

<h1> Checklist to translate a term</h1>

1. Check that no one else has claimed the page in the comments below.
2. Comment below the page that you would like to localize, focus on one page per PR, at a time.
   Example: `I  am working on content/bn/<xyz.md>`
4. Maintainers will add your username next to your selected page in the below checklist.
5. Fork this repo, make your localizations, and submit a pull request following the name convention [bn]  Localization of <file_name.md>.
  Example: `[bn] Localization of cloud_native_apps.md`
6. Target branch dev-1.24-bn.1 when creating the PR
7. tag/ping a maintainer to make it easier to track progress
8. Also, when you create a PR, please make sure to add these  line in the description.

   `Resolves : #44993 `

<h1> Minimum required content before go live in bn </h1>

```[tasklist]
### Concepts
- [x] `content/en/docs/_index.md`  @asem-hamid
- [x] `content/en/docs/concepts/_index.md` @asem-hamid
- [x] `content/en/docs/concepts/architecture/_index.md` @asem-hamid
- [x] `content/en/docs/concepts/containers/_index.md` @asem-hamid
- [x] `content/en/docs/concepts/cluster-administration/_index.md` @sajjadrahman56
- [x] `content/en/docs/concepts/configuration/_index.md` @azaynul10
- [x] `content/en/docs/concepts/overview/_index.md` @sajibAdhi
- [x] `content/en/docs/concepts/overview/working-with-objects/_index.md` @cloudwithtanvir
- [x] `content/en/docs/concepts/policy/_index.md` @sajjadrahman56
- [x] `content/en/docs/concepts/scheduling-eviction/_index.md` @azaynul10
- [x] `content/en/docs/concepts/security/_index.md` @itsPronay
- [x] `content/en/docs/concepts/services-networking/_index.md` @asem-hamid
- [x] `content/en/docs/concepts/storage/_index.md` @asem-hamid
- [x] `content/en/docs/concepts/windows/_index.md` @sajjadrahman56
- [x] `content/en/docs/concepts/workloads/_index.md` @asem-hamid
- [x] `content/en/docs/concepts/workloads/controllers/_index.md` @asem-hamid
- [x] `content/en/docs/concepts/workloads/pods/_index.md` @sajjadrahman56
- [x] `content/en/docs/concepts/extend-kubernetes/_index.md` @asem-hamid
- [x] `content/en/docs/concepts/extend-kubernetes/api-extension/_index.md` @asem-hamid
- [x] `content/en/docs/concepts/extend-kubernetes/compute-storage-net/_index.md` @asem-hamid
```

```[tasklist]
### Tasks
- [x] `included/optional-kubectl-configs-pwsh.md` @asem-hamid
- [x] `docs/tasks/tools/included/optional-kubectl-configs-fish.md` @asem-hamid
- [x] update `docs/tasks /_index.md` @asem-hamid
```

```[tasklist]
### Releases
- [x] `content/bn/releases/notes.md` @asem-hamid
- [x] `content/bn/releases/download.md` @asem-hamid
- [x] `content/bn/releases/version-skew-policy.md` @sajjadrahman56
- [x] `content/bn/releases/patch-releases.md` @itsPronay
- [x] `content/bn/releases/release.md` @radiumSodium
- [x] `content/bn/releases/release-managers.md` @itsPronay
```

```[tasklist]
### Releases -  Update
- [x] update `content/bn/releases/_index.md` @saifulshark
```

```[tasklist]
### includes
- [x] `default-storage-class-prereqs.md` @asem-hamid
- [x] `federation-deprecation-warning-note.md` @itsPronay
- [x] `index.md` @itsPronay
- [x] `task-tutorial-prereqs-node-upgrade.md`  @asem-hamid
- [x] `user-guide-content-moved.md` @asem-hamid
```

```[tasklist]
### Tutorials
- [x] `content/en/docs/tutorials/configuration/_index.md` @asem-hamid
- [x] `content/en/docs/tutorials/security/_index.md` @asem-hamid
- [x] `content/en/docs/tutorials/stateful-application/_index.md` @asem-hamid
- [x] `content/en/docs/tutorials/stateless-application/_index.md` @asem-hamid
- [x] `content/en/docs/tutorials/services/_index.md` @asem-hamid
```

```[tasklist]
### Setup
- [x] `content/en/docs/setup/production-environment/tools/_index.md` @sajibAdhi
- [x] `content/en/docs/setup/production-environment/tools/kubeadm/_index.md` @azaynul10
```

```[tasklist]
### Setup -  Update
- [x] update `content/bn/docs/setup/production-environment/_index.md` @sajibAdhi
- [x] update `content/bn/docs/setup/_index.md` @azaynul10
- [x] update `content/bn/docs/setup/production-environment/turnkey-solutions.md` @azaynul10
```

```[tasklist]
### More
- [x] `content/en/community/_index.html` @asem-hamid
- [x] `content/en/community/code-of-conduct.md` @asem-hamid
- [x] update `readme-bn.md` @asem-hamid
- [x] update `bn/docs/contribute /_index.md` @asem-hamid
- [x] update `bn/docs/home /_index.md` @asem-hamid
- [x] update `bn/docs/home /supported-doc-versions.md` @asem-hamid
- [x] `content/bn/_common-resources/index.md` @asem-hamid
- [x] `content/en/training /_index.html` @asem-hamid
- [x] `content/en/blog/_index.md` @azaynul10
- [x] `content/en/partners/_index.html` @itsPronay
- [x] `content/en/partners/_index.html` @asem-hamid (completed in this [PR](https://github.com/kubernetes/website/pull/46186))
- [x] update `content/bn/docs/reference/_index.md` @asem-hamid
- [x] `content/en/search.md` @sajjadrahman56
- [x] `data/i18n/bn/bn.toml` @asem-hamid
- [x] add files at `content/bn/case-studies` @Nafisa-Tabassum-Mim
- [x] add files at `content/bn/examples` @SAShameem
- [x] add `docs /images/` @asem-hamid
- [x] `Blog - 2023-12-18-read-write-once-pod-access-mode-ga.md` @asem-hamid
```

<h2> Glossary  </h2>

We have a total of 146 glossary terms to localize into Bangla. You can find them in this [issue](https://github.com/kubernetes/website/issues/45729)

### Related issue :
1. #45009 
2. #31677
3. #45729

**Comment by sftim** [comment]
Files I'd expect to see on the Bengali branch:
- `content/bn/_index.html`
- `content/bn/case-studies/_index.md`
- **and more**

See https://kubernetes.io/docs/contribute/localization/#minimum-required-content

**Comment by sftim** [comment]
What other files need to be localized, or updated, in order for the localization to go live? (would someone like to help compile the list?)

**Comment by asem-hamid** [comment]
i will add them.

**Comment by asem-hamid** [comment]
i am working on content/bn/releases/notes.md

**Comment by asem-hamid** [comment]
i am working on 
content/bn/releases/notes.md

**Comment by sajjadrahman56** [comment]
I am working on 
content/en/search.md

**Comment by azaynul10** [comment]
I am working on content/bn/docs/concepts/configuration/_index.md

**Comment by asem-hamid** [comment]
i am working on 

`content/en/docs/concepts/services-networking/_index.md`

**Comment by sajjadrahman56** [comment]
I am working on 
_content/en/docs/concepts/policy/_index.md_

**Comment by sajibAdhi** [comment]
I am localizing `content/en/docs/concepts/overview/_index.md`.

**Comment by asem-hamid** [comment]
@sajibAdhi  `content/en/docs/concepts/overview/_index.md.`   is the updated version of 
 `content/bn/docs/concepts/overview/what-is-kubernetes.md`  you update this rather than Localizing from scratch

**Comment by asem-hamid** [comment]
I am localizing `content/bn/releases/download.md`

**Comment by sajjadrahman56** [comment]
I am localizing `content/en/docs/concepts/workloads/pods/_index.md`

**Comment by itsPronay** [comment]
I'll be translating `content/bn/releases/patch-releases.md`

**Comment by asem-hamid** [comment]
@itsPronay  you can join us [here](https://kubernetes.slack.com/archives/CQ0TD298C)

**Comment by itsPronay** [comment]
I'll be localizing `content/bn/releases/release-managers.md`

**Comment by sajibAdhi** [comment]
> @sajibAdhi `content/en/docs/concepts/overview/_index.md.` is the updated version of `content/bn/docs/concepts/overview/what-is-kubernetes.md` . you can update this rather than Localizing from scratch

Thanks @asem-hamid.

**Comment by sajibAdhi** [comment]
I am working on `content/en/docs/setup/production-environment/tools/_index.md`

**Comment by saifulshark** [comment]
I am working on content/en/blog/_index.md

**Comment by saifulshark** [comment]
I am working on
content/en/blog/_index.md

**Comment by cloudwithtanvir** [comment]
Currently, I am working on : 

- content/en/docs/concepts/workloads/_index.md

- content/en/docs/concepts/overview/working-with-objects/_index.md

**Comment by saifulshark** [comment]
I am working on 
update content/bn/releases/_index.md

**Comment by asem-hamid** [comment]
@sajibAdhi  
update `content/bn/docs/setup/production-environment/_index.md`
This file has been assigned to you . Localize new lines and maintain proper line break

**Comment by sajjadrahman56** [comment]
i am working on `_content/en/docs/concepts/windows/_index.md_`

**Comment by asem-hamid** [comment]
i am working on `content/en/docs/concepts/extend-kubernetes/_index.md`

**Comment by azaynul10** [comment]
I am working on `content/en/docs/concepts/scheduling-eviction/_index.md`

**Comment by itsPronay** [comment]
Working on `content/en/docs/concepts/security/_index.md`

**Comment by itsPronay** [comment]
working on `content/en/partners/_index.html`

**Comment by itsPronay** [comment]
`content/en/docs/concepts/workloads/controllers/_index.md` on it

**Comment by azaynul10** [comment]
I will be working on `content/en/blog/_index.md`

**Comment by azaynul10** [comment]
I will be updating  `content/bn/docs/setup/production-environment/turnkey-solutions.md`

**Comment by azaynul10** [comment]
I will be updating `content/bn/docs/setup/production-environment/turnkey-solutions.md`

**Comment by sajjadrahman56** [comment]
i am working on _content/en/docs/concepts/cluster-administration/_index.md_

**Comment by azaynul10** [comment]
I will be working on `content/en/docs/setup/production-environment/tools/kubeadm/_index.md`

**Comment by itsPronay** [comment]
will be working on `bn/includes/partner-style.css`

**Comment by itsPronay** [comment]
will be working on `content/en/includes/user-guide-content-moved.md`

**Comment by sajibAdhi** [comment]
I am working on the glossary term_id sidecar-container. based on https://github.com/kubernetes/website/pull/45009#issuecomment-2020952243

**Comment by Nafisa-Tabassum-Mim** [comment]
i want to work on
 content/en/docs/concepts/extend-kubernetes/_index.md

**Comment by asem-hamid** [comment]
@Nafisa-Tabassum-Mim  
You can't take on that task; someone else is already handling it
![image](https://github.com/kubernetes/website/assets/155321064/ada24c30-0f05-40ad-96db-4ef695cd81bd)

**Comment by sftim** [comment]
>  You can't take on that task; someone else is already handling it

Any _can_ take on that task, but it's more helpful to pick a task that is waiting for help. Or to collaborate with someone who's said they intend to work on something.

This is because as a SIG we have a policy of “no cookie licking”: even if one person says they intend to work on a task, another person can also work on it. We still encourage folks to coordinate whereever feasible.

**Comment by Nafisa-Tabassum-Mim** [comment]
can i take this one???
add files at content/bn/case-studies

**Comment by itsPronay** [comment]
Please unassign me from `content/en/docs/concepts/workloads/controllers/_index.md`. Won't be working on this one.

**Comment by asem-hamid** [comment]
@sftim My apologies, it seems I made a mistake. 

What I meant to say is that " can't take on those tasks now because they already have a PR with a review. " 
Those tasks are nearing approval, which is why I intend to assign some unassigned tasks to her.

 Also Thank you for reminding me about that policy; I'll make sure to keep it in mind.

**Comment by asem-hamid** [comment]
@sftim My apologies, it seems I made a mistake.

My words should be :" can't take on those tasks now because they already have a PR with a review. "
Those tasks are nearing approval, which is why I intend to assign some unassigned tasks to her.

Also Thank you for reminding me about that policy; I'll make sure to keep it in mind.

**Comment by asem-hamid** [comment]
@itsPronay  ok

**Comment by sajibAdhi** [comment]
> can i take this one??? add files at content/bn/case-studies

@Nafisa-Tabassum-Mim yes you can.

**Comment by Nafisa-Tabassum-Mim** [comment]
content/en/docs/concepts/workloads/controllers/_index.md
i am doing this one

**Comment by asem-hamid** [comment]
@Nafisa-Tabassum-Mim  you need to submit the pull request that you declared first. after that's you can take another

**Comment by radiumSodium** [comment]
I am working on : 
content/bn/releases/release.md

**Comment by MRH-Romit** [comment]
i want to work  on docs/tasks/tools/included/optional-kubectl-configs-fish.md and  included/optional-kubectl-configs-pwsh.md

**Comment by sajjadrahman56** [comment]
I am working on _**content/bn/releases/version-skew-policy.md**_

**Comment by asem-hamid** [comment]
@MRH-Romit  those are already complete

![image](https://github.com/kubernetes/website/assets/155321064/f2532b99-5ba7-4914-8b4c-3b14a084f103)

**Comment by asem-hamid** [comment]
@MRH-Romit  They have already been completed

![image](https://github.com/kubernetes/website/assets/155321064/13c6ca1a-0172-4cd1-8116-ebb132e4c2cc)

**Comment by mitul3737** [comment]
> content/en/docs/concepts/workloads/controllers/_index.md i am doing this one

@Nafisa-Tabassum-Mim , have you completed working on it?

**Comment by asem-hamid** [comment]
unassigning  Nafisa-Tabassum-Mim from `content/en/docs/concepts/workloads/controllers/_index.md`

**Comment by SAShameem** [comment]
I am working on content/bn/examples

**Comment by asem-hamid** [comment]
Closing this issue in favor of  this [PR](https://github.com/kubernetes/website/pull/45009).

**Comment by asem-hamid** [comment]
## Hello Contributors,

As you may know, the first version of [Kubernetes in Bangla]( https://kubernetes.io/bn/) has been live since May 2024!

We are now ready to start our work on the second version of the Kubernetes Bangla documentation.

Our latest working branch is `dev-1.31-bn.1`.

## New Tracking Issue:

Our new tracking issue is #47747. Please refer to this issue for updates and progress.

## PR Guidelines:

When you create a new branch on your forked repo, make sure it’s based on the latest dev-1.31-bn.1 branch.

**Source Repository:**  `kubernetes/website`
**Source Branch:** `dev-1.31-bn.1`
**Target Branch:** `dev-1.31-bn.1` (when creating the PR)

Also, when submitting a PR, please include the following line in the description:

`Related issue: #47747`

Kubernetes in Bangla: https://kubernetes.io/bn/

Happy contributing!
