### ISSUE TITLE
[hi]  Umbrella issue for localizing /docs/setup/best-practice/ 

### ISSUE THREAD

**Issue by utkarsh-singh1** [kubernetes/website#45214]
**This is a Feature Request**

**What would you like to be added**
Localize docs/setup/best-practices/ in Hindi. As there are 5 pages to localize it will be best to have individual contributors working on each of the following listed pages.

- [ ] Localize [certificates.md](https://github.com/kubernetes/website/blob/main/content/en/docs/setup/best-practices/certificates.md)
- [ ] Localize [cluster-large.md](https://github.com/kubernetes/website/blob/main/content/en/docs/setup/best-practices/cluster-large.md)
- [ ] Localize [enforcing-pod-security-standards.md](https://github.com/kubernetes/website/blob/main/content/en/docs/setup/best-practices/enforcing-pod-security-standards.md)
- [ ] Localize [multiple-zones.md](https://github.com/kubernetes/website/blob/main/content/en/docs/setup/best-practices/multiple-zones.md)
- [ ] Localize [node-conformance.md](https://github.com/kubernetes/website/blob/main/content/en/docs/setup/best-practices/node-conformance.md)

Contributors who will be localizing these pages make sure to mention the pages you are localizing with your assign.

**Page -**
https://kubernetes.io/hi/docs/setup/best-practices/

**Comment by utkarsh-singh1** [comment]
Also follow these guidelines for localize content ⇾

- Before translation, try to adjust space, indentation or tab, sometimes it can change the meaning of passage or line.
- Remove any extra text or character like glossary_tooltip, {{}}, <> etc. or it may cause error.
- Lookout for term_id mention in [glossary_tooltip](https://github.com/kubernetes/website/tree/main/content/hi/docs/reference/glossary), wrong term_id can cause error.

**Comment by dipesh-rawat** [comment]
@utkarsh-singh1  Please refrain from labeling issues as "good first issue" until they have been properly triaged as accepted.

/remove-help 
/remove-good-first-issue

**Comment by dipesh-rawat** [comment]
I think the issue's scope is quite broad for contribution and subsequent review. The main requested page for localization seems to be the [index page](https://github.com/kubernetes/website/blob/main/content/hi/docs/setup/best-practices/_index.md), which is already localized. However, the challenge lies in [index page's](https://kubernetes.io/docs/setup/best-practices/) list content which is pulled from the front matter of other pages in the same directory, which includes a total of [five pages](https://github.com/kubernetes/website/tree/main/content/en/docs/setup/best-practices) that would need to be localized for this issue to be considered completed. To address this effectively, I suggest either narrowing down the scope of the issue or breaking it down into a task list, allowing multiple contributors to pick up different parts of the issue.

**Comment by KashishLakhara** [comment]
@dipesh-rawat I think it would be better if we retitle this as an umbrella issue like issue #35600  We can have 5 checkboxes for this issue and individual contributors can work on these checkboxes. By doing so, we can create a structured approach to track and manage the progress. 

- [ ] Localize [certificates.md](https://github.com/kubernetes/website/blob/main/content/en/docs/setup/best-practices/certificates.md)
- [ ] Localize [cluster-large.md](https://github.com/kubernetes/website/blob/main/content/en/docs/setup/best-practices/cluster-large.md)
- [ ] Localize [enforcing-pod-security-standards.md](https://github.com/kubernetes/website/blob/main/content/en/docs/setup/best-practices/enforcing-pod-security-standards.md)
- [ ] Localize [multiple-zones.md](https://github.com/kubernetes/website/blob/main/content/en/docs/setup/best-practices/multiple-zones.md)
- [ ] Localize [node-conformance.md](https://github.com/kubernetes/website/blob/main/content/en/docs/setup/best-practices/node-conformance.md)

**Comment by divya-mohan0209** [comment]
@utkarsh-singh1 : Could you please reword the description & retitle the whole issue to incorporate [this suggestion](https://github.com/kubernetes/website/issues/45214#issuecomment-1987299263)

**Comment by utkarsh-singh1** [comment]
> To address this effectively, I suggest either narrowing down the scope of the issue or breaking it down into a task list, allowing multiple contributors to pick up different parts of the issue.

It's better to have an umbrella issue that will cover the localization of these pages.

**Comment by utkarsh-singh1** [comment]
/retitle Umbrella issue for localizing /docs/setup/best-practice/ into hindi.

**Comment by utkarsh-singh1** [comment]
@Ayush9026, Have you made any progress in localizing the pages?

**Comment by utkarsh-singh1** [comment]
If not please mention the pages you are working with your assign tag.
