### ISSUE TITLE
[Umbrella tracking issue] SIG Docs Tech Leads onboarding: Kat & Xander

### ISSUE THREAD

**Issue by divya-mohan0209** [kubernetes/website#46303]
**Note for contributors: We are NOT ACCEPTING contributions for this issue from new/experienced contributors since this is to onboard our new tech leads, Kat & Xander. The PRs need to be submitted by them.**

# SIG Docs Tech Leads onboarding

On 30th April, Kat Cosgrove and Xander Grzywinski were [nominated](https://groups.google.com/g/kubernetes-sig-docs/c/lzUKjN_i8cA/m/RFXMBejbAwAJ?utm_medium=email&utm_source=footer) as the new tech leads for SIG Docs. 

## Transition date

A lazy consensus period till 8th May was also announced in the aforementioned nomination. 

## Required changes

Tech Lead onboarding requires some changes outlined below:

### Kat Cosgrove

| Repo  | file  | Complete?  |
|---|---|---|
| k/community  | [OWNERS_ALIASES](https://github.com/kubernetes/community/blob/master/OWNERS_ALIASES)  |   |
| k/community  | [sig-docs/README.md](https://github.com/kubernetes/community/blob/master/sig-docs/README.md)  |   |
| k/community  | [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md)  |   |
| k/community  | [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml#L1539) |   |
| k/enhancements  | [OWNERS_ALIASES](https://github.com/kubernetes/enhancements/blob/master/OWNERS_ALIASES#L46)   |   |
| k/org  | [OWNERS_ALIASES](https://github.com/kubernetes/org/blob/master/OWNERS_ALIASES#L45) |   |
| k/website OWNERS  | [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L11)  |   |
| k/website en OWNERS  | [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L41)  |   |
| k/website en REVIEWERS  | [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L50)  |   |
| k/website  | [SECURITY_CONTACTS](https://github.com/kubernetes/website/blob/master/SECURITY_CONTACTS) |   |
| kubernetes-sigs/reference | [OWNERS](https://github.com/kubernetes-sigs/reference-docs/blob/master/OWNERS) |   |

External tools you will need access to:

- [x] [Netlify](https://github.com/kubernetes/community/blob/master/sig-docs/netlify-access.md) => Collaborator access to be requested & documented.
- [x] [k8s-sig-docs-leads@ Google Group](https://groups.google.com/g/k8s-sig-docs-leads) => Membership to be requested
- [x] Google Analytics access => Will be automatically granted once access to **k8s-sig-docs-leads@ Google Group** is sorted.

### Xander Grzywinski

| Repo  | file  | Complete?  |
|---|---|---|
| k/community  | [OWNERS_ALIASES](https://github.com/kubernetes/community/blob/master/OWNERS_ALIASES)  |   |
| k/community  | [sig-docs/README.md](https://github.com/kubernetes/community/blob/master/sig-docs/README.md)  |   |
| k/community  | [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md)  |   |
| k/community  | [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml#L1539) |   |
| k/enhancements  | [OWNERS_ALIASES](https://github.com/kubernetes/enhancements/blob/master/OWNERS_ALIASES#L46)   |   |
| k/org  | [OWNERS_ALIASES](https://github.com/kubernetes/org/blob/master/OWNERS_ALIASES#L45) |   |
| k/website OWNERS  | [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L11)  |   |
| k/website en OWNERS  | [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L41)  |   |
| k/website en REVIEWERS  | [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L50)  |   |
| k/website  | [SECURITY_CONTACTS](https://github.com/kubernetes/website/blob/master/SECURITY_CONTACTS) |   |
| kubernetes-sigs/reference | [OWNERS](https://github.com/kubernetes-sigs/reference-docs/blob/master/OWNERS) |   |

External tools you will need access to:

- [x] [Netlify](https://github.com/kubernetes/community/blob/master/sig-docs/netlify-access.md) => Collaborator access to be requested & documented.
- [x] [k8s-sig-docs-leads@ Google Group](https://groups.google.com/g/k8s-sig-docs-leads) => Membership to be requested
- [x] Google Analytics access => Will be automatically granted once access to **k8s-sig-docs-leads@ Google Group** is sorted.

cc: @natalisucks @reylejano 

/sig docs

**Comment by natalisucks** [comment]
@divya-mohan0209 One other area that our new TLs will need to add themsleves to is the reference docs, and we'll need to make sure our onboarding is updated to reflect this: https://github.com/kubernetes-sigs/reference-docs/blob/master/OWNERS

**Comment by divya-mohan0209** [comment]
@natalisucks : Thanks for the catch, lemme add that on to the checklist above for both Kat & Xander.

**Comment by salaxander** [comment]
All my PRs have been created:

https://github.com/kubernetes/community/pull/7891
https://github.com/kubernetes/enhancements/pull/4626
https://github.com/kubernetes/org/pull/4941
https://github.com/kubernetes/website/pull/46312
https://github.com/kubernetes-sigs/reference-docs/pull/361

**Comment by katcosgrove** [comment]
All of my PRs are here:

https://github.com/kubernetes/community/pull/7893
https://github.com/kubernetes/website/pull/46345
https://github.com/kubernetes/org/pull/4947
https://github.com/kubernetes/enhancements/pull/4630
https://github.com/kubernetes-sigs/reference-docs/pull/362
