### ISSUE TITLE
AI: Scope out interactive/layered "Anatomy of a Kubernetes Cluster" diagram

### ISSUE THREAD

**Issue by abiogenesis-now** [kubernetes/website#4783]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
There isn't a very intuitive way to understand how all the different Kubernetes components tie together in the context of higher-level domains like security, networking, etc.

**Proposed Solution:**
Approximation of idea in https://docs.google.com/document/d/1-fpCxMAEfWucVLaDHKwYthVU3cIE962lsr6OTaqvpJg/edit# (heavily WIP).

**TLDR**
<img width="110" alt="anatomy gif" src="https://user-images.githubusercontent.com/25401650/29227608-5169279e-7e8b-11e7-89e4-75e0218932af.gif"> <img width="100" alt="plus sign" src="http://www.charbase.com/images/glyph/10133"> <img width="450" alt="basic k8s diagram" src="https://user-images.githubusercontent.com/25401650/29227710-c75d831e-7e8b-11e7-8320-d17b41f0c700.jpg"> 

**TODOS**
- [ ] Flesh out layers (@abiogenesis-now)
- [ ] Determine components per layer (@abiogenesis-now)
- [ ] Review (everyone -- SIG Docs and many engineers)
- [ ] Front-end magic (@chenopis)
- [ ] 🎉 

cc @chenopis @Bradamant3 @heidecke

**Comment by abiogenesis-now** [comment]
The idea is that this diagram would be particular helpful on the [What is Kubernetes](https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/) page.

**Comment by chenopis** [comment]
@alexcontini We might need your help on this too.
