### ISSUE TITLE
umbrella issue for InPlacePodVerticalScaling documentation

### ISSUE THREAD

**Issue by AnishShah** [kubernetes/website#48534]
**What would you like to be added**

```[tasklist]
### Tasks
- [ ] Documentation about new /resize subresource. (#128266)
- [ ] kubectl command for pod resize (#128296)
- [ ] Advise cluster admin to ensure validating / mutating admission policies are updated to also register for and handle `UPDATE pods/resize` requests
- [ ] Document InPlacePodVerticalScalingExclusiveCPUs for v1.32 , as suggested [here](https://github.com/kubernetes/kubernetes/pull/128287#issuecomment-2468770928)
```

**Why is this needed**

**Comments**

**Comment by sftim** [comment]
/retitle umbrella issue for InPlacePodVerticalScaling documentation

**Comment by tallclair** [comment]
/assign

placeholder PRs:
https://github.com/kubernetes/website/pull/48503
https://github.com/kubernetes/website/pull/48576

**Comment by tallclair** [comment]
This was covering the v1.32 issues. I filed https://github.com/kubernetes/website/issues/50022 to track v1.33 updates.

/close
