### ISSUE TITLE
[Tracking issue] Year-end activities for SIG Docs leadership

### ISSUE THREAD

**Issue by divya-mohan0209** [kubernetes/website#48843]
# We are not accepting contributions for this issue. This issue is to track [year-end activities](https://github.com/kubernetes/community/blob/master/sig-docs/annual-activities.md) that SIG Docs leads/chairs must carry out.

- [ ] Pruning the maintainers list
- [ ] Creating PR Wrangler schedule
- [ ] Creating Issue Wrangler schedule
- [ ] Preparing draft for Annual Report

/assign @kubernetes/sig-docs-leads 
/sig docs

**Comment by natalisucks** [comment]
I'm happy to create both the PR and Issue Wrangler schedules, and can get started on those soon. I'd like to propose that we advertise in #sig-docs whether experienced contributors want to newly be on the Issue Wrangler rotation so that we can get some new folks there 🫡

**Comment by natalisucks** [comment]
/triage accepted
i'll be using this issue to also track our 2026 TODOs.
cc. @divya-mohan0209 @reylejano
