### ISSUE TITLE
conformance status umbrella issue

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/website#7278]
As discussed on [the mailing list](https://groups.google.com/d/msg/kubernetes-sig-docs/GFnX8DRw7iY/8y3feBK5AAAJ), we are going enforce conformance rules on getting started guides and remove any guides that result in non-conformant cluster configuration by end of March (i.e. after 1.10 release).

This issue is an umbrella to track progress.

**Comment by errordeveloper** [comment]
Steps:

- [x] remove guides marked as deprecated (#7242)
- [ ] identify stale guides
- [ ] identify guides that are maintained but conformance status is unclear
